<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $permissions = [
            // Payment Settings
            'view payment settings',
            'edit payment settings',
            'test mpesa settings',
            'view customers',
            'create customers',
            'edit customers',
            'delete customers',
            'restore customers',
            'force delete customers',
            'export customers',
            'view general settings',
            'edit general settings',
            'view users',
            'create users',
            'edit users',
            'delete users',
            'assign roles',
            'assign permissions',
            'view email settings',
            'edit email settings',
            'test email settings',
            'view settings',
            'edit settings',
            'view animals',
            'create animals',
            'edit animals',
            'delete animals',
            'archive animals',
            'restore animals',
            'export animals',
            // Livestock Locations
            'view locations',
            'create locations',
            'edit locations',
            'delete locations',
            'view sold animals',
            'view dead culled animals',
            'view breeds',
            'create breeds',
            'edit breeds',
            'delete breeds',
            'export breeds',
            'view health records',
            'create health records',
            'edit health records',
            'delete health records',
            'export health records',
            'view breeding records',
            'create breeding records',
            'edit breeding records',
            'delete breeding records',
            'view weight records',
            'create weight records',
            'edit weight records',
            'delete weight records',
            'restore weight records',
            'force delete weight records',
            'export weight records',
            'view sales',
            'create sales',
            'edit sales',
            'delete sales',
            'approve sales',
            'export sales',
            'view income categories',
            'create income categories',
            'edit income categories',
            'delete income categories',
            'restore income categories',
            'force delete income categories',
            'export income categories',
            'view expenses',
            'create expenses',
            'edit expenses',
            'delete expenses',
            'approve expenses',
            'view petty cash',
            'manage petty cash',
            'export finance reports',
            'view hr dashboard',
            'view departments',
            'create departments',
            'edit departments',
            'delete departments',
            'view job titles',
            'create job titles',
            'edit job titles',
            'delete job titles',
            'view holidays',
            'create holidays',
            'edit holidays',
            'delete holidays',
            'view leave types',
            'create leave types',
            'edit leave types',
            'delete leave types',
            'view employees',
            'create employees',
            'edit employees',
            'delete employees',
            'restore employees',
            'force delete employees',
            'export employees',
            'view attendance',
            'manage attendance',
            'view leave applications',
            'create leave applications',
            'edit leave applications',
            'delete leave applications',
            'approve leave applications',
            'view payroll',
            'create payroll',
            'edit payroll',
            'delete payroll',
            'generate payroll',
            'approve payroll',
            'export payroll',
            'view payslips',
            'edit payslips',
            'delete payslips',
            'print payslips',
            'email payslips',
            'view salary advances',
            'create salary advances',
            'edit salary advances',
            'delete salary advances',
            'approve salary advances',
            'export salary advances',
            'view inventory',
            'create inventory',
            'edit inventory',
            'delete inventory',
            'manage stock movements',
            'view reports',
            'export reports',
            'print reports',
            'view casual payroll',
            'create casual payroll',
            'upload casual payroll',
            'edit casual payroll',
            'delete casual payroll',
            'export casual payroll',
            // Sales Invoices
            'view sales invoices',
            'create sales invoices',
            'edit sales invoices',
            'delete sales invoices',
            'restore sales invoices',
            'force delete sales invoices',
            'approve sales invoices',
            'cancel sales invoices',
            'export sales invoices',
            'print sales invoices',
            // Sales Payments
            'view sales payments',
            'create sales payments',
            'edit sales payments',
            'delete sales payments',
            'restore sales payments',
            'force delete sales payments',
            'verify sales payments',
            'export sales payments',
            // M-Pesa C2B Settings
            'view mpesa c2b settings',
            'edit mpesa c2b settings',
            'register mpesa c2b urls',
            'view mpesa c2b transactions',
            'verify mpesa c2b transactions',
            'view inventory items',
            'create inventory items',
            'edit inventory items',
            'delete inventory items',
            'view stock movements',
            'create stock movements',
            'edit stock movements',
            'delete stock movements',
            'view animal health records',
            'create animal health records',
            'edit animal health records',
            'delete animal health records',
            // Suppliers
            'view suppliers',
            'create suppliers',
            'edit suppliers',
            'delete suppliers',
            // Health Products
            'view health products',
            'create health products',
            'edit health products',
            'delete health products',
            // Inventory Items
            'view inventory items',
            'create inventory items',
            'edit inventory items',
            'delete inventory items',
            // Purchase Orders
            'view purchase orders',
            'create purchase orders',
            'edit purchase orders',
            'delete purchase orders',
            'receive purchase orders',
            // Stock Movements
            'view stock movements',
            'create stock movements',
            'edit stock movements',
            'delete stock movements',
            // Health Administrations
            'view health administrations',
            'create health administrations',
            'edit health administrations',
            'delete health administrations',
            'create purchase order payments',
            'view procurement dashboard',
            'approve purchase orders',
            'view supplier statements',
            'view payment vouchers',
            'view purchase order payments',
            'create purchase order payments',
            'edit purchase order payments',
            'delete purchase order payments',
            'print payment vouchers',
            'view breeding batches',
            'create breeding batches',
            'edit breeding batches',
            'delete breeding batches',
            'view breeding records',
            'edit breeding records',
            'view gestation rules',
            'create gestation rules',
            'edit gestation rules',
            'delete gestation rules',
            'view goods received notes',
            'create goods received notes',
            'print goods received notes',
            'view animal feedings',
            'create animal feedings',
            'print animal feedings',
            'view stock adjustments',
            'create stock adjustments',
            'view stock movements',
            'print stock movements',
            'view assets',
            'create assets',
            'edit assets',
            'delete assets',
            'restore assets',
            'force delete assets',
            'view asset valuations',
            'create asset valuations',
            'edit asset valuations',
            'delete asset valuations',
            'view asset maintenance',
            'create asset maintenance',
            'edit asset maintenance',
            'delete asset maintenance',
            'print asset reports',
            'print asset valuation report',
            'export assets',
            // Crop Farming
            'view crops',
            'create crops',
            'edit crops',
            'delete crops',
            'view crop fields',
            'create crop fields',
            'edit crop fields',
            'delete crop fields',
            'view crop seasons',
            'create crop seasons',
            'edit crop seasons',
            'delete crop seasons',
            'view nursery batches',
            'create nursery batches',
            'edit nursery batches',
            'delete nursery batches',
            'view crop input applications',
            'create crop input applications',
            'delete crop input applications',
            'view crop harvests',
            'create crop harvests',
            'edit crop harvests',
            'delete crop harvests',
            'view crop care tasks',
            'create crop care tasks',
            'edit crop care tasks',
            'delete crop care tasks',
            'print crop reports',
            'export crop reports',
            // Audit
            'view audit logs',
            'delete audit logs',
            'export audit logs',
            'view audit reports',
            'view audit settings',
            'edit audit settings',
            'view audit dashboard',
            'print audit session reports',
            'send audit session emails',
            'view projects',
            'create projects',
            'edit projects',
            'delete projects',
            'restore projects',
            'force delete projects',
            'view project categories',
            'create project categories',
            'edit project categories',
            'delete project categories',
            'view project milestones',
            'create project milestones',
            'edit project milestones',
            'delete project milestones',
            'view project tasks',
            'create project tasks',
            'edit project tasks',
            'delete project tasks',
            'view project budgets',
            'create project budgets',
            'edit project budgets',
            'delete project budgets',
            'approve project budgets',
            'view project expenses',
            'create project expenses',
            'edit project expenses',
            'delete project expenses',
            'approve project expenses',
            'view project progress',
            'create project progress',
            'edit project progress',
            'delete project progress',
            'view project documents',
            'upload project documents',
            'delete project documents',
            'print project reports',
            'export project reports',
            'view project dashboard',
            'view accounting dashboard',
            'view accounting reports',
            'view trial balance',
            'view general ledger',
            'view profit and loss',
            'view balance sheet',
            'view cash flow report',
            'view farm activity explorer',
            'download accounting pdf reports',
            'export accounting reports',
            'view accounting accounts',
            'create accounting accounts',
            'update accounting accounts',
            'delete accounting accounts',
            'view accounting fiscal years',
            'create accounting fiscal years',
            'update accounting fiscal years',
            'delete accounting fiscal years',
            'close accounting fiscal years',
            'reopen accounting fiscal years',
            'view accounting periods',
            'create accounting periods',
            'update accounting periods',
            'delete accounting periods',
            'close accounting periods',
            'reopen accounting periods',
            'view accounting cost centers',
            'create accounting cost centers',
            'update accounting cost centers',
            'delete accounting cost centers',
            'view accounting journal entries',
            'create accounting journal entries',
            'update accounting journal entries',
            'delete accounting journal entries',
            'post accounting journal entries',
            'approve accounting journal entries',
            'reverse accounting journal entries',
            'view accounting funding sources',
            'create accounting funding sources',
            'update accounting funding sources',
            'delete accounting funding sources',
            'view accounting project funds',
            'create accounting project funds',
            'update accounting project funds',
            'delete accounting project funds',
            'approve accounting project funds',
            'view accounting project fund transactions',
            'create accounting project fund transactions',
            'update accounting project fund transactions',
            'delete accounting project fund transactions',
            'approve accounting project fund transactions',
            'view accounting account mappings',
            'create accounting account mappings',
            'update accounting account mappings',
            'delete accounting account mappings',
            'view accounting opening balances',
            'create accounting opening balances',
            'update accounting opening balances',
            'delete accounting opening balances',
            'post accounting opening balances',
            'view accounting tax settings',
            'create accounting tax settings',
            'update accounting tax settings',
            'delete accounting tax settings',
            'view accounting reconciliations',
            'create accounting reconciliations',
            'update accounting reconciliations',
            'delete accounting reconciliations',
            'approve accounting reconciliations',
            'complete accounting reconciliations',
            'run accounting auto posting',
            'run accounting backfill',
            'manage accounting module',
            'view accounting dashboard',
            'view accounting reports',
            'view trial balance',
            'view general ledger',
            'view profit and loss',
            'view balance sheet',
            'view cash flow report',
            'view farm activity explorer',
            'download accounting pdf reports',
            'export accounting reports',
            'view accounting accounts',
            'create accounting accounts',
            'edit accounting accounts',
            'delete accounting accounts',
            'restore accounting accounts',
            'force delete accounting accounts',
            'view accounting fiscal years',
            'create accounting fiscal years',
            'edit accounting fiscal years',
            'delete accounting fiscal years',
            'restore accounting fiscal years',
            'force delete accounting fiscal years',
            'close accounting fiscal years',
            'reopen accounting fiscal years',
            'view accounting periods',
            'create accounting periods',
            'edit accounting periods',
            'delete accounting periods',
            'restore accounting periods',
            'force delete accounting periods',
            'close accounting periods',
            'reopen accounting periods',
            'view accounting cost centers',
            'create accounting cost centers',
            'edit accounting cost centers',
            'delete accounting cost centers',
            'restore accounting cost centers',
            'force delete accounting cost centers',
            'view accounting journal entries',
            'create accounting journal entries',
            'edit accounting journal entries',
            'delete accounting journal entries',
            'restore accounting journal entries',
            'force delete accounting journal entries',
            'post accounting journal entries',
            'approve accounting journal entries',
            'reverse accounting journal entries',
            'view accounting funding sources',
            'create accounting funding sources',
            'edit accounting funding sources',
            'delete accounting funding sources',
            'restore accounting funding sources',
            'force delete accounting funding sources',
            'view accounting project funds',
            'create accounting project funds',
            'edit accounting project funds',
            'delete accounting project funds',
            'restore accounting project funds',
            'force delete accounting project funds',
            'approve accounting project funds',
            'view accounting project fund transactions',
            'create accounting project fund transactions',
            'edit accounting project fund transactions',
            'delete accounting project fund transactions',
            'restore accounting project fund transactions',
            'force delete accounting project fund transactions',
            'approve accounting project fund transactions',
            'view accounting account mappings',
            'create accounting account mappings',
            'edit accounting account mappings',
            'delete accounting account mappings',
            'restore accounting account mappings',
            'force delete accounting account mappings',
            'view accounting opening balances',
            'create accounting opening balances',
            'edit accounting opening balances',
            'delete accounting opening balances',
            'restore accounting opening balances',
            'force delete accounting opening balances',
            'post accounting opening balances',
            'view accounting tax settings',
            'create accounting tax settings',
            'edit accounting tax settings',
            'delete accounting tax settings',
            'restore accounting tax settings',
            'force delete accounting tax settings',
            'view accounting reconciliations',
            'create accounting reconciliations',
            'edit accounting reconciliations',
            'delete accounting reconciliations',
            'restore accounting reconciliations',
            'force delete accounting reconciliations',
            'approve accounting reconciliations',
            'complete accounting reconciliations',
            'run accounting auto posting',
            'run accounting backfill',
            'manage accounting module',
            'view clinical cases',
            'create clinical cases',
            'edit clinical cases',
            'delete clinical cases',
            'view lab requests',
            'create lab requests',
            'edit lab requests',
            'delete lab requests',
            'view veterinary clinics',
            'create veterinary clinics',
            'edit veterinary clinics',
            'delete veterinary clinics',
            'view veterinary clinics',
            'create veterinary clinics',
            'edit veterinary clinics',
            'delete veterinary clinics',
            'view data center',
            'run database backups',
            'schedule database backups',
            'download database backups',
            'archive database backups',
            'restore database backups',
            'delete database backups',
            'clear application cache',
            'clear view cache',
            'clear route cache',
            'clear config cache',
            'clear filament cache',
            'clear all caches',
            'view data directories',
            'create data directories',
            'edit data directories',
            'delete data directories',
            'view data documents',
            'create data documents',
            'edit data documents',
            'delete data documents',
            'download data documents',
            'view customer geo intelligence',
            'print sales gatepasses',
            'view animal movement dashboard',
            'view animal transfers',
            'create animal transfers',
            'edit animal transfers',
            'delete animal transfers',
            'receive animal transfers',
            'print animal transfer reports',
            'view animal groups',
            'create animal groups',
            'edit animal groups',
            'delete animal groups',
            'sync animal groups',
            'print animal group reports',
            'print locations',
            'export locations',
        ];

        foreach (array_unique($permissions) as $permission) {
            Permission::firstOrCreate([
                'name' => $permission,
                'guard_name' => 'web',
            ]);
        }

        $roles = [
            'Administrator',
            'Director',
            'Manager',
            'Finance',
            'HR',
            'Veterinary Officer',
            'Farm Supervisor',
            'Data Entry Clerk',
        ];

        foreach ($roles as $role) {
            Role::firstOrCreate([
                'name' => $role,
                'guard_name' => 'web',
            ]);
        }

        $admin = User::where('email', 'nzioki.dev@gmail.com')->first();

        if ($admin) {
            $admin->syncRoles(['Administrator']);
            $admin->syncPermissions($permissions);
        }

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}
