@php
    use App\Models\Settings\PaymentSetting;

    if (! function_exists('pdfImageBase64')) {
        function pdfImageBase64(?string $path): ?string
        {
            if (! $path) {
                return null;
            }

            $cleanPath = trim((string) $path);
            $cleanPath = ltrim($cleanPath, '/');
            $cleanPath = preg_replace('#^storage/#', '', $cleanPath);
            $cleanPath = preg_replace('#^public/#', '', $cleanPath);

            $possiblePaths = [
                storage_path('app/public/' . $cleanPath),
                public_path('storage/' . $cleanPath),
                public_path($cleanPath),
            ];

            foreach ($possiblePaths as $fullPath) {
                if (is_file($fullPath)) {
                    $extension = strtolower(pathinfo($fullPath, PATHINFO_EXTENSION));

                    $mime = match ($extension) {
                        'jpg', 'jpeg' => 'image/jpeg',
                        'png' => 'image/png',
                        'gif' => 'image/gif',
                        'webp' => 'image/webp',
                        'svg' => 'image/svg+xml',
                        'ico' => 'image/x-icon',
                        default => 'image/png',
                    };

                    return 'data:' . $mime . ';base64,' . base64_encode(file_get_contents($fullPath));
                }
            }

            return null;
        }
    }

    $paymentSettings = PaymentSetting::current();

    $eatNow = now('Africa/Nairobi');

    $farmName = setting('farm.name', 'Lelekwe Farms');
    $farmTagline = setting('farm.tagline', 'Nurturing Nature, Feeding The Future');
    $farmPhone = setting('farm.phone', '+254 743 487 186');
    $farmEmail = setting('farm.email', 'jambo@lelekwefarms.co.ke');
    $farmCounty = setting('farm.county', 'Ravine, Kambi Moto');
    $farmAddress = setting('farm.address', $farmCounty);

    $primaryColor = trim(setting('theme.primary', '#014a12'));
    $secondaryColor = trim(setting('theme.secondary', '#14532d'));
    $accentColor = trim(setting('theme.accent', '#f59e0b'));
    $successColor = trim(setting('theme.success', '#16a34a'));
    $dangerColor = trim(setting('theme.danger', '#dc2626'));

    $logoBase64 = pdfImageBase64(setting('branding.logo_light'));

    $signatureBase64 = pdfImageBase64(
        data_get($paymentSettings, 'authorized_signature_image')
        ?: data_get($paymentSettings, 'signature_path')
        ?: data_get($paymentSettings, 'authorized_signature_path')
        ?: setting('branding.signature')
    );

    $stampBase64 = pdfImageBase64(
        data_get($paymentSettings, 'payment_stamp_image')
        ?: data_get($paymentSettings, 'stamp_path')
        ?: data_get($paymentSettings, 'official_stamp_path')
        ?: setting('branding.stamp')
    );

    $generatedByName = $generatedBy?->name ?? 'System';
    $generatedByRole = $generatedByRole ?? 'User';

    $totalAnimals = $transfer->items->count();

    $verificationText =
        $farmName .
        ' Animal Transfer Report | Transfer: ' .
        $transfer->transfer_number .
        ' | Status: ' .
        $transfer->status_label .
        ' | From: ' .
        ($transfer->fromLocation?->name ?? 'Mixed / Current') .
        ' | To: ' .
        ($transfer->toLocation?->name ?? '-') .
        ' | Animals: ' .
        $totalAnimals .
        ' | Generated by: ' .
        $generatedByName .
        ' (' .
        $generatedByRole .
        ')' .
        ' | Date: ' .
        $eatNow->format('Y-m-d H:i:s') .
        ' EAT';

    $qrPng = null;

    if (class_exists(\SimpleSoftwareIO\QrCode\Facades\QrCode::class)) {
        try {
            $qrPng = base64_encode(
                \SimpleSoftwareIO\QrCode\Facades\QrCode::format('png')
                    ->size(110)
                    ->margin(1)
                    ->generate($verificationText)
            );
        } catch (\Throwable) {
            $qrPng = null;
        }
    }

    $statusColor = match ($transfer->status) {
        'completed' => $successColor,
        'cancelled' => $dangerColor,
        'draft' => '#6b7280',
        default => $accentColor,
    };
@endphp

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $transfer->transfer_number }}</title>

    <style>
        @page {
            margin: 118px 34px 92px 34px;
        }

        body {
            margin: 0;
            font-family: Courier, "Courier New", monospace;
            font-size: 10.5px;
            color: #111827;
            background: #ffffff;
            position: relative;
        }

        .watermark {
            position: fixed;
            top: 30%;
            left: 12%;
            width: 76%;
            opacity: 0.035;
            z-index: -10;
            text-align: center;
        }

        .watermark img {
            width: 430px;
        }

        header {
            position: fixed;
            top: -96px;
            left: 0;
            right: 0;
            height: 88px;
            border-bottom: 3px solid {{ $primaryColor }};
        }

        footer {
            position: fixed;
            bottom: -70px;
            left: 0;
            right: 0;
            height: 58px;
            border-top: 1px solid #d1d5db;
            color: #4b5563;
            font-size: 9px;
        }

        .header-table,
        .footer-table,
        .summary-table,
        .items,
        .signature-table {
            width: 100%;
            border-collapse: collapse;
        }

        .header-table td {
            vertical-align: middle;
        }

        .logo {
            width: 140px;
            max-height: 80px;
            object-fit: contain;
        }

        .company-title {
            text-align: center;
            font-size: 15px;
            font-weight: bold;
            color: {{ $primaryColor }};
            text-transform: uppercase;
            letter-spacing: .4px;
        }

        .tagline {
            text-align: center;
            margin-top: 3px;
            font-size: 9.5px;
            color: #4b5563;
            font-style: italic;
        }

        .header-right {
            width: 230px;
            text-align: right;
            font-size: 9px;
            line-height: 1.55;
        }

        .footer-table {
            margin-top: 7px;
        }

        .footer-left {
            width: 33%;
            text-align: left;
        }

        .footer-center {
            width: 34%;
            text-align: center;
        }

        .footer-right {
            width: 33%;
            text-align: right;
        }

        .small-muted {
            color: #6b7280;
            font-size: 8.5px;
            line-height: 1.35;
        }

        .report-top {
            margin-bottom: 14px;
            border: 1px solid #dbe4d3;
            border-left: 7px solid {{ $primaryColor }};
            background: #fbfdf9;
            padding: 12px 14px;
        }

        .report-title-table {
            width: 100%;
            border-collapse: collapse;
        }

        .report-title {
            margin: 0;
            color: #111827;
            font-size: 23px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: .7px;
        }

        .report-subtitle {
            margin-top: 4px;
            color: {{ $primaryColor }};
            font-size: 10px;
            font-weight: bold;
            line-height: 1.45;
        }

        .report-total-box {
            text-align: right;
        }

        .report-total-label {
            color: #6b7280;
            font-size: 8.5px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .report-total-value {
            margin-top: 3px;
            color: {{ $primaryColor }};
            font-size: 20px;
            font-weight: bold;
        }

        .status-badge {
            display: inline-block;
            margin-top: 6px;
            padding: 4px 8px;
            border-radius: 999px;
            background: {{ $statusColor }};
            color: #ffffff;
            font-size: 8.5px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .summary-table {
            border-spacing: 10px 0;
            border-collapse: separate;
            margin-bottom: 12px;
        }

        .summary-card {
            width: 50%;
            vertical-align: top;
            border: 1px solid #dbe4d3;
            background: #ffffff;
            padding: 11px;
        }

        .card-heading {
            margin-bottom: 8px;
            color: {{ $primaryColor }};
            font-size: 11px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .info-row {
            border-bottom: 1px solid #edf2ea;
            padding: 5px 0;
        }

        .info-label {
            display: inline-block;
            width: 38%;
            color: #6b7280;
            font-size: 9px;
        }

        .info-value {
            color: #111827;
            font-weight: bold;
        }

        .note-box {
            margin-top: 12px;
            margin-bottom: 12px;
            border: 1px solid #e5e7eb;
            border-left: 5px solid {{ $accentColor }};
            background: #fffdf7;
            padding: 10px;
            line-height: 1.55;
        }

        .items {
            margin-top: 10px;
            border-collapse: collapse;
        }

        .items th {
            border: 1px solid {{ $primaryColor }};
            background: {{ $primaryColor }};
            color: #ffffff;
            padding: 7px;
            font-size: 9.5px;
            text-align: left;
            text-transform: uppercase;
        }

        .items td {
            border: 1px solid #e5e7eb;
            padding: 7px;
            vertical-align: top;
        }

        .items tr:nth-child(even) {
            background: #fafafa;
        }

        .signature-block {
            margin-top: 20px;
            page-break-inside: avoid;
        }

        .signature-table {
            border-spacing: 8px 0;
            border-collapse: separate;
        }

        .signature-card {
            min-height: 116px;
            border: 1px solid #dbe4d3;
            background: #fbfdf9;
            padding: 10px;
            vertical-align: top;
        }

        .signature-title {
            margin-bottom: 7px;
            color: {{ $secondaryColor }};
            font-size: 9.5px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .signature-name {
            color: #111827;
            font-size: 12px;
            font-weight: bold;
        }

        .signature-line {
            margin-top: 14px;
            border-top: 1px solid #4b5563;
            padding-top: 5px;
        }

        .signature-img {
            max-width: 155px;
            max-height: 60px;
            display: block;
            margin: 4px auto 6px auto;
            object-fit: contain;
        }

        .signature-placeholder {
            height: 58px;
            border: 1px dashed #9ca3af;
            background: #ffffff;
            text-align: center;
            color: #6b7280;
            font-size: 9px;
            line-height: 58px;
            margin-bottom: 6px;
        }

        .stamp-wrap {
            text-align: center;
        }

        .stamp-img {
            max-width: 118px;
            max-height: 96px;
            display: block;
            margin: 0 auto 5px auto;
            object-fit: contain;
        }

        .stamp-placeholder {
            width: 96px;
            height: 96px;
            margin: 0 auto 6px auto;
            border: 2px dashed {{ $primaryColor }};
            border-radius: 50%;
            display: table;
            background: #ffffff;
        }

        .stamp-placeholder span {
            display: table-cell;
            vertical-align: middle;
            text-align: center;
            color: {{ $primaryColor }};
            font-size: 10px;
            font-weight: bold;
            line-height: 1.35;
        }

        .qr-box {
            text-align: center;
        }

        .qr-image-wrap,
        .qr-fallback {
            width: 96px;
            height: 96px;
            margin: 0 auto 6px auto;
            border: 2px solid {{ $primaryColor }};
            background: #ffffff;
            padding: 4px;
        }

        .qr-image {
            width: 86px;
            height: 86px;
        }
    </style>
</head>

<body>
    @if ($logoBase64)
        <div class="watermark">
            <img src="{{ $logoBase64 }}" alt="Watermark">
        </div>
    @endif

    <header>
        <table class="header-table">
            <tr>
                <td width="150">
                    @if ($logoBase64)
                        <img src="{{ $logoBase64 }}" class="logo" alt="Logo">
                    @endif
                </td>

                <td>
                    <div class="company-title">{{ $farmName }}</div>
                    <div class="tagline">{{ $farmTagline }}</div>
                </td>

                <td class="header-right">
                    <strong>Phone:</strong> {{ $farmPhone }}<br>
                    <strong>Email:</strong> {{ $farmEmail }}<br>
                    <strong>Location:</strong> {{ $farmAddress }}
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table class="footer-table">
            <tr>
                <td class="footer-left">
                    Printed {{ $eatNow->format('d M Y, H:i') }} EAT
                </td>
                <td class="footer-center">
                    Animal Transfer • {{ $transfer->transfer_number }}
                </td>
                <td class="footer-right">
                    Created by {{ $generatedByName }} ({{ $generatedByRole }})
                </td>
            </tr>
            <tr>
                <td colspan="3" class="footer-center small-muted">
                    {{ $farmName }} • {{ $farmCounty }} • {{ $farmPhone }} • {{ $farmEmail }}
                </td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="report-top">
            <table class="report-title-table">
                <tr>
                    <td>
                        <h1 class="report-title">Animal Transfer Report</h1>
                        <div class="report-subtitle">
                            {{ $transfer->transfer_number }}
                            • {{ $transfer->fromLocation?->name ?? 'Mixed / Current' }}
                            → {{ $transfer->toLocation?->name ?? '-' }}
                        </div>
                        <span class="status-badge">{{ $transfer->status_label }}</span>
                    </td>

                    <td class="report-total-box" width="210">
                        <div class="report-total-label">Total Animals</div>
                        <div class="report-total-value">
                            {{ number_format($totalAnimals) }}
                        </div>
                    </td>
                </tr>
            </table>
        </div>

        <table class="summary-table">
            <tr>
                <td class="summary-card">
                    <div class="card-heading">Movement Details</div>

                    <div class="info-row">
                        <span class="info-label">From</span>
                        <span class="info-value">{{ $transfer->fromLocation?->name ?? 'Mixed / Current' }}</span>
                    </div>

                    <div class="info-row">
                        <span class="info-label">To</span>
                        <span class="info-value">{{ $transfer->toLocation?->name ?? '-' }}</span>
                    </div>

                    <div class="info-row">
                        <span class="info-label">Transfer Date</span>
                        <span class="info-value">{{ $transfer->transfer_date?->format('d M Y') }}</span>
                    </div>

                    <div class="info-row">
                        <span class="info-label">Expected</span>
                        <span class="info-value">{{ $transfer->expected_receive_date?->format('d M Y') ?? '-' }}</span>
                    </div>

                    <div class="info-row">
                        <span class="info-label">Received</span>
                        <span class="info-value">{{ $transfer->received_at?->format('d M Y H:i') ?? '-' }}</span>
                    </div>
                </td>

                <td class="summary-card">
                    <div class="card-heading">Control Details</div>

                    <div class="info-row">
                        <span class="info-label">Prepared By</span>
                        <span class="info-value">{{ $transfer->preparedBy?->name ?? '-' }}</span>
                    </div>

                    <div class="info-row">
                        <span class="info-label">Received By</span>
                        <span class="info-value">{{ $transfer->receivedBy?->name ?? '-' }}</span>
                    </div>

                    <div class="info-row">
                        <span class="info-label">Animals</span>
                        <span class="info-value">{{ number_format($totalAnimals) }}</span>
                    </div>

                    <div class="info-row">
                        <span class="info-label">Reason</span>
                        <span class="info-value">{{ $transfer->reason ?? '-' }}</span>
                    </div>

                    <div class="info-row">
                        <span class="info-label">Status</span>
                        <span class="info-value">{{ $transfer->status_label }}</span>
                    </div>
                </td>
            </tr>
        </table>

        @if ($transfer->notes || $transfer->receive_notes)
            <div class="note-box">
                @if ($transfer->notes)
                    <strong>Transfer Notes:</strong> {{ $transfer->notes }}<br>
                @endif

                @if ($transfer->receive_notes)
                    <strong>Receive Notes:</strong> {{ $transfer->receive_notes }}
                @endif
            </div>
        @endif

        <table class="items">
            <thead>
                <tr>
                    <th width="5%">#</th>
                    <th width="18%">Animal Tag</th>
                    <th width="22%">Breed</th>
                    <th width="10%">Sex</th>
                    <th width="18%">From</th>
                    <th width="18%">To</th>
                    <th width="9%">Status</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($transfer->items as $index => $item)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td><strong>{{ $item->tag_number }}</strong></td>
                        <td>{{ $item->breed_name ?: ($item->animal?->breed?->breed_name ?? '-') }}</td>
                        <td>{{ $item->sex ?: ($item->animal?->sex ?? '-') }}</td>
                        <td>{{ $item->fromLocation?->name ?? '-' }}</td>
                        <td>{{ $item->toLocation?->name ?? '-' }}</td>
                        <td>{{ str($item->status)->title() }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="signature-block">
            <table class="signature-table">
                <tr>
                    <td class="signature-card" style="width: 26%;">
                        <div class="signature-title">Prepared By</div>
                        <div class="signature-name">{{ $transfer->preparedBy?->name ?? $generatedByName }}</div>
                        <div class="small-muted">{{ $generatedByRole }}</div>
                        <div class="signature-line"></div>
                        <div class="small-muted">
                            Generated {{ $eatNow->format('d M Y, H:i') }} EAT
                        </div>
                    </td>

                    <td class="signature-card" style="width: 28%; text-align: center;">
                        <div class="signature-title">Authorized Signature</div>

                        @if ($signatureBase64)
                            <img src="{{ $signatureBase64 }}" class="signature-img" alt="Authorized Signature">
                        @else
                            <div class="signature-placeholder">Signature not uploaded</div>
                        @endif

                        <div class="small-muted">
                            {{ $farmName }} Management Approval
                        </div>
                    </td>

                    <td class="signature-card stamp-wrap" style="width: 22%;">
                        <div class="signature-title">Official Stamp</div>

                        @if ($stampBase64)
                            <img src="{{ $stampBase64 }}" class="stamp-img" alt="Official Stamp">
                        @else
                            <div class="stamp-placeholder">
                                <span>STAMP<br>NOT<br>UPLOADED</span>
                            </div>
                        @endif

                        <div class="small-muted">{{ $farmName }}</div>
                    </td>

                    <td class="signature-card" style="width: 24%;">
                        <div class="qr-box">
                            <div class="signature-title">Verification</div>

                            @if (! empty($qrPng))
                                <div class="qr-image-wrap">
                                    <img src="data:image/png;base64,{{ $qrPng }}" class="qr-image" alt="QR Code">
                                </div>
                            @else
                                <div class="qr-fallback">
                                    <span class="small-muted">QR not available</span>
                                </div>
                            @endif

                            <div class="small-muted">
                                Scan to verify transfer metadata
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </main>

    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
                $font = $fontMetrics->getFont('Helvetica', 'normal');
                $size = 8.5;

                $text = "Page {$pageNumber} of {$pageCount}";
                $width = $fontMetrics->getTextWidth($text, $font, $size);

                $x = ($canvas->get_width() - $width) / 2;
                $y = $canvas->get_height() - 30;

                $canvas->text($x, $y, $text, $font, $size, [0.42, 0.45, 0.50]);
            });
        }
    </script>
</body>
</html>
