@php
    if (! function_exists('pdfImageBase64')) {
        function pdfImageBase64(?string $path): ?string
        {
            if (! $path) {
                return null;
            }

            $cleanPath = trim($path);
            $cleanPath = ltrim($cleanPath, '/');
            $cleanPath = preg_replace('#^storage/#', '', $cleanPath);

            $possiblePaths = [
                storage_path('app/public/' . $cleanPath),
                public_path('storage/' . $cleanPath),
                public_path($cleanPath),
            ];

            foreach ($possiblePaths as $fullPath) {
                if (is_file($fullPath)) {
                    $extension = strtolower(pathinfo($fullPath, PATHINFO_EXTENSION));

                    $mime = match ($extension) {
                        'jpg', 'jpeg' => 'image/jpeg',
                        'png' => 'image/png',
                        'gif' => 'image/gif',
                        'webp' => 'image/webp',
                        'svg' => 'image/svg+xml',
                        default => 'image/png',
                    };

                    return 'data:' . $mime . ';base64,' . base64_encode(file_get_contents($fullPath));
                }
            }

            return null;
        }
    }

    $eatNow = now('Africa/Nairobi');

    $farmName = setting('farm.name', 'Lelekwe Farms');
    $farmTagline = setting('farm.tagline', 'Nurturing Nature, Feeding The Future');
    $farmPhone = setting('farm.phone', '+254 743 487 186');
    $farmEmail = setting('farm.email', 'jambo@lelekwefarms.co.ke');
    $farmCounty = setting('farm.county', 'Ravine, Kambi Moto');

    $primaryColor = trim(setting('theme.primary', '#008f00'));
    $secondaryColor = trim(setting('theme.secondary', '#14532d'));
    $accentColor = trim(setting('theme.accent', '#f59e0b'));
    $dangerColor = trim(setting('theme.danger', '#dc2626'));
    $successColor = trim(setting('theme.success', '#16a34a'));

    $logoBase64 = pdfImageBase64(setting('branding.logo_light'));

    $generatedByName = $generatedBy->name ?? 'System';
    $generatedByRole = $generatedByRole ?? 'User';

    $maxAverage = max((float) ($breedAverages->max('avg_weight') ?? 1), 1);
    $totalAnimals = (int) $breedAverages->sum('animals_count');

    $overallAverage = $totalAnimals > 0
        ? $breedAverages->sum(fn ($breed) => ((float) $breed->avg_weight * (int) $breed->animals_count)) / $totalAnimals
        : 0;

    $verificationText =
        $farmName . ' Breed Weight Intelligence Report | Generated by: ' .
        $generatedByName . ' (' . $generatedByRole . ')' .
        ' | Date: ' . $eatNow->format('Y-m-d H:i:s') .
        ' EAT | Breeds: ' . $breedAverages->count() .
        ' | Animals: ' . $totalAnimals;

    $qrImage = null;

    if (class_exists(\SimpleSoftwareIO\QrCode\Facades\QrCode::class)) {
        try {
            $qrImage = 'data:image/png;base64,' . base64_encode(
                \SimpleSoftwareIO\QrCode\Facades\QrCode::format('png')
                    ->size(110)
                    ->margin(1)
                    ->generate($verificationText)
            );
        } catch (\Throwable $e) {
            $qrImage = null;
        }
    }

    $barColors = [
        '#008f00',
        '#2563eb',
        '#dc2626',
        '#f59e0b',
        '#7c3aed',
        '#0891b2',
        '#16a34a',
        '#ea580c',
        '#be123c',
        '#0f766e',
    ];
@endphp

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Breed Weight Intelligence Report</title>

    <style>
         @font-face {
            font-family: "ChopinScript";
            src: url("{{ public_path('fonts/ChopinScript.ttf') }}") format("truetype");
            font-weight: normal;
            font-style: normal;
        }

        .signature-handwritten {
            font-family: "ChopinScript" !important;
            font-size: 25px;
            color: {{ $successColor }};
            letter-spacing: 1px;
        }
        @page {
            margin: 120px 35px 95px 35px;
        }

        body {
            font-family: Courier, sans-serif;
            font-size: 11px;
            color: #1f2937;
        }

        .watermark {
            position: fixed;
            top: 30%;
            left: 12%;
            width: 75%;
            opacity: 0.055;
            z-index: -1;
            text-align: center;
        }

        .watermark img {
            width: 420px;
        }

        header {
            position: fixed;
            top: -95px;
            left: 0;
            right: 0;
            height: 90px;
            border-bottom: 2px solid {{ $primaryColor }};
        }

        .header-table,
        .footer-table,
        .report,
        .summary-grid,
        .signature-table {
            width: 100%;
            border-collapse: collapse;
        }

        .header-left {
            width: 130px;
            text-align: left;
            vertical-align: middle;
        }

        .header-center {
            text-align: center;
            vertical-align: middle;
        }

        .header-right {
            width: 230px;
            text-align: right;
            vertical-align: middle;
            font-size: 10px;
            line-height: 1.5;
            color: #374151;
        }

        .logo {
            width: 175px;
            max-height: 75px;
        }

        .company-title {
            font-size: 22px;
            font-weight: bold;
            color: {{ $primaryColor }};
            margin-bottom: 2px;
        }

        .tagline {
            font-size: 11px;
            color: #4b5563;
            font-style: italic;
        }

        footer {
            position: fixed;
            bottom: -72px;
            left: 0;
            right: 0;
            height: 62px;
            border-top: 1px solid #d1d5db;
            font-size: 10px;
            color: #4b5563;
        }

        .footer-table {
            margin-top: 8px;
        }

        .footer-left {
            text-align: left;
            width: 33%;
        }

        .footer-center {
            text-align: center;
            width: 34%;
        }

        .footer-right {
            text-align: right;
            width: 33%;
        }

        .small-muted {
            color: #6b7280;
            font-size: 9px;
        }

        .report-title {
            margin-bottom: 14px;
        }

        .report-title h1 {
            margin: 0 0 4px 0;
            font-size: 19px;
            color: #111827;
        }

        .report-title p {
            margin: 0;
            color: {{ $primaryColor }};
            font-size: 10px;
        }

        .summary-grid {
            margin-bottom: 16px;
        }

        .summary-grid td {
            width: 25%;
            border: 1px solid #d1d5db;
            padding: 11px;
            background: #fbfdf9;
        }

        .summary-label {
            font-size: 9px;
            color: #6b7280;
            text-transform: uppercase;
            margin-bottom: 5px;
        }

        .summary-value {
            font-size: 15px;
            font-weight: bold;
            color: {{ $primaryColor }};
        }

        .chart-title {
            margin: 18px 0 8px 0;
            padding: 8px 10px;
            background: {{ $primaryColor }};
            color: #fff;
            font-weight: bold;
            font-size: 12px;
        }

        .chart-row {
            margin-bottom: 8px;
        }

        .chart-label {
            width: 28%;
            display: inline-block;
            font-weight: bold;
            font-size: 10px;
        }

        .chart-track {
            width: 55%;
            height: 12px;
            display: inline-block;
            background: #e5e7eb;
            vertical-align: middle;
        }

        .chart-bar {
            height: 12px;
            display: block;
        }

        .chart-value {
            width: 15%;
            display: inline-block;
            text-align: right;
            font-weight: bold;
            font-size: 10px;
        }

        .insight-box {
            margin-top: 14px;
            border: 1px solid #d1d5db;
            padding: 11px;
            background: #fffdf5;
            font-size: 10px;
            line-height: 1.55;
        }

        table.report {
            margin-top: 12px;
        }

        table.report th {
            background: {{ $primaryColor }};
            color: #fff;
            border: 1px solid {{ $primaryColor }};
            padding: 9px 7px;
            text-align: left;
            font-size: 10px;
        }

        table.report td {
            border: 1px solid #e5e7eb;
            padding: 8px 7px;
            vertical-align: middle;
        }

        table.report tr:nth-child(even) {
            background: #f9fafb;
        }

        .badge {
            display: inline-block;
            padding: 4px 8px;
            background: #ecfdf5;
            color: {{ $secondaryColor }};
            border: 1px solid #bbf7d0;
            font-weight: bold;
            font-size: 9px;
        }

        .weight {
            font-weight: bold;
            color: #111827;
        }

        .muted {
            color: #6b7280;
        }

        .section-block {
            margin-top: 30px;
        }

        .signature-table td {
            vertical-align: top;
        }

        .signature-card {
            border: 1px solid #dbe4d3;
            padding: 12px 14px;
            background: #fbfdf9;
            min-height: 120px;
        }

        .signature-card-title {
            font-size: 11px;
            font-weight: bold;
            color: {{ $secondaryColor }};
            margin-bottom: 10px;
            text-transform: uppercase;
            letter-spacing: 0.4px;
        }

        .signature-name {
            font-size: 13px;
            font-weight: bold;
            color: #111827;
            margin-bottom: 4px;
        }

        .signature-meta,
        .signature-footer {
            font-size: 9px;
            color: #6b7280;
        }

        .signature-line {
            border-top: 1px solid #4b5563;
            margin-top: 18px;
            padding-top: 6px;
        }

        .stamp-circle {
            width: 110px;
            height: 110px;
            margin: 0 auto 8px auto;
            border: 1px dashed {{ $primaryColor }};
            border-radius: 50%;
            display: table;
        }

        .stamp-text {
            display: table-cell;
            vertical-align: middle;
            text-align: center;
            font-size: 12px;
            font-weight: bold;
            color: {{ $primaryColor }};
            line-height: 1.4;
        }

        .stamp-caption {
            font-size: 9px;
            color: #6b7280;
            text-align: center;
        }

        .qr-box {
            text-align: center;
        }

        .qr-image-wrap {
            width: 104px;
            height: 104px;
            margin: 4px auto 8px auto;
            padding: 4px;
            border: 2px solid {{ $primaryColor }};
            background: #fff;
        }

        .qr-image {
            width: 90px;
            height: 90px;
            display: block;
            margin: 0 auto;
        }

        .qr-caption {
            font-size: 8px;
            color: #6b7280;
            margin-top: 6px;
            line-height: 1.4;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="watermark">
        @if ($logoBase64)
            <img src="{{ $logoBase64 }}" alt="Watermark">
        @endif
    </div>

    <header>
        <table class="header-table">
            <tr>
                <td class="header-left">
                    @if ($logoBase64)
                        <img src="{{ $logoBase64 }}" class="logo" alt="Logo">
                    @endif
                </td>

                <td class="header-center">
                    <div class="company-title">{{ $farmName }}</div>
                    <div class="tagline">{{ $farmTagline }}</div>
                </td>

                <td class="header-right">
                    <strong>Phone:</strong> {{ $farmPhone }}<br>
                    <strong>Email:</strong> {{ $farmEmail }}<br>
                    <strong>County:</strong> {{ $farmCounty }}
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table class="footer-table">
            <tr>
                <td class="footer-left">
                    Printed on {{ $eatNow->format('d M Y, H:i') }} EAT
                </td>
                <td class="footer-center">
                    Breed Weight Intelligence Report
                </td>
                <td class="footer-right">
                    Created by {{ $generatedByName }} ({{ $generatedByRole }})
                </td>
            </tr>
            <tr>
                <td colspan="3" class="footer-center small-muted">
                    {{ $farmName }} • {{ $farmCounty }} • {{ $farmPhone }} • {{ $farmEmail }}
                </td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="report-title">
            <h1>Breed Weight Intelligence Report</h1>
            <p>Sales-focused weight performance report based on latest animal weights.</p>
        </div>

        <table class="summary-grid">
            <tr>
                <td>
                    <div class="summary-label">Breeds Analysed</div>
                    <div class="summary-value">{{ $breedAverages->count() }}</div>
                </td>
                <td>
                    <div class="summary-label">Animals Included</div>
                    <div class="summary-value">{{ number_format($totalAnimals) }}</div>
                </td>
                <td>
                    <div class="summary-label">Overall Avg Weight</div>
                    <div class="summary-value">{{ number_format($overallAverage, 2) }} KG</div>
                </td>
                <td>
                    <div class="summary-label">Leading Breed</div>
                    <div class="summary-value">{{ $breedAverages->first()?->breed_name ?? 'N/A' }}</div>
                </td>
            </tr>
        </table>

        <div class="chart-title">Breed Average Weight Chart</div>

        @foreach ($breedAverages as $index => $breed)
            @php
                $percent = min(100, ((float) $breed->avg_weight / $maxAverage) * 100);
                $color = $barColors[$index % count($barColors)];
            @endphp

            <div class="chart-row">
                <span class="chart-label">{{ $breed->breed_name }}</span>
                <span class="chart-track">
                    <span class="chart-bar" style="width: {{ $percent }}%; background: {{ $color }};"></span>
                </span>
                <span class="chart-value">{{ number_format((float) $breed->avg_weight, 2) }} KG</span>
            </div>
        @endforeach

        <div class="insight-box">
            <strong>Sales Weight Insight:</strong>
            This report ranks breeds by latest average weight. Higher average weights may indicate stronger sale readiness,
            stronger finishing performance, better feed conversion, or mature stock concentration. Breeds below the farm
            average should be reviewed against age, sex, health records, feed program, and recent weight-loss alerts before
            sales planning.
        </div>

        <table class="report">
            <thead>
                <tr>
                    <th width="5%">#</th>
                    <th width="20%">Breed</th>
                    <th width="13%">Category</th>
                    <th width="10%">Animals</th>
                    <th width="13%">Avg Weight</th>
                    <th width="13%">Min Weight</th>
                    <th width="13%">Max Weight</th>
                    <th width="13%">Sales Position</th>
                </tr>
            </thead>

            <tbody>
                @forelse ($breedAverages as $index => $breed)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td><strong>{{ $breed->breed_name }}</strong></td>
                        <td><span class="badge">{{ $breed->parent_category }}</span></td>
                        <td>{{ number_format($breed->animals_count) }}</td>
                        <td class="weight">{{ number_format((float) $breed->avg_weight, 2) }} KG</td>
                        <td class="muted">{{ number_format((float) $breed->min_weight, 2) }} KG</td>
                        <td class="muted">{{ number_format((float) $breed->max_weight, 2) }} KG</td>
                        <td>
                            @if ($index === 0)
                                <strong style="color: {{ $successColor }}">Top Performer</strong>
                            @elseif ((float) $breed->avg_weight >= $overallAverage)
                                <strong style="color: {{ $primaryColor }}">Above Average</strong>
                            @else
                                <span class="muted">Needs Review</span>
                            @endif
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="8">No breed weight data available.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

       <div class="section-block">
            <table class="signature-table">
                <tr>
                    <td style="width: 26%; padding-top: 16px; padding-right: 8px;">
                        <div class="signature-card">
                            <div class="signature-card-title">Prepared By</div>
                            <div class="signature-name">{{ $generatedBy->name }}</div>
                            <div class="signature-meta">{{ $generatedByRole }}</div>
                            <div class="signature-line"></div>
                            <div class="signature-footer">
                                Generated on {{ $eatNow->format('d M Y, H:i') }} EAT
                            </div>
                        </div>
                    </td>

                    <td style="width: 28%; padding-top: 16px; padding-right: 8px;">
                        <div class="signature-card signature-card-authorized">
                            <div class="signature-card-title">Authorized Signature</div>

                            <div class="signature-handwritten">
                                Digitally.Approved!
                            </div>

                            <div class="signature-meta">
                                Signature Date: {{ $eatNow->format('d M Y, H:i') }} EAT
                            </div>

                            <div class="signature-line"></div>

                            <div class="signature-footer">
                                {{ $farmName }} Management Approval
                            </div>
                        </div>
                    </td>

                    <td style="width: 22%; padding-top: 16px; padding-right: 8px;">
                        <div class="stamp-wrap">
                            <!--<div class="info-card-title">Official Stamp</div>-->

                            <div class="stamp-circle">
                                <div class="stamp-text">OFFICIAL<br>STAMP</div>
                            </div>

                            <div class="stamp-caption">{{ $farmName }} Stamp</div>
                        </div>
                    </td>

                    <td style="width: 24%; padding-top: 16px;">
                        <div class=" qr-box">
                            <!--<div class="info-card-title">Verification QR</div>-->

                            @if (!empty($qrImage))
                                <div class="qr-image-wrap">
                                    <img src="{{ $qrImage }}" alt="QR Code" class="qr-image">
                                </div>
                            @else
                                <div class="qr-fallback">
                                    <span>QR not available</span>
                                </div>
                            @endif

                            <div class="qr-caption">
                                Scan to verify report metadata
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </main>

    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
                $font = $fontMetrics->getFont('Helvetica', 'normal');
                $size = 9;

                $text = "Page {$pageNumber} of {$pageCount}";
                $width = $fontMetrics->getTextWidth($text, $font, $size);

                $x = 420 - ($width / 2);
                $y = 565;

                $canvas->text($x, $y, $text, $font, $size, [0.42, 0.45, 0.50]);
            });
        }
    </script>
</body>
</html>
