@php

    $startDate = $payroll->week_start ? \Carbon\Carbon::parse($payroll->week_start) : now();

    $dayLabels = [];

    for ($i = 0; $i < 7; $i++) {
        $dayLabels[] = $startDate->copy()->addDays($i);
    }

    if (!function_exists('pdfImageBase64')) {
        function pdfImageBase64(?string $path): ?string
        {
            if (!$path) {
                return null;
            }

            $cleanPath = trim($path);
            $cleanPath = ltrim($cleanPath, '/');

            // Handles values saved as: storage/logos/logo.png
            $cleanPath = preg_replace('#^storage/#', '', $cleanPath);

            $possiblePaths = [
                storage_path('app/public/' . $cleanPath),
                public_path('storage/' . $cleanPath),
                public_path($cleanPath),
            ];

            foreach ($possiblePaths as $fullPath) {
                if (is_file($fullPath)) {
                    $extension = strtolower(pathinfo($fullPath, PATHINFO_EXTENSION));

                    $mime = match ($extension) {
                        'jpg', 'jpeg' => 'image/jpeg',
                        'png' => 'image/png',
                        'gif' => 'image/gif',
                        'webp' => 'image/webp',
                        'svg' => 'image/svg+xml',
                        'ico' => 'image/x-icon',
                        default => 'image/png',
                    };

                    return 'data:' . $mime . ';base64,' . base64_encode(file_get_contents($fullPath));
                }
            }

            return null;
        }
    }

    $eatNow = now('Africa/Nairobi');

    $farmName = setting('farm.name', $farmName ?? 'Lelekwe Farm Limited');
    $farmTagline = setting('farm.tagline', 'Nurturing Nature, Feeding The Future');
    $farmPhone = setting('farm.phone', '+254 743 487 186');
    $farmEmail = setting('farm.email', 'jambo@lelekwefarms.co.ke');
    $farmCounty = setting('farm.county', 'Ravine, Kambi Moto');

    $primaryColor = trim(setting('theme.primary', '#014a12'));
    $secondaryColor = trim(setting('theme.secondary', '#14532d'));
    $accentColor = trim(setting('theme.accent', '#f59e0b'));
    $dangerColor = trim(setting('theme.danger', '#dc2626'));
    $successColor = trim(setting('theme.success', '#16a34a'));

    $logoBase64 = pdfImageBase64(setting('branding.logo_light'));

    $generatedByName = $generatedBy?->name ?? 'System';
    $generatedByRole = $generatedBy?->getRoleNames()?->first() ?? 'User';

    $periodText =
        optional($payroll->week_start)->format('d M Y') . ' to ' . optional($payroll->week_end)->format('d M Y');

    $verificationText =
        $verificationText ??
        $farmName .
            ' Casual Payroll Report | Payroll ID: ' .
            $payroll->id .
            ' | Period: ' .
            optional($payroll->week_start)->format('Y-m-d') .
            ' to ' .
            optional($payroll->week_end)->format('Y-m-d') .
            ' | Total Casuals: ' .
            $payroll->total_casuals .
            ' | Total Amount: KES ' .
            number_format((float) $payroll->total_amount, 2) .
            ' | Generated by: ' .
            $generatedByName .
            ' (' .
            $generatedByRole .
            ')' .
            ' | Date: ' .
            $eatNow->format('Y-m-d H:i:s') .
            ' EAT';

    $qrPng = null;

    if (!empty($qrImage)) {
        $qrPng = str_replace('data:image/png;base64,', '', $qrImage);
    } elseif (class_exists(\SimpleSoftwareIO\QrCode\Facades\QrCode::class)) {
        try {
            $qrPng = base64_encode(
                \SimpleSoftwareIO\QrCode\Facades\QrCode::format('png')
                    ->size(110)
                    ->margin(1)
                    ->generate($verificationText),
            );
        } catch (\Throwable $e) {
            $qrPng = null;
        }
    }

    $items = $payroll->items ?? collect();

    $satTotal = $items->sum('saturday_amount');
    $sunTotal = $items->sum('sunday_amount');
    $monTotal = $items->sum('monday_amount');
    $tueTotal = $items->sum('tuesday_amount');
    $wedTotal = $items->sum('wednesday_amount');
    $thuTotal = $items->sum('thursday_amount');
    $friTotal = $items->sum('friday_amount');
@endphp

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Casual Payroll Report</title>

    <style>
        @font-face {
            font-family: "ChopinScript";
            src: url("{{ public_path('fonts/ChopinScript.ttf') }}") format("truetype");
            font-weight: normal;
            font-style: normal;
        }

        @page {
            margin: 120px 35px 95px 35px;
        }

        body {
            font-family: "Courier New", Courier, monospace;
            font-size: 10px;
            color: #222;
            position: relative;
        }

        .watermark {
            position: fixed;
            top: 30%;
            left: 12%;
            width: 75%;
            opacity: 0.06;
            z-index: -1;
            text-align: center;
        }

        .watermark img {
            width: 420px;
        }

        header {
            position: fixed;
            top: -95px;
            left: 0;
            right: 0;
            height: 90px;
            border-bottom: 2px solid {{ $primaryColor }};
        }

        .header-table {
            width: 100%;
            border-collapse: collapse;
        }

        .header-table td {
            vertical-align: middle;
        }

        .header-left {
            text-align: left;
        }

        .header-center {
            text-align: center;
        }

        .header-right {
            text-align: right;
            font-size: 10px;
            line-height: 1.5;
            color: #374151;
        }

        .logo {
            width: 180px;
            max-height: 75px;
            object-fit: contain;
        }

        .company-title {
            font-size: 22px;
            font-weight: 700;
            color: {{ $primaryColor }};
            margin-bottom: 2px;
            text-align: center;
        }

        .tagline {
            font-size: 11px;
            color: #4b5563;
            font-style: italic;
            text-align: center;
        }

        .report-title {
            margin-top: 5px;
            margin-bottom: 12px;
        }

        .report-title h1 {
            font-size: 18px;
            margin: 0 0 4px 0;
            color: #111827;
        }

        .report-title p {
            margin: 0;
            color: {{ $primaryColor }};
            font-size: 10px;
        }

        .summary-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 12px;
        }

        .summary-table td {
            border: 1px solid #d1d5db;
            padding: 7px;
            vertical-align: top;
        }

        .summary-label {
            background: #f3f4f6;
            font-weight: bold;
            color: #111827;
        }

        .summary-value {
            font-weight: bold;
            color: {{ $primaryColor }};
        }

        table.report {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }

        table.report thead th {
            background: {{ $primaryColor }};
            border: 1px solid {{ $primaryColor }};
            color: #fff;
            padding: 7px 5px;
            font-size: 8.5px;
            text-align: left;
        }

        table.report tbody td {
            border: 1px solid #e5e7eb;
            padding: 6px 5px;
            vertical-align: top;
            font-size: 8.5px;
        }

        table.report tbody tr:nth-child(even) {
            background: #fafafa;
        }

        .text-right {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }

        .money {
            font-weight: bold;
            white-space: nowrap;
        }

        .badge {
            display: inline-block;
            padding: 3px 7px;
            border-radius: 999px;
            font-size: 8px;
            font-weight: bold;
            color: #fff;
            background: {{ $secondaryColor }};
        }

        .worked {
            color: {{ $successColor }};
            font-weight: bold;
            text-align: center;
        }

        .not-worked {
            color: #9ca3af;
            text-align: center;
        }

        .total-row {
            background: #dcfce7;
            font-weight: bold;
        }

        .total-row td {
            border-top: 2px solid {{ $primaryColor }} !important;
        }

        .section-block {
            margin-top: 24px;
        }

        .signature-table {
            width: 100%;
            border-collapse: collapse;
        }

        .signature-table td {
            vertical-align: top;
        }

        .signature-card {
            border: 1px solid #dbe4d3;
            border-radius: 10px;
            padding: 12px 14px;
            background: #fbfdf9;
            min-height: 120px;
        }

        .signature-card-authorized {
            border: 1px solid #cfe3bf;
            background: #f8fff2;
        }

        .signature-card-title {
            font-size: 11px;
            font-weight: bold;
            color: {{ $secondaryColor }};
            margin-bottom: 10px;
            text-transform: uppercase;
            letter-spacing: 0.4px;
        }

        .signature-name {
            font-size: 13px;
            font-weight: bold;
            color: #111827;
            margin-bottom: 4px;
        }

        .signature-meta {
            font-size: 9px;
            color: #6b7280;
            margin-bottom: 12px;
        }

        .signature-line {
            border-top: 1px solid #4b5563;
            margin-top: 18px;
            padding-top: 6px;
        }

        .signature-footer {
            font-size: 9px;
            color: #6b7280;
            margin-top: 4px;
        }

        .signature-handwritten {
            font-family: "ChopinScript", "Courier New", Courier, monospace !important;
            font-size: 25px;
            color: {{ $successColor }};
            letter-spacing: 1px;
        }

        .stamp-wrap {
            padding-top: 4px;
            text-align: center;
        }

        .stamp-circle {
            width: 110px;
            height: 110px;
            margin: 0 auto 8px auto;
            border: 1px dashed {{ $primaryColor }};
            border-radius: 50%;
            display: table;
        }

        .stamp-text {
            display: table-cell;
            vertical-align: middle;
            text-align: center;
            font-size: 12px;
            font-weight: bold;
            color: {{ $primaryColor }};
            line-height: 1.4;
        }

        .stamp-caption {
            font-size: 9px;
            color: #6b7280;
            text-align: center;
        }

        .qr-box {
            text-align: center;
        }

        .qr-image-wrap {
            width: 104px;
            height: 104px;
            margin: 4px auto 8px auto;
            padding: 4px;
            border: 2px solid {{ $primaryColor }};
            background: #fff;
            border-radius: 8px;
        }

        .qr-image {
            width: 90px;
            height: 90px;
            display: block;
            margin: 0 auto;
        }

        .qr-caption {
            font-size: 8px;
            color: #6b7280;
            margin-top: 6px;
            line-height: 1.4;
        }

        .qr-fallback {
            width: 104px;
            height: 104px;
            margin: 4px auto 8px auto;
            border: 1px solid #999;
            border-radius: 8px;
            font-size: 9px;
            display: table;
            background: #fff;
        }

        .qr-fallback span {
            display: table-cell;
            vertical-align: middle;
            text-align: center;
        }

        footer {
            position: fixed;
            bottom: -72px;
            left: 0;
            right: 0;
            height: 62px;
            border-top: 1px solid #d1d5db;
            font-size: 10px;
            color: #4b5563;
        }

        .footer-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }

        .footer-left {
            text-align: left;
            width: 33%;
        }

        .footer-center {
            text-align: center;
            width: 34%;
        }

        .footer-right {
            text-align: right;
            width: 33%;
        }

        .small-muted {
            color: #6b7280;
            font-size: 9px;
        }
    </style>
</head>

<body>
    <div class="watermark">
        @if ($logoBase64)
            <img src="{{ $logoBase64 }}" alt="Watermark">
        @endif
    </div>

    <header>
        <table class="header-table">
            <tr>
                <td class="header-left" width="110">
                    @if ($logoBase64)
                        <img src="{{ $logoBase64 }}" class="logo" alt="Logo">
                    @endif
                </td>

                <td class="header-center">
                    <div class="company-title">{{ $farmName }}</div>
                    <div class="tagline">{{ $farmTagline }}</div>
                </td>

                <td class="header-right" width="230">
                    <strong>Phone:</strong> {{ $farmPhone }}<br>
                    <strong>Email:</strong> {{ $farmEmail }}<br>
                    <strong>County:</strong> {{ $farmCounty }}
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table class="footer-table">
            <tr>
                <td class="footer-left">
                    Printed on {{ $eatNow->format('d M Y, H:i') }} EAT
                </td>

                <td class="footer-center">
                    Casual Payroll Report
                </td>

                <td class="footer-right">
                    Created by {{ $generatedByName }} ({{ $generatedByRole }})
                </td>
            </tr>

            <tr>
                <td colspan="3" class="footer-center small-muted">
                    {{ $farmName }} • {{ $farmCounty }} • {{ $farmPhone }} • {{ $farmEmail }}
                </td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="report-title">
            <h1>Casual Payroll Report</h1>
            <p>
                Period: {{ $periodText }}
                |
                Work Site: {{ $payroll->work_site ?? 'All Sites' }}
            </p>
        </div>

        <table class="summary-table">
            <tr>
                <td class="summary-label">Payroll Title</td>
                <td class="summary-value">{{ $payroll->title ?? 'Casual Payroll' }}</td>

                <td class="summary-label">Week Start</td>
                <td>{{ optional($payroll->week_start)->format('d M Y') }}</td>

                <td class="summary-label">Week End</td>
                <td>{{ optional($payroll->week_end)->format('d M Y') }}</td>
            </tr>

            <tr>
                <td class="summary-label">Total Casuals</td>
                <td class="summary-value">{{ number_format((float) $payroll->total_casuals) }}</td>

                <td class="summary-label">Total Days Worked</td>
                <td class="summary-value">{{ number_format((float) $payroll->total_days_worked, 2) }}</td>

                <td class="summary-label">Total Amount Paid</td>
                <td class="summary-value">KES {{ number_format((float) $payroll->total_amount, 2) }}</td>
            </tr>

            <tr>
                <td class="summary-label">Uploaded By</td>
                <td>{{ $payroll->uploader?->name ?? $generatedByName }}</td>

                <td class="summary-label">Generated By</td>
                <td>{{ $generatedByName }}</td>

                <td class="summary-label">Generated At</td>
                <td>{{ $eatNow->format('d M Y, H:i') }} EAT</td>
            </tr>
        </table>

        <table class="report">
            <thead>
                <tr>
                    <th width="3%">#</th>
                    <th width="13%">Name</th>
                    <th width="8%">ID No.</th>
                    <th width="9%">Phone</th>
                    <th width="10%">Designation</th>
                    <th width="8%">Site</th>
                    <th width="8%">Rate</th>

                    @foreach ($dayLabels as $day)
                        <th width="4%">
                            {{ $day->format('D') }}<br>
                            {{ $day->format('d/m') }}
                        </th>
                    @endforeach
                    <th width="5%">Days</th>
                    <th width="9%">Total</th>
                    <th width="6%">Sign</th>
                </tr>
            </thead>

            <tbody>
                @forelse ($items as $item)
                    <tr>
                        <td class="text-center">{{ $loop->iteration }}</td>
                        <td><strong>{{ $item->casual_name }}</strong></td>
                        <td>{{ $item->id_number ?? '-' }}</td>
                        <td>{{ $item->phone_number ?? '-' }}</td>
                        <td>{{ $item->designation ?? '-' }}</td>
                        <td>{{ $item->work_site ?? '-' }}</td>

                        <td class="text-right money">
                            {{ number_format((float) ($item->daily_rate ?? 0), 2) }}
                        </td>

                        <td class="{{ (float) $item->saturday_amount > 0 ? 'worked' : 'not-worked' }}">
    {{ (float) $item->saturday_amount > 0 ? 'P' : '-' }}
</td>

<td class="{{ (float) $item->sunday_amount > 0 ? 'worked' : 'not-worked' }}">
    {{ (float) $item->sunday_amount > 0 ? 'P' : '-' }}
</td>

<td class="{{ (float) $item->monday_amount > 0 ? 'worked' : 'not-worked' }}">
    {{ (float) $item->monday_amount > 0 ? 'P' : '-' }}
</td>

<td class="{{ (float) $item->tuesday_amount > 0 ? 'worked' : 'not-worked' }}">
    {{ (float) $item->tuesday_amount > 0 ? 'P' : '-' }}
</td>

<td class="{{ (float) $item->wednesday_amount > 0 ? 'worked' : 'not-worked' }}">
    {{ (float) $item->wednesday_amount > 0 ? 'P' : '-' }}
</td>

<td class="{{ (float) $item->thursday_amount > 0 ? 'worked' : 'not-worked' }}">
    {{ (float) $item->thursday_amount > 0 ? 'P' : '-' }}
</td>

<td class="{{ (float) $item->friday_amount > 0 ? 'worked' : 'not-worked' }}">
    {{ (float) $item->friday_amount > 0 ? 'P' : '-' }}
</td>

                        <td class="text-center">
                            {{ number_format((float) $item->days_worked, 2) }}
                        </td>

                        <td class="text-right money">
                            KES {{ number_format((float) $item->total_pay, 2) }}
                        </td>

                        <td>{{ $item->signature ?? '' }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="17" class="text-center">
                            No casual payroll items found.
                        </td>
                    </tr>
                @endforelse

                <tr class="total-row">
                    <td colspan="7">TOTALS</td>
                    <td class="text-right">{{ number_format((float) $satTotal, 2) }}</td>
                    <td class="text-right">{{ number_format((float) $sunTotal, 2) }}</td>
                    <td class="text-right">{{ number_format((float) $monTotal, 2) }}</td>
                    <td class="text-right">{{ number_format((float) $tueTotal, 2) }}</td>
                    <td class="text-right">{{ number_format((float) $wedTotal, 2) }}</td>
                    <td class="text-right">{{ number_format((float) $thuTotal, 2) }}</td>
                    <td class="text-right">{{ number_format((float) $friTotal, 2) }}</td>
                    <td class="text-center">{{ number_format((float) $payroll->total_days_worked, 2) }}</td>
                    <td class="text-right">KES {{ number_format((float) $payroll->total_amount, 2) }}</td>
                    <td></td>
                </tr>
            </tbody>
        </table>

        @if ($payroll->notes)
            <div class="section-block">
                <table class="summary-table">
                    <tr>
                        <td class="summary-label" width="18%">Notes</td>
                        <td>{{ $payroll->notes }}</td>
                    </tr>
                </table>
            </div>
        @endif

        <div class="section-block">
            <table class="signature-table">
                <tr>
                    <td style="width: 26%; padding-top: 16px; padding-right: 8px;">
                        <div class="signature-card">
                            <div class="signature-card-title">Prepared By</div>
                            <div class="signature-name">{{ $generatedByName }}</div>
                            <div class="signature-meta">{{ $generatedByRole }}</div>
                            <div class="signature-line"></div>
                            <div class="signature-footer">
                                Generated on {{ $eatNow->format('d M Y, H:i') }} EAT
                            </div>
                        </div>
                    </td>

                    <td style="width: 28%; padding-top: 16px; padding-right: 8px;">
                        <div class="signature-card signature-card-authorized">
                            <div class="signature-card-title">Authorized Signature</div>

                            <div class="signature-handwritten">
                                Digitally Approved!
                            </div>

                            <div class="signature-meta">
                                Signature Date: {{ $eatNow->format('d M Y, H:i') }} EAT
                            </div>

                            <div class="signature-line"></div>

                            <div class="signature-footer">
                                {{ $farmName }} Management Approval
                            </div>
                        </div>
                    </td>

                    <td style="width: 22%; padding-top: 16px; padding-right: 8px;">
                        <div class="stamp-wrap">
                            <div class="stamp-circle">
                                <div class="stamp-text">OFFICIAL<br>STAMP</div>
                            </div>

                            <div class="stamp-caption">{{ $farmName }} Stamp</div>
                        </div>
                    </td>

                    <td style="width: 24%; padding-top: 16px;">
                        <div class="qr-box">
                            @if (!empty($qrPng))
                                <div class="qr-image-wrap">
                                    <img src="data:image/png;base64,{{ $qrPng }}" alt="QR Code"
                                        class="qr-image">
                                </div>
                            @else
                                <div class="qr-fallback">
                                    <span>QR not available</span>
                                </div>
                            @endif

                            <div class="qr-caption">
                                Scan to verify payroll report metadata
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </main>

    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
                $font = $fontMetrics->getFont('Helvetica', 'normal');
                $size = 9;

                $text = "Page {$pageNumber} of {$pageCount}";
                $width = $fontMetrics->getTextWidth($text, $font, $size);

                $x = 420 - ($width / 2);
                $y = 565;

                $canvas->text($x, $y, $text, $font, $size, [0.42, 0.45, 0.50]);
            });
        }
    </script>
</body>

</html>
