<x-filament-panels::page>
    @php
        $primary=setting('theme.primary','#14532d');$secondary=setting('theme.secondary','#166534');$accent=setting('theme.accent','#b7791f');
        $summary=$this->summary;$output=(float)$summary->where('direction','output')->sum('tax_amount');$input=(float)$summary->where('direction','input')->sum('tax_amount');$withheld=(float)$summary->where('direction','withheld')->sum('tax_amount');
    @endphp
    <style>
        .ktc{--p:{{ $primary }};--s:{{ $secondary }};--a:{{ $accent }};display:grid;gap:1rem;color:#0f172a}.dark .ktc{color:#f8fafc}.ktc-hero{padding:1.2rem;border-radius:1rem;color:#fff;background:linear-gradient(125deg,var(--p),var(--s))}.ktc-hero h2{font-size:clamp(1.35rem,2vw,2rem);font-weight:950}.ktc-hero p{margin-top:.35rem;max-width:850px;color:rgba(255,255,255,.82);font-size:.76rem;line-height:1.5}.ktc-filter,.ktc-card,.ktc-panel{border:1px solid #dbe4df;border-radius:.9rem;background:#fff}.dark .ktc-filter,.dark .ktc-card,.dark .ktc-panel{border-color:#334155;background:#0f172a}.ktc-filter{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.7rem;padding:.85rem}.ktc-filter label{font-size:.65rem;font-weight:900}.ktc-filter input{display:block;width:100%;margin-top:.25rem;border:1px solid #cbd5e1;border-radius:.55rem;padding:.55rem;background:transparent}.ktc-kpis{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.7rem}.ktc-card{padding:.9rem;border-left:4px solid var(--tone,var(--p))}.ktc-card small{color:#64748b;font-weight:900;text-transform:uppercase}.dark .ktc-card small{color:#94a3b8}.ktc-card strong{display:block;margin-top:.35rem;font-size:1.25rem;font-weight:950}.ktc-panel{overflow:hidden}.ktc-title{padding:.75rem .85rem;font-weight:950;border-bottom:1px solid #e2e8f0}.dark .ktc-title{border-color:#334155}.ktc-wrap{overflow-x:auto}.ktc-table{width:100%;min-width:780px;border-collapse:collapse}.ktc-table th,.ktc-table td{padding:.68rem;border-bottom:1px solid #e2e8f0;font-size:.71rem;text-align:left}.dark .ktc-table th,.dark .ktc-table td{border-color:#334155}.ktc-table th{background:#f8fafc;font-size:.61rem;text-transform:uppercase}.dark .ktc-table th{background:#111827}.ktc-note{padding:.8rem;border:1px solid #f59e0b;border-radius:.8rem;background:#fffbeb;color:#92400e;font-size:.7rem;line-height:1.45}.dark .ktc-note{background:#451a03;color:#fde68a}@media(min-width:1100px){.ktc-kpis{grid-template-columns:repeat(4,minmax(0,1fr))}.ktc-filter{grid-template-columns:repeat(4,minmax(0,1fr))}}@media(max-width:480px){.ktc-filter{grid-template-columns:1fr}.ktc{gap:.7rem}.ktc-card strong{font-size:1.05rem}}
    </style>
    <div class="ktc">
        <section class="ktc-hero"><h2>Kenya Tax Compliance Dashboard</h2><p>Review VAT, withholding tax, withholding VAT, eTIMS evidence, due dates and remittance status from the accounting tax register.</p></section>
        <div class="ktc-note"><strong>Control notice:</strong> rates are configurable and must be reviewed against the latest KRA notices and your tax adviser. Withholding VAT should only be activated when the business is an appointed withholding agent.</div>
        <section class="ktc-filter"><label>From<input type="date" wire:model.live="from"></label><label>To<input type="date" wire:model.live="to"></label></section>
        <section class="ktc-kpis"><div class="ktc-card" style="--tone:#dc2626"><small>Output Tax</small><strong>KES {{ number_format($output,2) }}</strong></div><div class="ktc-card" style="--tone:#2563eb"><small>Input Tax</small><strong>KES {{ number_format($input,2) }}</strong></div><div class="ktc-card" style="--tone:var(--a)"><small>Tax Withheld</small><strong>KES {{ number_format($withheld,2) }}</strong></div><div class="ktc-card" style="--tone:{{ $this->overdue->count() ? '#dc2626' : '#15803d' }}"><small>Overdue Items</small><strong>{{ number_format($this->overdue->count()) }}</strong></div></section>
        <section class="ktc-panel"><div class="ktc-title">Tax Summary</div><div class="ktc-wrap"><table class="ktc-table"><thead><tr><th>Tax Code</th><th>Direction</th><th>Transactions</th><th>Taxable Amount</th><th>Tax Amount</th><th>Gross Amount</th></tr></thead><tbody>@forelse($summary as $row)<tr><td>{{ $row->tax_code }}</td><td>{{ str($row->direction)->headline() }}</td><td>{{ number_format($row->transaction_count) }}</td><td>KES {{ number_format($row->taxable_amount,2) }}</td><td>KES {{ number_format($row->tax_amount,2) }}</td><td>KES {{ number_format($row->gross_amount,2) }}</td></tr>@empty<tr><td colspan="6">No tax transactions for the period.</td></tr>@endforelse</tbody></table></div></section>
        <section class="ktc-panel"><div class="ktc-title">Overdue Compliance Items</div><div class="ktc-wrap"><table class="ktc-table"><thead><tr><th>Due Date</th><th>Tax No.</th><th>Tax Code</th><th>Party</th><th>Amount</th><th>Status</th></tr></thead><tbody>@forelse($this->overdue as $row)<tr><td>{{ $row->due_date?->format('d M Y') }}</td><td>{{ $row->tax_number }}</td><td>{{ $row->tax_code }}</td><td>{{ $row->party_name ?: '-' }}</td><td>KES {{ number_format($row->tax_amount,2) }}</td><td>{{ str($row->status)->headline() }}</td></tr>@empty<tr><td colspan="6">No overdue compliance items.</td></tr>@endforelse</tbody></table></div></section>
    </div>
</x-filament-panels::page>
