<?php

namespace App\Services;

use App\Models\Animal;
use App\Models\Breed;
use App\Models\BreedingRecord;
use App\Models\Location;
use Carbon\Carbon;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

class BreedingDeliveryService
{
    /**
     * Register every not-yet-created live offspring from a completed delivery.
     *
     * Tags are generated by the existing AnimalTagGeneratorService. Sire, dam,
     * location and purity are never entered manually here.
     *
     * @param  array<int, array<string, mixed>>  $offspringRows
     * @return Collection<int, Animal>
     */
    public function registerLiveOffspring(
        BreedingRecord $breedingRecord,
        array $offspringRows
    ): Collection {
        return DB::transaction(function () use ($breedingRecord, $offspringRows): Collection {
            /** @var BreedingRecord $record */
            $record = BreedingRecord::query()
                ->with([
                    'male.breed',
                    'male.location',
                    'female.breed',
                    'female.location',
                    'batch',
                ])
                ->lockForUpdate()
                ->findOrFail($breedingRecord->getKey());

            if ($record->pregnancy_status !== 'delivered') {
                if ($offspringRows !== []) {
                    throw ValidationException::withMessages([
                        'new_offspring' => 'Offspring can only be registered when pregnancy status is Delivered.',
                    ]);
                }

                return collect();
            }

            // Server-side protection. This is repeated here deliberately so
            // no alternate caller can bypass the minimum gestation rule.
            $record->assertDeliveryDateMeetsGestation();

            $sire = $record->male;
            $dam = $record->female;

            if (! $sire || $sire->sex !== 'Male') {
                throw ValidationException::withMessages([
                    'male_animal_id' => 'The assigned sire is missing or is not registered as Male.',
                ]);
            }

            if (! $dam || $dam->sex !== 'Female') {
                throw ValidationException::withMessages([
                    'female_animal_id' => 'The assigned dam is missing or is not registered as Female.',
                ]);
            }

            $liveBirthCount = max(0, (int) ($record->live_birth_count ?? 0));

            $existingOffspringCount = Animal::query()
                ->where('source_reference_type', BreedingRecord::class)
                ->where('source_reference_id', $record->getKey())
                ->count();

            if ($existingOffspringCount > $liveBirthCount) {
                throw ValidationException::withMessages([
                    'live_birth_count' => "{$existingOffspringCount} offspring are already registered. Live births cannot be reduced below this number.",
                ]);
            }

            $rows = collect($offspringRows)
                ->filter(fn (mixed $row): bool => is_array($row))
                ->map(function (array $row): array {
                    $row['creation_token'] = filled($row['creation_token'] ?? null)
                        ? (string) $row['creation_token']
                        : (string) Str::uuid();

                    return $row;
                })
                ->unique('creation_token')
                ->values();

            $rowsToCreate = $rows
                ->reject(fn (array $row): bool => $this->creationTokenExists(
                    recordId: (int) $record->getKey(),
                    token: (string) $row['creation_token'],
                ))
                ->values();

            $requiredNewOffspring = $liveBirthCount - $existingOffspringCount;

            if ($rowsToCreate->count() !== $requiredNewOffspring) {
                throw ValidationException::withMessages([
                    'new_offspring' => "This delivery records {$liveBirthCount} live birth(s), of which {$existingOffspringCount} are already registered. Add exactly {$requiredNewOffspring} new offspring row(s).",
                ]);
            }

            if ($requiredNewOffspring === 0) {
                return collect();
            }

            $birthDate = Carbon::parse($record->delivery_date)->startOfDay();
            $species = $record->species
                ?: $dam->species
                ?: $dam->breed?->parent_category
                ?: $sire->species
                ?: $sire->breed?->parent_category;

            $defaultLocationId = $dam->current_location_id
                ?: $sire->current_location_id
                ?: Location::query()->active()->defaultFirst()->value('id');

            if (! $defaultLocationId) {
                throw ValidationException::withMessages([
                    'new_offspring' => 'No valid offspring location is available. Assign the dam to a location or create an active default location.',
                ]);
            }

            $animalColumns = array_flip(Schema::getColumnListing('animals'));
            $createdAnimals = collect();

            foreach ($rowsToCreate as $index => $row) {
                $rowNumber = $index + 1;

                /*
                 * Offspring always retain the dam's registered breed.
                 * The posted repeater value is intentionally ignored so the
                 * breed cannot be cleared or changed from the browser.
                 */
                $breedId = (int) $dam->breed_id;

                /** @var Breed|null $breed */
                $breed = Breed::query()
                    ->whereKey($breedId)
                    ->where('is_active', true)
                    ->first();

                if (! $breed) {
                    throw ValidationException::withMessages([
                        "new_offspring.{$index}.breed_id" =>
                            'The dam does not have a valid active breed. '
                            . 'Correct the dam record before confirming delivery.',
                    ]);
                }

                if (
                    filled($species)
                    && strcasecmp(trim((string) $breed->parent_category), trim((string) $species)) !== 0
                ) {
                    throw ValidationException::withMessages([
                        "new_offspring.{$index}.breed_id" => "The selected breed for offspring {$rowNumber} must belong to {$species}.",
                    ]);
                }

                $sex = ucfirst(strtolower(trim((string) ($row['sex'] ?? ''))));

                if (! in_array($sex, ['Male', 'Female'], true)) {
                    throw ValidationException::withMessages([
                        "new_offspring.{$index}.sex" => "Select Male or Female for offspring {$rowNumber}.",
                    ]);
                }

                $locationId = filled($row['current_location_id'] ?? null)
                    ? (int) $row['current_location_id']
                    : (int) $defaultLocationId;

                if (! Location::query()->whereKey($locationId)->exists()) {
                    throw ValidationException::withMessages([
                        "new_offspring.{$index}.current_location_id" => "Select a valid location for offspring {$rowNumber}.",
                    ]);
                }

                $purpose = filled($row['purpose'] ?? null)
                    ? (string) $row['purpose']
                    : 'Production';

                if (! in_array($purpose, ['Breeding', 'Sale', 'Dairy', 'Production'], true)) {
                    throw ValidationException::withMessages([
                        "new_offspring.{$index}.purpose" => "The initial purpose for offspring {$rowNumber} is invalid.",
                    ]);
                }

                $tagData = app(AnimalTagGeneratorService::class)
                    ->generateForBreedAndBirthDate($breed, $birthDate);

                $token = (string) $row['creation_token'];
                $marker = $this->creationMarker((int) $record->getKey(), $token);
                $userNotes = trim((string) ($row['notes'] ?? ''));

                $attributes = [
                    'tag_number' => $tagData['tag_number'],
                    'tag_sequence' => $tagData['tag_sequence'],
                    'species' => $breed->parent_category,
                    'breed_id' => $breed->id,
                    'sex' => $sex,
                    // Birth date is intentionally forced to the confirmed
                    // delivery date so the tag year cannot be manipulated.
                    'date_of_birth' => $birthDate->toDateString(),
                    'date_of_birth_is_estimated' => false,
                    'source' => 'Born on farm',
                    'source_reference_type' => BreedingRecord::class,
                    'source_reference_id' => $record->getKey(),
                    'status' => 'Active',
                    'is_archived' => false,
                    'purpose' => $purpose,
                    'is_breeder' => $purpose === 'Breeding',
                    'sale_ready' => false,
                    'valuation_price' => null,
                    'current_location_id' => $locationId,
                    'sire_id' => $sire->getKey(),
                    'dam_id' => $dam->getKey(),
                    'purity_breed_id' => $breed->id,
                    'breed_purity_percent' => null,
                    'purity_override_percent' => null,
                    'purity_status' => 'pending',
                    'is_foundation_animal' => false,
                    'purity_verified_at' => null,
                    'purity_notes' => 'Automatically calculated from the registered sire and dam after delivery confirmation.',
                    'notes' => implode(' ', array_filter([
                        $marker,
                        'Born from breeding record #' . $record->getKey() . '.',
                        'Sire: ' . ($sire->tag_number ?? 'Unknown') . '.',
                        'Dam: ' . ($dam->tag_number ?? 'Unknown') . '.',
                        $userNotes,
                    ])),
                    'created_by' => auth()->id(),
                    'updated_by' => auth()->id(),
                ];

                // Keeps the patch compatible with installations where a few
                // optional purity columns have not yet been added.
                $attributes = array_intersect_key($attributes, $animalColumns);

                $animal = new Animal();
                $animal->forceFill($attributes);
                $animal->save();

                app(BreedPurityService::class)->recalculate($animal);

                $createdAnimals->push($animal->fresh([
                    'breed',
                    'location',
                    'sire',
                    'dam',
                ]));
            }

            return $createdAnimals;
        }, 5);
    }

    private function creationTokenExists(int $recordId, string $token): bool
    {
        return Animal::query()
            ->where('source_reference_type', BreedingRecord::class)
            ->where('source_reference_id', $recordId)
            ->where('notes', 'like', '%' . $this->creationMarker($recordId, $token) . '%')
            ->exists();
    }

    private function creationMarker(int $recordId, string $token): string
    {
        return '[BREEDING-OFFSPRING:' . $recordId . ':' . $token . ']';
    }
}
