@php
    if (! function_exists('pdfImageBase64')) {
        function pdfImageBase64(?string $path): ?string
        {
            if (! $path) return null;

            $cleanPath = trim($path);
            $cleanPath = ltrim($cleanPath, '/');
            $cleanPath = preg_replace('#^storage/#', '', $cleanPath);

            $possiblePaths = [
                storage_path('app/public/' . $cleanPath),
                public_path('storage/' . $cleanPath),
                public_path($cleanPath),
            ];

            foreach ($possiblePaths as $fullPath) {
                if (is_file($fullPath)) {
                    $extension = strtolower(pathinfo($fullPath, PATHINFO_EXTENSION));

                    $mime = match ($extension) {
                        'jpg', 'jpeg' => 'image/jpeg',
                        'png' => 'image/png',
                        'gif' => 'image/gif',
                        'webp' => 'image/webp',
                        'svg' => 'image/svg+xml',
                        default => 'image/png',
                    };

                    return 'data:' . $mime . ';base64,' . base64_encode(file_get_contents($fullPath));
                }
            }

            return null;
        }
    }

    $eatNow = now('Africa/Nairobi');

    $farmName = setting('farm.name', 'Lelekwe Farm Limited');
    $farmTagline = setting('farm.tagline', 'Nurturing Nature, Feeding The Future');
    $farmPhone = setting('farm.phone', '+254 743 487 186');
    $farmEmail = setting('farm.email', 'jambo@lelekwefarm.com');
    $farmCounty = setting('farm.county', 'Nakuru County');

    $primaryColor = trim(setting('theme.primary', '#014a12'));
    $secondaryColor = trim(setting('theme.secondary', '#14532d'));
    $accentColor = trim(setting('theme.accent', '#f59e0b'));
    $dangerColor = trim(setting('theme.danger', '#dc2626'));
    $successColor = trim(setting('theme.success', '#16a34a'));

    $logoBase64 = pdfImageBase64(setting('branding.logo_light'));

    $generatedByName = $generatedBy->name ?? 'System';
    $generatedByRole = $generatedByRole ?? 'User';

    $activeCount = $customers->where('is_active', true)->count();
    $inactiveCount = $customers->where('is_active', false)->count();
    $withPinCount = $customers->filter(fn ($c) => filled($c->kra_pin))->count();
    $countiesCount = $customers->pluck('county')->filter()->unique()->count();

    $verificationText = $farmName . ' Customers Report | Generated by: ' . $generatedByName . ' | Date: ' . $eatNow->format('Y-m-d H:i:s') . ' EAT | Records: ' . $customers->count();

    $qrPng = null;

    if (class_exists(\SimpleSoftwareIO\QrCode\Facades\QrCode::class)) {
        try {
            $qrPng = base64_encode(
                \SimpleSoftwareIO\QrCode\Facades\QrCode::format('png')
                    ->size(110)
                    ->margin(1)
                    ->generate($verificationText)
            );
        } catch (\Throwable $e) {
            $qrPng = null;
        }
    }
@endphp

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Customers Report</title>

    <style>
        @font-face {
            font-family: "ChopinScript";
            src: url("{{ public_path('fonts/ChopinScript.ttf') }}") format("truetype");
        }

        @page {
            size: A4 landscape;
            margin: 112px 28px 82px 28px;
        }

        body {
            font-family: Courier, sans-serif;
            font-size: 10.2px;
            color: #1f2937;
        }

        .watermark {
            position: fixed;
            top: 22%;
            left: 20%;
            width: 60%;
            opacity: 0.045;
            z-index: -1;
            text-align: center;
        }

        .watermark img {
            width: 430px;
        }

        header {
            position: fixed;
            top: -92px;
            left: 0;
            right: 0;
            height: 82px;
            border-bottom: 2px solid {{ $primaryColor }};
        }

        .header-table,
        .footer-table,
        .summary-table,
        .signature-table {
            width: 100%;
            border-collapse: collapse;
        }

        .header-table td {
            vertical-align: middle;
        }

        .logo {
            width: 170px;
            max-height: 70px;
            object-fit: contain;
        }

        .company-title {
            font-size: 23px;
            font-weight: bold;
            color: {{ $primaryColor }};
            text-align: center;
            margin-bottom: 3px;
        }

        .tagline {
            font-size: 10.5px;
            color: #4b5563;
            font-style: italic;
            text-align: center;
        }

        .header-right {
            text-align: right;
            font-size: 9.5px;
            line-height: 1.55;
            color: #374151;
        }

        footer {
            position: fixed;
            bottom: -58px;
            left: 0;
            right: 0;
            height: 50px;
            border-top: 1px solid #d1d5db;
            font-size: 9.5px;
            color: #4b5563;
        }

        .footer-table {
            margin-top: 7px;
        }

        .footer-left { text-align: left; width: 33%; }
        .footer-center { text-align: center; width: 34%; }
        .footer-right { text-align: right; width: 33%; }

        .report-title {
            margin-bottom: 10px;
        }

        .report-title h1 {
            font-size: 20px;
            margin: 0 0 4px 0;
            color: #111827;
        }

        .report-title p {
            margin: 0;
            color: {{ $primaryColor }};
            font-size: 10px;
        }

        .summary-table {
            border-collapse: separate;
            border-spacing: 7px 0;
            margin-bottom: 8px;
        }

        .summary-card {
            border: 1px solid #dbe4d3;
            border-left: 5px solid {{ $primaryColor }};
            background: #fbfdf9;
            padding: 10px 12px;
            border-radius: 10px;
        }

        .summary-label {
            font-size: 8.5px;
            color: #6b7280;
            text-transform: uppercase;
            letter-spacing: .4px;
            font-weight: bold;
        }

        .summary-value {
            font-size: 22px;
            font-weight: bold;
            color: {{ $primaryColor }};
            margin-top: 4px;
        }

        .summary-note {
            margin-top: 4px;
            font-size: 8.7px;
            color: #6b7280;
            line-height: 1.35;
        }

        .explanation-box {
            border: 1px solid #d1d5db;
            background: #f9fafb;
            padding: 9px 12px;
            margin: 8px 0 12px 0;
            font-size: 9.5px;
            line-height: 1.5;
            color: #374151;
        }

        table.report {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }

        table.report thead th {
            background: {{ $primaryColor }};
            border: 1px solid {{ $primaryColor }};
            color: #fff;
            padding: 8px 7px;
            font-size: 9.2px;
            text-align: left;
            white-space: nowrap;
        }

        table.report tbody td {
            border: 1px solid #e5e7eb;
            padding: 7px;
            vertical-align: top;
            word-break: break-word;
        }

        table.report tbody tr:nth-child(even) {
            background: #fafafa;
        }

        .badge {
            display: inline-block;
            padding: 3px 7px;
            border-radius: 999px;
            font-size: 8.5px;
            font-weight: bold;
            color: #fff;
            white-space: nowrap;
        }

        .badge-green { background: {{ $successColor }}; }
        .badge-red { background: {{ $dangerColor }}; }
        .badge-blue { background: {{ $secondaryColor }}; }
        .badge-gray { background: #6b7280; }

        .small-muted {
            font-size: 8.5px;
            color: #6b7280;
        }

        .section-block {
            margin-top: 25px;
        }

        .signature-table td {
            vertical-align: top;
        }

        .signature-card {
            border: 1px solid #dbe4d3;
            border-radius: 10px;
            padding: 10px 12px;
            background: #fbfdf9;
            min-height: 100px;
        }

        .signature-card-title {
            font-size: 10px;
            font-weight: bold;
            color: {{ $secondaryColor }};
            margin-bottom: 8px;
            text-transform: uppercase;
        }

        .signature-name {
            font-size: 12px;
            font-weight: bold;
            color: #111827;
            margin-bottom: 3px;
        }

        .signature-line {
            border-top: 1px solid #4b5563;
            margin-top: 15px;
            padding-top: 5px;
        }

        .signature-handwritten {
            font-family: "ChopinScript" !important;
            font-size: 23px;
            color: {{ $successColor }};
        }

        .stamp-circle {
            width: 96px;
            height: 96px;
            margin: 0 auto 7px auto;
            border: 1px dashed {{ $primaryColor }};
            border-radius: 50%;
            display: table;
        }

        .stamp-text {
            display: table-cell;
            vertical-align: middle;
            text-align: center;
            font-size: 11px;
            font-weight: bold;
            color: {{ $primaryColor }};
            line-height: 1.35;
        }

        .qr-box {
            text-align: center;
        }

        .qr-image-wrap,
        .qr-fallback {
            width: 92px;
            height: 92px;
            margin: 0 auto 6px auto;
            border: 2px solid {{ $primaryColor }};
            background: #fff;
            border-radius: 8px;
            padding: 4px;
        }

        .qr-image {
            width: 82px;
            height: 82px;
        }
    </style>
</head>

<body>
    <div class="watermark">
        @if ($logoBase64)
            <img src="{{ $logoBase64 }}" alt="Watermark">
        @endif
    </div>

    <header>
        <table class="header-table">
            <tr>
                <td width="180">
                    @if ($logoBase64)
                        <img src="{{ $logoBase64 }}" class="logo" alt="Logo">
                    @endif
                </td>
                <td>
                    <div class="company-title">{{ $farmName }}</div>
                    <div class="tagline">{{ $farmTagline }}</div>
                </td>
                <td class="header-right" width="240">
                    <strong>Phone:</strong> {{ $farmPhone }}<br>
                    <strong>Email:</strong> {{ $farmEmail }}<br>
                    <strong>County:</strong> {{ $farmCounty }}
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table class="footer-table">
            <tr>
                <td class="footer-left">Printed {{ $eatNow->format('d M Y, H:i') }} EAT</td>
                <td class="footer-center">Customers Report</td>
                <td class="footer-right">By {{ $generatedByName }} ({{ $generatedByRole }})</td>
            </tr>
            <tr>
                <td colspan="3" class="footer-center small-muted">
                    {{ $farmName }} • {{ $farmCounty }} • {{ $farmPhone }} • {{ $farmEmail }}
                </td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="report-title">
            <h1>Customers Report</h1>
            <p>Buyer register for invoices, payments, receipts, farm revenue analysis, and sales history.</p>
        </div>

        <table class="summary-table">
            <tr>
                <td class="summary-card">
                    <div class="summary-label">Selected Customers</div>
                    <div class="summary-value">{{ $customers->count() }}</div>
                    <div class="summary-note">Total buyers included in this report.</div>
                </td>
                <td class="summary-card">
                    <div class="summary-label">Active Buyers</div>
                    <div class="summary-value">{{ $activeCount }}</div>
                    <div class="summary-note">Available for new sales invoices.</div>
                </td>
                <td class="summary-card">
                    <div class="summary-label">With KRA PIN</div>
                    <div class="summary-value">{{ $withPinCount }}</div>
                    <div class="summary-note">Useful for tax-compliant invoices.</div>
                </td>
                <td class="summary-card">
                    <div class="summary-label">Counties Covered</div>
                    <div class="summary-value">{{ $countiesCount }}</div>
                    <div class="summary-note">Geographic spread of selected customers.</div>
                </td>
            </tr>
        </table>

        <div class="explanation-box">
            This report lists customers used across the Sales module. Accurate buyer records allow the farm to track
            repeat buyers, unpaid invoices, payment history, regional demand, tax details, and animal sales performance.
        </div>

        <table class="report">
            <thead>
                <tr>
                    <th width="4%">#</th>
                    <th width="10%">Customer No.</th>
                    <th width="16%">Name</th>
                    <th width="10%">Type</th>
                    <th width="11%">Phone</th>
                    <th width="13%">KRA PIN</th>
                    <th width="15%">Location</th>
                    <th width="8%">Active</th>
                    <th width="13%">Created By</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($customers as $index => $customer)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $customer->customer_number ?? '-' }}</td>
                        <td>
                            <strong>{{ $customer->name ?? '-' }}</strong><br>
                            <span class="small-muted">{{ $customer->email ?: '-' }}</span>
                        </td>
                        <td>
                            <span class="badge badge-blue">
                                {{ $customer->customer_type_label ?? '-' }}
                            </span>
                        </td>
                        <td>{{ $customer->phone ?: '-' }}</td>
                        <td>{{ $customer->kra_pin ?: '-' }}</td>
                        <td>
                            {{ $customer->town ?: '-' }}<br>
                            <span class="small-muted">{{ $customer->county ?: $customer->country }}</span>
                        </td>
                        <td>
                            @if ($customer->is_active)
                                <span class="badge badge-green">Yes</span>
                            @else
                                <span class="badge badge-red">No</span>
                            @endif
                        </td>
                        <td>
                            <strong>{{ $customer->createdBy?->name ?? 'System' }}</strong><br>
                            <span class="small-muted">{{ optional($customer->created_at)->format('d M Y') }}</span>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="section-block">
            <table class="signature-table">
                <tr>
                    <td style="width: 26%; padding-right: 8px;">
                        <div class="signature-card">
                            <div class="signature-card-title">Prepared By</div>
                            <div class="signature-name">{{ $generatedByName }}</div>
                            <div class="small-muted">{{ $generatedByRole }}</div>
                            <div class="signature-line"></div>
                            <div class="small-muted">Generated {{ $eatNow->format('d M Y, H:i') }} EAT</div>
                        </div>
                    </td>
                    <td style="width: 28%; padding-right: 8px;">
                        <div class="signature-card">
                            <div class="signature-card-title">Authorized Signature</div>
                            <div class="signature-handwritten">Digitally Approved!</div>
                            <div class="small-muted">Signature Date: {{ $eatNow->format('d M Y, H:i') }} EAT</div>
                            <div class="signature-line"></div>
                            <div class="small-muted">{{ $farmName }} Management Approval</div>
                        </div>
                    </td>
                    <td style="width: 22%; padding-right: 8px; text-align: center;">
                        <div class="stamp-circle">
                            <div class="stamp-text">OFFICIAL<br>STAMP</div>
                        </div>
                        <div class="small-muted">{{ $farmName }} Stamp</div>
                    </td>
                    <td style="width: 24%;">
                        <div class="qr-box">
                            @if (! empty($qrPng))
                                <div class="qr-image-wrap">
                                    <img src="data:image/png;base64,{{ $qrPng }}" class="qr-image" alt="QR Code">
                                </div>
                            @else
                                <div class="qr-fallback">
                                    <span class="small-muted">QR not available</span>
                                </div>
                            @endif
                            <div class="small-muted">Scan to verify report metadata</div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </main>

    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
                $font = $fontMetrics->getFont('Helvetica', 'normal');
                $size = 9;

                $text = "Page {$pageNumber} of {$pageCount}";
                $textWidth = $fontMetrics->getTextWidth($text, $font, $size);

                $pageWidth = $canvas->get_width();
                $pageHeight = $canvas->get_height();

                $x = ($pageWidth - $textWidth) / 2;
                $y = $pageHeight - 32;

                $canvas->text($x, $y, $text, $font, $size, [0.42, 0.45, 0.50]);
            });
        }
    </script>
</body>
</html>
