@php
    $settings = \App\Models\Settings\PaymentSetting::current();
    $farmName = function_exists('setting') ? (setting('farm.name') ?: setting('app.name')) : config('app.name');
    $signature = $settings->authorized_signature_image ?: $settings->invoice_signature_path;
    $stamp = $settings->payment_stamp_image ?: $settings->invoice_stamp_path;
@endphp
<!doctype html>
<html><head><meta charset="utf-8"><style>
@page{margin:32px 36px 55px}body{font-family:DejaVu Sans,sans-serif;color:#111827;font-size:10px}.header{border-bottom:2px solid #111827;padding-bottom:10px;margin-bottom:16px}.title{font-size:20px;font-weight:700}.muted{color:#6b7280}.grid{width:100%;border-collapse:collapse;margin:12px 0}.grid td{width:33.33%;padding:8px;border:1px solid #d1d5db;vertical-align:top}.label{font-size:8px;text-transform:uppercase;color:#6b7280}.value{font-size:11px;font-weight:700;margin-top:3px}.items{width:100%;border-collapse:collapse}.items th,.items td{border:1px solid #d1d5db;padding:6px}.items th{background:#f3f4f6;text-align:left}.right{text-align:right}.total{font-size:14px;font-weight:700}.approval{margin-top:22px;width:100%}.approval td{width:50%;vertical-align:bottom;padding:12px}.sign-img{max-height:55px;max-width:150px}.footer{position:fixed;bottom:-35px;left:0;right:0;text-align:center;color:#6b7280;font-size:8px}
</style></head><body>
<div class="header"><div class="title">{{ $farmName ?: 'Penzi Farm' }}</div><div><strong>Salary Payment Voucher</strong></div><div class="muted">Generated {{ now('Africa/Nairobi')->format('d M Y H:i') }}</div></div>
<table class="grid"><tr><td><div class="label">Payment Number</div><div class="value">{{ $payment->payment_number }}</div></td><td><div class="label">Payroll</div><div class="value">{{ \Carbon\Carbon::create()->month((int)$payment->payroll?->month)->format('F') }} {{ $payment->payroll?->year }}</div></td><td><div class="label">Payment Date</div><div class="value">{{ $payment->payment_date?->format('d M Y H:i') }}</div></td></tr></table>
<table class="items"><thead><tr><th>Employee</th><th>Method</th><th>Destination</th><th>Reference</th><th class="right">Amount (KES)</th></tr></thead><tbody>
@foreach($payment->items as $line)<tr><td>{{ $line->employee?->full_name ?? $line->employee?->name }}</td><td>{{ str($line->payment_method)->replace('_',' ')->title() }}</td><td>{{ $line->bank_account_number ?: $line->phone_number ?: 'Cash' }}</td><td>{{ $line->transaction_reference ?: 'N/A' }}</td><td class="right">{{ number_format((float)$line->amount,2) }}</td></tr>@endforeach
<tr><td colspan="4" class="right total">Total</td><td class="right total">{{ number_format((float)$payment->total_amount,2) }}</td></tr></tbody></table>
<table class="approval"><tr><td>@if($signature)<img class="sign-img" src="{{ str_starts_with($signature,'data:') ? $signature : public_path('storage/'.ltrim($signature,'/')) }}">@endif<br>Authorised Signature</td><td class="right">@if($stamp)<img class="sign-img" src="{{ str_starts_with($stamp,'data:') ? $stamp : public_path('storage/'.ltrim($stamp,'/')) }}">@endif<br>Official Stamp</td></tr></table>
<div class="footer">Posted by {{ $payment->poster?->name ?? 'N/A' }} · Generated by {{ $generatedBy?->name ?? 'System' }}</div>
</body></html>
