@php
    $settings = \App\Models\Settings\PaymentSetting::current();
    $farmName = function_exists('setting') ? (setting('farm.name') ?: setting('app.name')) : config('app.name');
@endphp
<!doctype html><html><head><meta charset="utf-8"><style>
@page{margin:35px}body{font-family:DejaVu Sans,sans-serif;font-size:11px;color:#111827}.header{border-bottom:2px solid #111827;padding-bottom:10px}.title{font-size:20px;font-weight:700}.box{border:1px solid #d1d5db;padding:10px;margin-top:12px}.row{width:100%;border-collapse:collapse}.row td{width:50%;padding:7px;border-bottom:1px solid #e5e7eb}.label{color:#6b7280}.amount{font-size:22px;font-weight:700;text-align:right}.footer{margin-top:30px;font-size:9px;color:#6b7280}
</style></head><body>
<div class="header"><div class="title">{{ $farmName ?: 'Penzi Farm' }}</div><div><strong>Statutory Remittance Voucher</strong></div></div>
<div class="box"><table class="row">
<tr><td><span class="label">Remittance No.</span><br><strong>{{ $remittance->remittance_number }}</strong></td><td><span class="label">Obligation</span><br><strong>{{ $remittance->type_label }}</strong></td></tr>
<tr><td><span class="label">Payroll Period</span><br>{{ $remittance->period_start?->format('d M Y') }} – {{ $remittance->period_end?->format('d M Y') }}</td><td><span class="label">Due Date</span><br>{{ $remittance->due_date?->format('d M Y') }}</td></tr>
<tr><td><span class="label">Payment Date & Time</span><br>{{ $remittance->payment_date?->format('d M Y H:i') }}</td><td><span class="label">Method</span><br>{{ str($remittance->payment_method)->replace('_',' ')->title() }}</td></tr>
<tr><td><span class="label">PRN</span><br>{{ $remittance->payment_registration_number ?: 'N/A' }}</td><td><span class="label">Transaction Reference</span><br>{{ $remittance->transaction_reference ?: 'N/A' }}</td></tr>
</table><div class="amount">KES {{ number_format((float)$remittance->amount,2) }}</div></div>
<div class="footer">Status: {{ str($remittance->status)->title() }} · Posted by {{ $remittance->poster?->name ?? 'N/A' }} · Generated by {{ $generatedBy?->name ?? 'System' }}</div>
</body></html>
