@php
    if (!function_exists('pdfPaymentImageBase64')) {
        function pdfPaymentImageBase64(?string $path): ?string
        {
            if (!$path) {
                return null;
            }

            $cleanPath = trim($path);
            $cleanPath = ltrim($cleanPath, '/');
            $cleanPath = preg_replace('#^storage/#', '', $cleanPath);

            $possiblePaths = [
                storage_path('app/public/' . $cleanPath),
                public_path('storage/' . $cleanPath),
                public_path($cleanPath),
            ];

            foreach ($possiblePaths as $fullPath) {
                if (is_file($fullPath)) {
                    $extension = strtolower(pathinfo($fullPath, PATHINFO_EXTENSION));

                    $mime = match ($extension) {
                        'jpg', 'jpeg' => 'image/jpeg',
                        'png' => 'image/png',
                        'gif' => 'image/gif',
                        'webp' => 'image/webp',
                        'svg' => 'image/svg+xml',
                        default => 'image/png',
                    };

                    return 'data:' . $mime . ';base64,' . base64_encode(file_get_contents($fullPath));
                }
            }

            return null;
        }
    }

    if (!function_exists('pdfPaymentMoney')) {
        function pdfPaymentMoney($amount): string
        {
            return 'KES ' . number_format((float) $amount, 2);
        }
    }

    if (!function_exists('pdfPaymentDate')) {
        function pdfPaymentDate($date, string $format = 'd M Y'): string
        {
            if (!$date) {
                return '-';
            }

            try {
                return \Carbon\Carbon::parse($date)->format($format);
            } catch (\Throwable $e) {
                return '-';
            }
        }
    }

    $purchaseOrder = $purchaseOrder ?? $payment->purchaseOrder;
    $supplier = $supplier ?? $purchaseOrder?->supplier;
    $voucherNumber =
        $voucherNumber ?? ($payment->payment_number ?? 'PV-' . str_pad((string) $payment->id, 6, '0', STR_PAD_LEFT));

    $paidBefore = (float) ($paidBefore ?? 0);
    $balanceBefore = (float) ($balanceBefore ?? max(0, (float) ($purchaseOrder?->grand_total ?? 0) - $paidBefore));
    $balanceAfter = (float) ($balanceAfter ?? max(0, $balanceBefore - (float) ($payment->amount ?? 0)));

    $eatNow = now('Africa/Nairobi');

    $farmName = setting('farm.name', config('app.name', 'Lelekwe Farms'));
    $farmTagline = setting('farm.tagline', 'Nurturing Nature, Feeding The Future');
    $farmPhone = setting('farm.phone', '+254 743 487 186');
    $farmEmail = setting('farm.email', 'jambo@lelekwefarms.co.ke');
    $farmCounty = setting('farm.county', 'Ravine, Kambi Moto');

    $primaryColor = setting('theme.primary', '#014a12');
    $secondaryColor = setting('theme.secondary', '#14532d');
    $accentColor = setting('theme.accent', '#f59e0b');
    $dangerColor = setting('theme.danger', '#dc2626');
    $successColor = setting('theme.success', '#16a34a');

    $logoBase64 = pdfPaymentImageBase64(
        setting('branding.logo_light') ?: setting('branding.logo') ?: setting('farm.logo'),
    );

    $generatedByName = $generatedBy?->name ?? 'System';
    $generatedByRole = $generatedByRole ?? 'User';

    $paymentMethod = str($payment->payment_method ?? '-')
        ->replace('_', ' ')
        ->title()
        ->toString();

    $paymentReference =
        $payment->mpesa_reference ?:
        ($payment->bank_reference ?:
        ($payment->cheque_number ?:
        $payment->reference ?? '-'));

    $supplierName = $supplier->company_name ?? ($supplier->name ?? 'Unknown Supplier');

    $paymentStatus = $payment->status ?? 'successful';

    $statusClass = match ($paymentStatus) {
        'successful', 'completed', 'paid', 'approved' => 'status-success',
        'pending', 'processing' => 'status-warning',
        default => 'status-danger',
    };

    $verificationText =
        $farmName .
        ' Payment Voucher | Voucher: ' .
        $voucherNumber .
        ' | Supplier: ' .
        $supplierName .
        ' | Invoice: ' .
        ($purchaseOrder->invoice_number ?? '-') .
        ' | PO: ' .
        ($purchaseOrder->purchase_order_number ?? '-') .
        ' | Amount: ' .
        pdfPaymentMoney($payment->amount ?? 0) .
        ' | Method: ' .
        $paymentMethod .
        ' | Ref: ' .
        $paymentReference .
        ' | Generated by: ' .
        $generatedByName .
        ' | Date: ' .
        $eatNow->format('Y-m-d H:i:s') .
        ' EAT';

    $qrPng = null;

    if (class_exists(\SimpleSoftwareIO\QrCode\Facades\QrCode::class)) {
        try {
            $qrPng = base64_encode(
                \SimpleSoftwareIO\QrCode\Facades\QrCode::format('png')
                    ->size(110)
                    ->margin(1)
                    ->generate($verificationText),
            );
        } catch (\Throwable $e) {
            $qrPng = null;
        }
    }
@endphp

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ $voucherNumber }}</title>

    <style>
        @font-face {
            font-family: "ChopinScript";
            src: url("{{ public_path('fonts/ChopinScript.ttf') }}") format("truetype");
            font-weight: normal;
            font-style: normal;
        }

        @page {
            margin: 120px 35px 95px 35px;
        }

        body {
            font-family: Courier, sans-serif;
            font-size: 11px;
            color: #222;
            position: relative;
        }

        .watermark {
            position: fixed;
            top: 30%;
            left: 12%;
            width: 75%;
            opacity: 0.055;
            z-index: -1;
            text-align: center;
        }

        .watermark img {
            width: 420px;
        }

        header {
            position: fixed;
            top: -95px;
            left: 0;
            right: 0;
            height: 90px;
            border-bottom: 2px solid {{ $primaryColor }};
        }

        .header-table {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
        }

        .header-table td {
            vertical-align: middle;
        }

        .header-left {
            width: 230px;
            text-align: left;
        }

        .header-center {
            text-align: center;
            width: auto;
        }

        .header-right {
            width: 230px;
            text-align: right;
            font-size: 10px;
            line-height: 1.5;
            color: #374151;
        }

        .logo {
            width: 145px;
            max-height: 75px;
            object-fit: contain;
        }

        .company-title {
            font-size: 22px;
            font-weight: 700;
            color: {{ $primaryColor }};
            margin-bottom: 2px;
            text-align: center;
            line-height: 1.15;
        }

        .tagline {
            font-size: 11px;
            color: #4b5563;
            font-style: italic;
            text-align: center;
            line-height: 1.3;
        }

        footer {
            position: fixed;
            bottom: -72px;
            left: 0;
            right: 0;
            height: 62px;
            border-top: 1px solid #d1d5db;
            font-size: 10px;
            color: #4b5563;
        }

        .footer-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }

        .footer-left {
            text-align: left;
            width: 33%;
        }

        .footer-center {
            text-align: center;
            width: 34%;
        }

        .footer-right {
            text-align: right;
            width: 33%;
        }

        .small-muted {
            color: #6b7280;
            font-size: 9px;
        }

        .report-title {
            margin-top: 5px;
            margin-bottom: 12px;
        }

        .report-title h1 {
            font-size: 18px;
            margin: 0 0 4px 0;
            color: #111827;
        }

        .report-title p {
            margin: 0;
            color: {{ $primaryColor }};
            font-size: 10px;
        }

        .voucher-strip {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 14px;
        }

        .voucher-strip td {
            vertical-align: top;
            padding: 0;
        }

        .voucher-card {
            border: 1px solid #dbe4d3;
            background: #fbfdf9;
            padding: 11px 12px;
            min-height: 86px;
        }

        .voucher-card-dark {
            background: {{ $primaryColor }};
            color: #ffffff;
            border-color: {{ $primaryColor }};
        }

        .voucher-label {
            font-size: 9px;
            font-weight: bold;
            color: {{ $secondaryColor }};
            text-transform: uppercase;
            letter-spacing: .45px;
            margin-bottom: 7px;
        }

        .voucher-card-dark .voucher-label {
            color: #d1fae5;
        }

        .voucher-main {
            font-size: 15px;
            font-weight: bold;
            color: #111827;
            margin-bottom: 4px;
        }

        .voucher-card-dark .voucher-main {
            color: #ffffff;
        }

        .voucher-line {
            font-size: 10px;
            color: #4b5563;
            line-height: 1.55;
        }

        .voucher-card-dark .voucher-line {
            color: #e5e7eb;
        }

        .kpi-table {
            width: 100%;
            border-collapse: collapse;
            margin: 12px 0 16px 0;
        }

        .kpi {
            border: 1px solid #dbe4d3;
            background: #ffffff;
            padding: 10px 12px;
            min-height: 58px;
        }

        .kpi-label {
            font-size: 9px;
            color: #6b7280;
            text-transform: uppercase;
            letter-spacing: .45px;
            font-weight: bold;
        }

        .kpi-value {
            margin-top: 5px;
            font-size: 14px;
            font-weight: bold;
            color: #111827;
        }

        .kpi-success {
            color: {{ $successColor }};
        }

        .kpi-danger {
            color: {{ $dangerColor }};
        }

        .balance-before {
            color: {{ $accentColor }};
        }

        .balance-after {
            color: {{ $dangerColor }};
        }

        .section-heading {
            margin-top: 18px;
            margin-bottom: 8px;
            padding: 8px 10px;
            background: #f3f7ef;
            border-left: 4px solid {{ $primaryColor }};
            color: #111827;
            font-size: 12px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: .35px;
        }

        table.report {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }

        table.report thead th {
            background: {{ $primaryColor }};
            border: 1px solid {{ $primaryColor }};
            color: #ffffff;
            padding: 9px 7px;
            font-size: 9px;
            text-align: left;
            text-transform: uppercase;
            letter-spacing: .25px;
        }

        table.report tbody td {
            border: 1px solid #e5e7eb;
            padding: 8px 7px;
            vertical-align: top;
            font-size: 10px;
        }

        table.report tbody tr:nth-child(even) {
            background: #fafafa;
        }

        .right {
            text-align: right;
        }

        .status-badge {
            display: inline-block;
            padding: 3px 7px;
            border-radius: 999px;
            font-size: 9px;
            font-weight: bold;
            color: #ffffff;
            text-transform: uppercase;
        }

        .status-success {
            background: {{ $successColor }};
        }

        .status-warning {
            background: {{ $accentColor }};
        }

        .status-danger {
            background: {{ $dangerColor }};
        }

        .summary-wrap {
            margin-top: 18px;
            width: 100%;
            border-collapse: collapse;
        }

        .summary-box {
            border: 1px solid #dbe4d3;
            background: #fbfdf9;
            padding: 12px;
        }

        .summary-table {
            width: 100%;
            border-collapse: collapse;
        }

        .summary-table td {
            padding: 6px 4px;
            border-bottom: 1px solid #e5e7eb;
            font-size: 10px;
        }

        .summary-table tr:last-child td {
            border-bottom: none;
        }

        .summary-label {
            color: #374151;
            font-weight: bold;
        }

        .summary-value {
            text-align: right;
            font-weight: bold;
        }

        .signature-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 28px;
        }

        .signature-card {
            border: 1px solid #dbe4d3;
            padding: 12px 14px;
            background: #fbfdf9;
            min-height: 118px;
        }

        .signature-card-title {
            font-size: 11px;
            font-weight: bold;
            color: {{ $secondaryColor }};
            margin-bottom: 10px;
            text-transform: uppercase;
            letter-spacing: .4px;
        }

        .signature-name {
            font-size: 13px;
            font-weight: bold;
            color: #111827;
            margin-bottom: 4px;
        }

        .signature-meta {
            font-size: 9px;
            color: #6b7280;
            margin-bottom: 12px;
        }

        .signature-line {
            border-top: 1px solid #4b5563;
            margin-top: 18px;
            padding-top: 6px;
        }

        .signature-footer {
            font-size: 9px;
            color: #6b7280;
            margin-top: 4px;
        }

        .signature-handwritten {
            font-family: "ChopinScript" !important;
            font-size: 25px;
            color: {{ $successColor }};
            letter-spacing: 1px;
        }

        .stamp-wrap {
            padding-top: 4px;
            text-align: center;
        }

        .stamp-circle {
            width: 110px;
            height: 110px;
            margin: 0 auto 8px auto;
            border: 1px dashed {{ $primaryColor }};
            border-radius: 50%;
            display: table;
        }

        .stamp-text {
            display: table-cell;
            vertical-align: middle;
            text-align: center;
            font-size: 12px;
            font-weight: bold;
            color: {{ $primaryColor }};
            line-height: 1.4;
        }

        .stamp-caption {
            font-size: 9px;
            color: #6b7280;
            text-align: center;
        }

        .qr-box {
            text-align: center;
        }

        .qr-image-wrap {
            width: 104px;
            height: 104px;
            margin: 4px auto 8px auto;
            padding: 4px;
            border: 2px solid {{ $primaryColor }};
            background: #ffffff;
        }

        .qr-image {
            width: 90px;
            height: 90px;
            display: block;
            margin: 0 auto;
        }

        .qr-caption {
            font-size: 8px;
            color: #6b7280;
            margin-top: 6px;
            line-height: 1.4;
        }

        .qr-fallback {
            width: 104px;
            height: 104px;
            margin: 4px auto 8px auto;
            border: 1px solid #999;
            font-size: 9px;
            display: table;
            background: #ffffff;
        }

        .qr-fallback span {
            display: table-cell;
            vertical-align: middle;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="watermark">
        @if ($logoBase64)
            <img src="{{ $logoBase64 }}" alt="Watermark">
        @endif
    </div>

    <header>
        <table class="header-table">
            <tr>
                <td class="header-left">
                    @if ($logoBase64)
                        <img src="{{ $logoBase64 }}" class="logo" alt="Logo">
                    @endif
                </td>

                <td class="header-center">
                    <div class="company-title">{{ $farmName }}</div>
                    <div class="tagline">{{ $farmTagline }}</div>
                </td>

                <td class="header-right">
                    <strong>Phone:</strong> {{ $farmPhone }}<br>
                    <strong>Email:</strong> {{ $farmEmail }}<br>
                    <strong>County:</strong> {{ $farmCounty }}
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table class="footer-table">
            <tr>
                <td class="footer-left">Printed on {{ $eatNow->format('d M Y, H:i') }} EAT</td>
                <td class="footer-center">Payment Voucher</td>
                <td class="footer-right">Created by {{ $generatedByName }} ({{ $generatedByRole }})</td>
            </tr>
            <tr>
                <td colspan="3" class="footer-center small-muted">
                    {{ $farmName }} - {{ $farmCounty }} - {{ $farmPhone }} - {{ $farmEmail }}
                </td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="report-title">
            <h1>Payment Voucher</h1>
            <p>
                Voucher: {{ $voucherNumber }}
                | Supplier Invoice: {{ $purchaseOrder->invoice_number ?? '-' }}
                | Purchase Order: {{ $purchaseOrder->purchase_order_number ?? '-' }}
            </p>
        </div>

        <table class="voucher-strip">
            <tr>
                <td style="width: 50%; padding-right: 8px;">
                    <div class="voucher-card">
                        <div class="voucher-label">Payee / Supplier</div>
                        <div class="voucher-main">{{ $supplierName }}</div>
                        <div class="voucher-line">
                            Contact: {{ $supplier->contact_person ?? '-' }}<br>
                            Phone: {{ $supplier->phone_primary ?? ($supplier->phone ?? '-') }}<br>
                            Email: {{ $supplier->email ?? '-' }}<br>
                            KRA PIN: {{ $supplier->kra_pin ?? '-' }}
                        </div>
                    </div>
                </td>

                <td style="width: 50%; padding-left: 8px;">
                    <div class="voucher-card voucher-card-dark">
                        <div class="voucher-label">Voucher Summary</div>
                        <div class="voucher-main">{{ pdfPaymentMoney($payment->amount ?? 0) }}</div>
                        <div class="voucher-line">
                            Method: {{ $paymentMethod }}<br>
                            Reference: {{ $paymentReference }}<br>
                            Payment Date: {{ pdfPaymentDate($payment->payment_date) }}<br>
                            Status:
                            <span class="status-badge {{ $statusClass }}">
                                {{ str($paymentStatus)->replace('_', ' ')->title() }}
                            </span>
                        </div>
                    </div>
                </td>
            </tr>
        </table>

        <table class="kpi-table">
            <tr>
                <td style="width: 25%; padding-right: 6px;">
                    <div class="kpi">
                        <div class="kpi-label">Invoice Total</div>
                        <div class="kpi-value">{{ pdfPaymentMoney($purchaseOrder->grand_total ?? 0) }}</div>
                    </div>
                </td>

                <td style="width: 25%; padding: 0 6px;">
                    <div class="kpi">
                        <div class="kpi-label">Balance Before</div>
                        <div class="kpi-value balance-before">{{ pdfPaymentMoney($balanceBefore) }}</div>
                    </div>
                </td>

                <td style="width: 25%; padding: 0 6px;">
                    <div class="kpi">
                        <div class="kpi-label">Amount Paid</div>
                        <div class="kpi-value kpi-success">{{ pdfPaymentMoney($payment->amount ?? 0) }}</div>
                    </div>
                </td>

                <td style="width: 25%; padding-left: 6px;">
                    <div class="kpi">
                        <div class="kpi-label">Balance After</div>
                        <div class="kpi-value {{ $balanceAfter > 0 ? 'kpi-danger' : 'kpi-success' }}">
                            {{ pdfPaymentMoney($balanceAfter) }}
                        </div>
                    </div>
                </td>
            </tr>
        </table>

        <div class="section-heading">Payment Details</div>

        <table class="report">
            <thead>
                <tr>
                    <th width="18%">Payment No.</th>
                    <th width="14%">Date</th>
                    <th width="16%">Method</th>
                    <th width="22%">Reference</th>
                    <th width="14%">Status</th>
                    <th width="16%" class="right">Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ $payment->payment_number ?? $voucherNumber }}</td>
                    <td>{{ pdfPaymentDate($payment->payment_date) }}</td>
                    <td>{{ $paymentMethod }}</td>
                    <td>{{ $paymentReference }}</td>
                    <td>
                        <span class="status-badge {{ $statusClass }}">
                            {{ str($paymentStatus)->replace('_', ' ')->title() }}
                        </span>
                    </td>
                    <td class="right">{{ pdfPaymentMoney($payment->amount ?? 0) }}</td>
                </tr>
            </tbody>
        </table>

        <div class="section-heading">Invoice / Purchase Order Reference</div>

        <table class="report">
            <thead>
                <tr>
                    <th width="18%">PO Number</th>
                    <th width="18%">Invoice</th>
                    <th width="14%">Order Date</th>
                    <th width="14%">Due Date</th>
                    <th width="12%">PO Status</th>
                    <th width="12%">Pay Status</th>
                    <th width="12%" class="right">Total</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ $purchaseOrder->purchase_order_number ?? '-' }}</td>
                    <td>{{ $purchaseOrder->invoice_number ?? '-' }}</td>
                    <td>{{ pdfPaymentDate($purchaseOrder->order_date ?? null) }}</td>
                    <td>{{ pdfPaymentDate($purchaseOrder->due_date ?? null) }}</td>
                    <td>{{ str($purchaseOrder->status ?? '-')->replace('_', ' ')->title() }}</td>
                    <td>{{ str($purchaseOrder->payment_status ?? '-')->replace('_', ' ')->title() }}</td>
                    <td class="right">{{ pdfPaymentMoney($purchaseOrder->grand_total ?? 0) }}</td>
                </tr>
            </tbody>
        </table>

        <table class="summary-wrap">
            <tr>
                <td style="width: 55%; padding-right: 12px; vertical-align: top;">
                    <div class="summary-box">
                        <strong>Voucher Note</strong><br>
                        <span class="small-muted">
                            This voucher confirms a supplier payment recorded against the listed purchase order or
                            supplier invoice.
                            The balance after payment is calculated from invoice total, previous successful payments,
                            and this payment.
                        </span>
                    </div>
                </td>

                <td style="width: 45%; vertical-align: top;">
                    <div class="summary-box">
                        <table class="summary-table">
                            <tr>
                                <td class="summary-label">Invoice Total</td>
                                <td class="summary-value">{{ pdfPaymentMoney($purchaseOrder->grand_total ?? 0) }}</td>
                            </tr>
                            <tr>
                                <td class="summary-label">Paid Before</td>
                                <td class="summary-value">{{ pdfPaymentMoney($paidBefore) }}</td>
                            </tr>
                            <tr>
                                <td class="summary-label">This Payment</td>
                                <td class="summary-value kpi-success">{{ pdfPaymentMoney($payment->amount ?? 0) }}</td>
                            </tr>
                            <tr>
                                <td class="summary-label">Balance After</td>
                                <td class="summary-value {{ $balanceAfter > 0 ? 'balance-after' : 'kpi-success' }}">
                                    {{ pdfPaymentMoney($balanceAfter) }}
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>

        <table class="signature-table">
            <tr>
                <td style="width: 26%; padding-right: 8px;">
                    <div class="signature-card">
                        <div class="signature-card-title">Prepared By</div>
                        <div class="signature-name">{{ $generatedByName }}</div>
                        <div class="signature-meta">{{ $generatedByRole }}</div>
                        <div class="signature-line"></div>
                        <div class="signature-footer">
                            Generated on {{ $eatNow->format('d M Y, H:i') }} EAT
                        </div>
                    </div>
                </td>

                <td style="width: 28%; padding-right: 8px;">
                    <div class="signature-card">
                        <div class="signature-card-title">Finance Approval</div>
                        <div class="signature-handwritten">Approved</div>
                        <div class="signature-meta">
                            Approval Date: {{ $eatNow->format('d M Y, H:i') }} EAT
                        </div>
                        <div class="signature-line"></div>
                        <div class="signature-footer">
                            {{ $farmName }} Procurement / Finance
                        </div>
                    </div>
                </td>

                <td style="width: 22%; padding-right: 8px;">
                    <div class="stamp-wrap">
                        <div class="stamp-circle">
                            <div class="stamp-text">OFFICIAL<br>STAMP</div>
                        </div>
                        <div class="stamp-caption">{{ $farmName }} Stamp</div>
                    </div>
                </td>

                <td style="width: 24%;">
                    <div class="qr-box">
                        @if (!empty($qrPng))
                            <div class="qr-image-wrap">
                                <img src="data:image/png;base64,{{ $qrPng }}" alt="QR Code"
                                    class="qr-image">
                            </div>
                        @else
                            <div class="qr-fallback">
                                <span>QR not available</span>
                            </div>
                        @endif

                        <div class="qr-caption">
                            Scan to verify voucher metadata
                        </div>
                    </div>
                </td>
            </tr>
        </table>
    </main>

    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
                $font = $fontMetrics->getFont('Helvetica', 'normal');
                $size = 9;

                $text = "Page {$pageNumber} of {$pageCount}";
                $width = $fontMetrics->getTextWidth($text, $font, $size);

                $x = 297.5 - ($width / 2);
                $y = 805;

                $canvas->text($x, $y, $text, $font, $size, [0.42, 0.45, 0.50]);
            });
        }
    </script>
</body>

</html>
