@php
    if (! function_exists('pdfImageBase64')) {
        function pdfImageBase64(?string $path): ?string
        {
            if (! $path) {
                return null;
            }

            $cleanPath = trim($path);
            $cleanPath = ltrim($cleanPath, '/');
            $cleanPath = preg_replace('#^storage/#', '', $cleanPath);

            $possiblePaths = [
                storage_path('app/public/' . $cleanPath),
                public_path('storage/' . $cleanPath),
                public_path($cleanPath),
            ];

            foreach ($possiblePaths as $fullPath) {
                if (is_file($fullPath)) {
                    $extension = strtolower(pathinfo($fullPath, PATHINFO_EXTENSION));

                    $mime = match ($extension) {
                        'jpg', 'jpeg' => 'image/jpeg',
                        'png' => 'image/png',
                        'gif' => 'image/gif',
                        'webp' => 'image/webp',
                        'svg' => 'image/svg+xml',
                        'ico' => 'image/x-icon',
                        default => 'image/png',
                    };

                    return 'data:' . $mime . ';base64,' . base64_encode(file_get_contents($fullPath));
                }
            }

            return null;
        }
    }

    $eatNow = now('Africa/Nairobi');

    $farmName = setting('farm.name', config('app.name', 'Lelekwe Farms'));
    $farmTagline = setting('farm.tagline', 'Nurturing Nature, Feeding The Future');
    $farmPhone = setting('farm.phone', '+254 743 487 186');
    $farmEmail = setting('farm.email', 'jambo@lelekwefarms.co.ke');
    $farmCounty = setting('farm.county', 'Ravine, Kambi Moto');
    $farmAddress = setting('farm.address', $farmCounty);

    $primaryColor = setting('theme.primary', '#014a12');
    $secondaryColor = setting('theme.secondary', '#14532d');
    $accentColor = setting('theme.accent', '#f59e0b');
    $dangerColor = setting('theme.danger', '#dc2626');
    $successColor = setting('theme.success', '#16a34a');

    $logoBase64 = pdfImageBase64(setting('branding.logo_light'));

    $generatedByName = $generatedBy?->name ?? 'System';
    $generatedByRole = $generatedByRole ?? 'User';

    $invoiceNumber = $purchaseOrder->invoice_number ?: ('PINV-' . $purchaseOrder->id);
    $poNumber = $purchaseOrder->purchase_order_number ?: ('PO-' . $purchaseOrder->id);

    $paymentStatus = $purchaseOrder->payment_status ?? 'unpaid';
    $orderStatus = $purchaseOrder->status ?? 'draft';

    $paymentBadgeClass = match ($paymentStatus) {
        'paid' => 'badge-success',
        'partial' => 'badge-warning',
        default => 'badge-danger',
    };

    $orderBadgeClass = match ($orderStatus) {
        'received' => 'badge-success',
        'partially_received', 'ordered' => 'badge-warning',
        'cancelled' => 'badge-danger',
        default => 'badge-gray',
    };

    $verificationText =
        $farmName .
        ' Procurement Invoice | Invoice: ' .
        $invoiceNumber .
        ' | PO: ' .
        $poNumber .
        ' | Supplier: ' .
        ($purchaseOrder->supplier?->company_name ?? 'N/A') .
        ' | Total: KES ' .
        number_format((float) $purchaseOrder->grand_total, 2) .
        ' | Balance: KES ' .
        number_format((float) $purchaseOrder->balance_due, 2) .
        ' | Generated by: ' .
        $generatedByName .
        ' (' .
        $generatedByRole .
        ') | Date: ' .
        $eatNow->format('Y-m-d H:i:s') .
        ' EAT';

    $qrPng = null;

    if (class_exists(\SimpleSoftwareIO\QrCode\Facades\QrCode::class)) {
        try {
            $qrPng = base64_encode(
                \SimpleSoftwareIO\QrCode\Facades\QrCode::format('png')
                    ->size(105)
                    ->margin(1)
                    ->generate($verificationText)
            );
        } catch (\Throwable $e) {
            $qrPng = null;
        }
    }

    $amountPaid = (float) $purchaseOrder->amount_paid;
    $grandTotal = (float) $purchaseOrder->grand_total;
    $balanceDue = (float) $purchaseOrder->balance_due;

    $paidPercent = $grandTotal > 0 ? min(100, round(($amountPaid / $grandTotal) * 100, 1)) : 0;
@endphp

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $invoiceNumber }}</title>

    <style>
        @page {
            margin: 122px 34px 92px 34px;
        }

        body {
            font-family: Courier, sans-serif;
            font-size: 10.5px;
            color: #111827;
            position: relative;
        }

        .watermark {
            position: fixed;
            top: 34%;
            left: 12%;
            width: 76%;
            opacity: 0.045;
            z-index: -1;
            text-align: center;
        }

        .watermark img {
            width: 430px;
        }

        header {
            position: fixed;
            top: -96px;
            left: 0;
            right: 0;
            height: 88px;
            border-bottom: 2px solid {{ $primaryColor }};
        }

        footer {
            position: fixed;
            bottom: -70px;
            left: 0;
            right: 0;
            height: 60px;
            border-top: 1px solid #d1d5db;
            font-size: 9px;
            color: #4b5563;
        }

        .header-table,
        .footer-table,
        .meta-table,
        .items,
        .summary,
        .payments,
        .approval-table {
            width: 100%;
            border-collapse: collapse;
        }

        .header-table td {
            vertical-align: middle;
        }

        .header-left {
            width: 120px;
            text-align: left;
        }

        .header-center {
            text-align: center;
        }

        .header-right {
            width: 220px;
            text-align: right;
            font-size: 9.5px;
            line-height: 1.45;
            color: #374151;
        }

        .logo {
            width: 170px;
            max-height: 72px;
            object-fit: contain;
        }

        .company-title {
            font-size: 21px;
            font-weight: 700;
            color: {{ $primaryColor }};
            margin-bottom: 2px;
        }

        .tagline {
            font-size: 10px;
            color: #4b5563;
            font-style: italic;
        }

        .footer-table {
            margin-top: 8px;
        }

        .footer-left {
            width: 33%;
            text-align: left;
        }

        .footer-center {
            width: 34%;
            text-align: center;
        }

        .footer-right {
            width: 33%;
            text-align: right;
        }

        .small-muted {
            color: #6b7280;
            font-size: 8.5px;
        }

        .document-head {
            margin-bottom: 12px;
        }

        .document-title {
            font-size: 18px;
            font-weight: 700;
            margin: 0;
            color: #111827;
        }

        .document-subtitle {
            margin-top: 3px;
            color: {{ $primaryColor }};
            font-size: 9.5px;
        }

        .payment-explainer {
            border: 1px solid #cfe3bf;
            background: #f8fff2;
            padding: 10px 12px;
            margin: 10px 0 14px 0;
            border-radius: 8px;
        }

        .payment-explainer-title {
            font-size: 12px;
            font-weight: bold;
            color: {{ $primaryColor }};
            margin-bottom: 5px;
        }

        .payment-explainer p {
            margin: 2px 0;
            line-height: 1.45;
        }

        .meta-card {
            border: 1px solid #e5e7eb;
            border-radius: 8px;
            padding: 10px;
            background: #fff;
        }

        .meta-title {
            font-size: 11px;
            font-weight: bold;
            color: {{ $secondaryColor }};
            margin-bottom: 7px;
            text-transform: uppercase;
        }

        .meta-line {
            margin-bottom: 4px;
        }

        .muted {
            color: #6b7280;
            font-size: 9px;
        }

        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 999px;
            font-size: 8.5px;
            font-weight: bold;
        }

        .badge-success {
            background: #dcfce7;
            color: {{ $successColor }};
        }

        .badge-warning {
            background: #fef3c7;
            color: #92400e;
        }

        .badge-danger {
            background: #fee2e2;
            color: {{ $dangerColor }};
        }

        .badge-gray {
            background: #f3f4f6;
            color: #4b5563;
        }

        .items {
            margin-top: 12px;
        }

        .items th {
            background: {{ $primaryColor }};
            color: white;
            padding: 7px 6px;
            border: 1px solid {{ $primaryColor }};
            text-align: left;
            font-size: 9px;
        }

        .items td {
            padding: 6px;
            border: 1px solid #e5e7eb;
            vertical-align: top;
            font-size: 9.5px;
        }

        .items tr:nth-child(even) td {
            background: #fafafa;
        }

        .right {
            text-align: right;
        }

        .center {
            text-align: center;
        }

        .section-title {
            margin-top: 18px;
            margin-bottom: 7px;
            font-size: 12px;
            color: {{ $primaryColor }};
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 0.4px;
        }

        .summary td {
            padding: 5px;
            font-size: 10px;
        }

        .summary .label {
            text-align: right;
            font-weight: bold;
            color: #374151;
        }

        .summary .amount {
            text-align: right;
            border-bottom: 1px solid #e5e7eb;
        }

        .grand-row td {
            font-size: 12px;
            font-weight: bold;
            color: {{ $primaryColor }};
        }

        .balance-row td {
            font-size: 12px;
            font-weight: bold;
            color: {{ $dangerColor }};
        }

        .payment-box {
            border: 1px solid #e5e7eb;
            border-radius: 8px;
            padding: 10px;
            background: #fff;
            margin-top: 10px;
        }

        .payment-bar-bg {
            width: 100%;
            height: 10px;
            border-radius: 999px;
            background: #e5e7eb;
            overflow: hidden;
            margin-top: 6px;
        }

        .payment-bar-fill {
            height: 10px;
            border-radius: 999px;
            background: {{ $successColor }};
            width: {{ $paidPercent }}%;
        }

        .payments th {
            background: #f3f4f6;
            color: #111827;
            padding: 6px;
            border: 1px solid #e5e7eb;
            font-size: 9px;
            text-align: left;
        }

        .payments td {
            padding: 6px;
            border: 1px solid #e5e7eb;
            font-size: 9px;
        }

        .signature-card {
            border: 1px solid #dbe4d3;
            border-radius: 8px;
            padding: 10px 12px;
            background: #fbfdf9;
            min-height: 80px;
        }

        .signature-title {
            font-size: 10px;
            font-weight: bold;
            color: {{ $secondaryColor }};
            text-transform: uppercase;
            margin-bottom: 14px;
        }

        .signature-line {
            border-top: 1px solid #4b5563;
            padding-top: 5px;
            font-size: 9px;
            color: #6b7280;
        }

        .qr-box {
            text-align: center;
        }

        .qr-image-wrap {
            width: 98px;
            height: 98px;
            margin: 0 auto 6px auto;
            padding: 4px;
            border: 2px solid {{ $primaryColor }};
            background: #fff;
            border-radius: 8px;
        }

        .qr-image {
            width: 88px;
            height: 88px;
        }

        .qr-fallback {
            width: 98px;
            height: 98px;
            margin: 0 auto 6px auto;
            border: 1px solid #999;
            border-radius: 8px;
            display: table;
            font-size: 8px;
        }

        .qr-fallback span {
            display: table-cell;
            vertical-align: middle;
            text-align: center;
        }

        .avoid-break {
            page-break-inside: avoid;
        }
    </style>
</head>

<body>
    <div class="watermark">
        @if ($logoBase64)
            <img src="{{ $logoBase64 }}" alt="Watermark">
        @endif
    </div>

    <header>
        <table class="header-table">
            <tr>
                <td class="header-left">
                    @if ($logoBase64)
                        <img src="{{ $logoBase64 }}" class="logo" alt="Logo">
                    @endif
                </td>

                <td class="header-center">
                    <div class="company-title">{{ $farmName }}</div>
                    <div class="tagline">{{ $farmTagline }}</div>
                </td>

                <td class="header-right">
                    <strong>Phone:</strong> {{ $farmPhone }}<br>
                    <strong>Email:</strong> {{ $farmEmail }}<br>
                    <strong>Location:</strong> {{ $farmAddress }}
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table class="footer-table">
            <tr>
                <td class="footer-left">
                    Printed {{ $eatNow->format('d M Y, H:i') }} EAT
                </td>
                <td class="footer-center">
                    Procurement Invoice
                </td>
                <td class="footer-right">
                    Created by {{ $generatedByName }} ({{ $generatedByRole }})
                </td>
            </tr>
            <tr>
                <td colspan="3" class="footer-center small-muted">
                    {{ $farmName }} • {{ $farmAddress }} • {{ $farmPhone }} • {{ $farmEmail }}
                </td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="document-head">
            <h1 class="document-title">Procurement Invoice</h1>
            <div class="document-subtitle">
                System Invoice: <strong>{{ $invoiceNumber }}</strong>
                &nbsp; | &nbsp;
                Purchase Order: <strong>{{ $poNumber }}</strong>
            </div>
        </div>

        <div class="payment-explainer avoid-break">
            <div class="payment-explainer-title">When is this invoice paid?</div>
            <p>
                Payment is recorded after the purchase order has a confirmed supplier cost.
                The payment should be made against this document using the
                <strong>System Invoice No. {{ $invoiceNumber }}</strong>,
                the <strong>PO No. {{ $poNumber }}</strong>, or the supplier's own invoice reference.
            </p>
            <p>
                <strong>Amount to pay now:</strong>
                KES {{ number_format($balanceDue, 2) }}.
                If the balance is zero, this invoice is fully paid.
            </p>
        </div>

        <table class="meta-table">
            <tr>
                <td width="50%" style="padding-right: 7px;">
                    <div class="meta-card">
                        <div class="meta-title">Supplier Details</div>
                        <div class="meta-line"><strong>Name:</strong> {{ $purchaseOrder->supplier?->company_name ?? '-' }}</div>
                        <div class="meta-line"><strong>Contact:</strong> {{ $purchaseOrder->supplier?->contact_person ?? '-' }}</div>
                        <div class="meta-line"><strong>Phone:</strong> {{ $purchaseOrder->supplier?->phone_primary ?? '-' }}</div>
                        <div class="meta-line"><strong>Email:</strong> {{ $purchaseOrder->supplier?->email ?? '-' }}</div>
                        <div class="meta-line"><strong>KRA PIN:</strong> {{ $purchaseOrder->supplier?->kra_pin ?? '-' }}</div>
                    </div>
                </td>

                <td width="50%" style="padding-left: 7px;">
                    <div class="meta-card">
                        <div class="meta-title">Invoice Control</div>
                        <div class="meta-line"><strong>System Invoice:</strong> {{ $invoiceNumber }}</div>
                        <div class="meta-line"><strong>PO Number:</strong> {{ $poNumber }}</div>
                        <div class="meta-line"><strong>Supplier Invoice:</strong> {{ $purchaseOrder->supplier_invoice_number ?? '-' }}</div>
                        <div class="meta-line"><strong>Invoice Date:</strong> {{ $purchaseOrder->invoice_date?->format('d M Y') ?? '-' }}</div>
                        <div class="meta-line"><strong>Due Date:</strong> {{ $purchaseOrder->due_date?->format('d M Y') ?? '-' }}</div>
                        <div class="meta-line">
                            <strong>Order Status:</strong>
                            <span class="badge {{ $orderBadgeClass }}">{{ str($orderStatus)->replace('_', ' ')->title() }}</span>
                        </div>
                        <div class="meta-line">
                            <strong>Payment Status:</strong>
                            <span class="badge {{ $paymentBadgeClass }}">{{ str($paymentStatus)->replace('_', ' ')->title() }}</span>
                        </div>
                    </div>
                </td>
            </tr>
        </table>

        <div class="section-title">Itemized Procurement Charges</div>

        <table class="items">
            <thead>
                <tr>
                    <th width="4%">#</th>
                    <th width="23%">Product / Item</th>
                    <th width="9%">Batch</th>
                    <th width="8%" class="right">Qty</th>
                    <th width="10%" class="right">Unit Cost</th>
                    <th width="10%" class="right">Subtotal</th>
                    <th width="8%" class="right">Disc.</th>
                    <th width="7%" class="right">Tax %</th>
                    <th width="9%" class="right">Tax</th>
                    <th width="12%" class="right">Line Total</th>
                </tr>
            </thead>

            <tbody>
                @forelse ($purchaseOrder->items as $index => $item)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>
                            <strong>{{ $item->healthProduct?->name ?? $item->inventoryItem?->name ?? '-' }}</strong><br>
                            <span class="muted">
                                {{ $item->inventoryItem?->category_label ?? '-' }}
                                @if ($item->expiry_date)
                                    • Exp: {{ $item->expiry_date->format('d M Y') }}
                                @endif
                            </span>
                        </td>
                        <td>{{ $item->batch_number ?? '-' }}</td>
                        <td class="right">{{ number_format((float) $item->quantity_ordered, 2) }}</td>
                        <td class="right">{{ number_format((float) $item->unit_cost, 2) }}</td>
                        <td class="right">{{ number_format((float) $item->line_subtotal, 2) }}</td>
                        <td class="right">{{ number_format((float) $item->discount_amount, 2) }}</td>
                        <td class="right">{{ number_format((float) $item->tax_rate, 2) }}%</td>
                        <td class="right">{{ number_format((float) $item->tax_amount, 2) }}</td>
                        <td class="right"><strong>{{ number_format((float) $item->line_total, 2) }}</strong></td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="10" class="center">No procurement items recorded.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        <table style="width: 100%; margin-top: 12px;">
            <tr>
                <td width="47%" style="vertical-align: top; padding-right: 10px;">
                    <div class="payment-box avoid-break">
                        <div class="meta-title">Payment Position</div>
                        <div><strong>Grand Total:</strong> KES {{ number_format($grandTotal, 2) }}</div>
                        <div><strong>Amount Paid:</strong> KES {{ number_format($amountPaid, 2) }}</div>
                        <div><strong>Balance Due:</strong> KES {{ number_format($balanceDue, 2) }}</div>

                        <div class="payment-bar-bg">
                            <div class="payment-bar-fill"></div>
                        </div>

                        <div class="muted" style="margin-top: 5px;">
                            {{ $paidPercent }}% paid. Payments should be recorded under Procurement → Supplier Payments.
                        </div>
                    </div>
                </td>

                <td width="53%" style="vertical-align: top;">
                    <table class="summary">
                        <tr>
                            <td class="label">Subtotal</td>
                            <td class="amount">KES {{ number_format((float) $purchaseOrder->subtotal, 2) }}</td>
                        </tr>
                        <tr>
                            <td class="label">Item Tax</td>
                            <td class="amount">KES {{ number_format((float) $purchaseOrder->tax_amount, 2) }}</td>
                        </tr>
                        <tr>
                            <td class="label">Order Discount</td>
                            <td class="amount">KES {{ number_format((float) $purchaseOrder->discount_amount, 2) }}</td>
                        </tr>
                        <tr>
                            <td class="label">Other Charges</td>
                            <td class="amount">KES {{ number_format((float) $purchaseOrder->other_charges, 2) }}</td>
                        </tr>
                        <tr class="grand-row">
                            <td class="label">Grand Total</td>
                            <td class="amount">KES {{ number_format($grandTotal, 2) }}</td>
                        </tr>
                        <tr>
                            <td class="label">Paid</td>
                            <td class="amount">KES {{ number_format($amountPaid, 2) }}</td>
                        </tr>
                        <tr class="balance-row">
                            <td class="label">Balance Due</td>
                            <td class="amount">KES {{ number_format($balanceDue, 2) }}</td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>

        <div class="section-title">Payment History</div>

        <table class="payments">
            <thead>
                <tr>
                    <th width="5%">#</th>
                    <th width="18%">Payment No.</th>
                    <th width="14%">Date</th>
                    <th width="18%">Method</th>
                    <th width="18%">Reference</th>
                    <th width="12%">Status</th>
                    <th width="15%" class="right">Amount</th>
                </tr>
            </thead>

            <tbody>
                @forelse ($purchaseOrder->payments as $index => $payment)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $payment->payment_number }}</td>
                        <td>{{ $payment->payment_date?->format('d M Y') }}</td>
                        <td>{{ str($payment->payment_method)->replace('_', ' ')->title() }}</td>
                        <td>
                            {{ $payment->mpesa_reference
                                ?: ($payment->bank_reference
                                ?: ($payment->cheque_number ?: '-')) }}
                        </td>
                        <td>{{ str($payment->status)->title() }}</td>
                        <td class="right">KES {{ number_format((float) $payment->amount, 2) }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7" class="center">
                            No supplier payment has been recorded for this procurement invoice.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        <div class="section-title">Approval & Verification</div>

        <table class="approval-table avoid-break">
            <tr>
                <td width="32%" style="padding-right: 8px;">
                    <div class="signature-card">
                        <div class="signature-title">Prepared By</div>
                        <div><strong>{{ $generatedByName }}</strong></div>
                        <div class="muted">{{ $generatedByRole }}</div>
                        <br>
                        <div class="signature-line">
                            Generated {{ $eatNow->format('d M Y, H:i') }} EAT
                        </div>
                    </div>
                </td>

                <td width="32%" style="padding-right: 8px;">
                    <div class="signature-card">
                        <div class="signature-title">Finance Approval</div>
                        <br><br>
                        <div class="signature-line">
                            Name / Signature / Date
                        </div>
                    </div>
                </td>

                <td width="18%" style="padding-right: 8px;">
                    <div class="signature-card center">
                        <div class="signature-title">Stamp</div>
                        <br><br>
                        <div class="signature-line">
                            Official Stamp
                        </div>
                    </div>
                </td>

                <td width="18%">
                    <div class="qr-box">
                        @if (! empty($qrPng))
                            <div class="qr-image-wrap">
                                <img src="data:image/png;base64,{{ $qrPng }}" class="qr-image" alt="QR">
                            </div>
                        @else
                            <div class="qr-fallback">
                                <span>QR unavailable</span>
                            </div>
                        @endif

                        <div class="muted">Scan to verify invoice metadata</div>
                    </div>
                </td>
            </tr>
        </table>
    </main>

    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
                $font = $fontMetrics->getFont('Helvetica', 'normal');
                $size = 8.5;

                $text = "Page {$pageNumber} of {$pageCount}";
                $width = $fontMetrics->getTextWidth($text, $font, $size);

                $x = 297.5 - ($width / 2);
                $y = 806;

                $canvas->text($x, $y, $text, $font, $size, [0.42, 0.45, 0.50]);
            });
        }
    </script>
</body>
</html>
