@php
    if (!function_exists('pdfImageBase64')) {
        function pdfImageBase64(?string $path): ?string
        {
            if (!$path) {
                return null;
            }

            $cleanPath = trim($path);
            $cleanPath = ltrim($cleanPath, '/');
            $cleanPath = preg_replace('#^storage/#', '', $cleanPath);

            $possiblePaths = [
                storage_path('app/public/' . $cleanPath),
                public_path('storage/' . $cleanPath),
                public_path($cleanPath),
            ];

            foreach ($possiblePaths as $fullPath) {
                if (is_file($fullPath)) {
                    $extension = strtolower(pathinfo($fullPath, PATHINFO_EXTENSION));

                    $mime = match ($extension) {
                        'jpg', 'jpeg' => 'image/jpeg',
                        'png' => 'image/png',
                        'gif' => 'image/gif',
                        'webp' => 'image/webp',
                        'svg' => 'image/svg+xml',
                        'ico' => 'image/x-icon',
                        default => 'image/png',
                    };

                    return 'data:' . $mime . ';base64,' . base64_encode(file_get_contents($fullPath));
                }
            }

            return null;
        }
    }

    if (!function_exists('pdfMoney')) {
        function pdfMoney($amount): string
        {
            return 'KES ' . number_format((float) $amount, 2);
        }
    }

    if (!function_exists('pdfDate')) {
        function pdfDate($date, string $format = 'd M Y'): string
        {
            if (!$date) {
                return '-';
            }

            try {
                return \Carbon\Carbon::parse($date)->format($format);
            } catch (\Throwable $e) {
                return '-';
            }
        }
    }

    $eatNow = now('Africa/Nairobi');

    $farmName = setting('farm.name', config('app.name', 'Lelekwe Farms'));
    $farmTagline = setting('farm.tagline', 'Nurturing Nature, Feeding The Future');
    $farmPhone = setting('farm.phone', '+254 743 487 186');
    $farmEmail = setting('farm.email', 'jambo@lelekwefarms.co.ke');
    $farmCounty = setting('farm.county', 'Ravine, Kambi Moto');

    $primaryColor = setting('theme.primary', '#014a12');
    $secondaryColor = setting('theme.secondary', '#14532d');
    $accentColor = setting('theme.accent', '#f59e0b');
    $dangerColor = setting('theme.danger', '#dc2626');
    $successColor = setting('theme.success', '#16a34a');

    $logoBase64 = pdfImageBase64(setting('branding.logo_light'));

    $generatedByName = $generatedBy->name ?? 'System';
    $generatedByRole = $generatedByRole ?? ($generatedBy?->getRoleNames()?->first() ?? 'User');

    // $invoiceTotal = (float) $purchaseOrders->sum('grand_total');
    // $paymentTotal = (float) $payments->where('status', 'successful')->sum('amount');

    //$balance = max(0, $invoiceTotal - $paymentTotal);

    $successfulStatuses = ['successful', 'completed', 'paid', 'approved'];

    $invoiceTotal = (float) $purchaseOrders->sum('grand_total');

    $paymentTotal = (float) $payments->whereIn('status', $successfulStatuses)->sum('amount');

    $balance = max(0, $invoiceTotal - $paymentTotal);

    $invoiceCount = $purchaseOrders->count();
    $paymentCount = $payments->count();

    $currentBucket = 0;
    $bucket0to7 = 0;
    $bucket8to30 = 0;
    $bucket31to60 = 0;
    $bucket60Plus = 0;

    foreach ($purchaseOrders as $order) {
        $orderBalance = (float) ($order->balance_due ?? 0);

        if ($orderBalance <= 0) {
            continue;
        }

        if (!$order->due_date) {
            $currentBucket += $orderBalance;
            continue;
        }

        $dueDate = \Carbon\Carbon::parse($order->due_date)->startOfDay();
        $today = $eatNow->copy()->startOfDay();

        if ($dueDate->gte($today)) {
            $currentBucket += $orderBalance;
            continue;
        }

        $daysOverdue = $dueDate->diffInDays($today);

        if ($daysOverdue <= 7) {
            $bucket0to7 += $orderBalance;
        } elseif ($daysOverdue <= 30) {
            $bucket8to30 += $orderBalance;
        } elseif ($daysOverdue <= 60) {
            $bucket31to60 += $orderBalance;
        } else {
            $bucket60Plus += $orderBalance;
        }
    }

    $verificationText =
        $farmName .
        ' Supplier Statement | Supplier: ' .
        ($supplier->company_name ?? 'Unknown Supplier') .
        ' | Period: ' .
        $from .
        ' to ' .
        $to .
        ' | Generated by: ' .
        $generatedByName .
        ' (' .
        $generatedByRole .
        ')' .
        ' | Date: ' .
        $eatNow->format('Y-m-d H:i:s') .
        ' EAT | Balance: ' .
        pdfMoney($balance);

    $qrPng = null;

    if (class_exists(\SimpleSoftwareIO\QrCode\Facades\QrCode::class)) {
        try {
            $qrPng = base64_encode(
                \SimpleSoftwareIO\QrCode\Facades\QrCode::format('png')
                    ->size(110)
                    ->margin(1)
                    ->generate($verificationText),
            );
        } catch (\Throwable $e) {
            $qrPng = null;
        }
    }

    $balanceClass = $balance > 0 ? 'status-danger' : 'status-success';
@endphp

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Supplier Statement</title>

    <style>
        @font-face {
            font-family: "ChopinScript";
            src: url("{{ public_path('fonts/ChopinScript.ttf') }}") format("truetype");
            font-weight: normal;
            font-style: normal;
        }

        @page {
            margin: 120px 35px 95px 35px;
        }

        body {
            font-family: Courier, sans-serif;
            font-size: 11px;
            color: #222;
            position: relative;
        }

        .watermark {
            position: fixed;
            top: 30%;
            left: 12%;
            width: 75%;
            opacity: 0.055;
            z-index: -1;
            text-align: center;
        }

        .watermark img {
            width: 420px;
        }

        header {
            position: fixed;
            top: -95px;
            left: 0;
            right: 0;
            height: 90px;
            border-bottom: 2px solid {{ $primaryColor }};
        }

        .header-table {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
        }

        .header-table td {
            vertical-align: middle;
        }

        .header-left {
            width: 230px;
            text-align: left;
        }

        .header-center {
            text-align: center;
            width: auto;
        }

        .header-right {
            width: 230px;
            text-align: right;
            font-size: 10px;
            line-height: 1.5;
            color: #374151;
        }

        .logo {
            width: 145px;
            max-height: 75px;
            object-fit: contain;
        }

        .company-title {
            font-size: 22px;
            font-weight: 700;
            color: {{ $primaryColor }};
            margin-bottom: 2px;
            text-align: center;
            line-height: 1.15;
        }

        .tagline {
            font-size: 11px;
            color: #4b5563;
            font-style: italic;
            text-align: center;
            line-height: 1.3;
        }



        footer {
            position: fixed;
            bottom: -72px;
            left: 0;
            right: 0;
            height: 62px;
            border-top: 1px solid #d1d5db;
            font-size: 10px;
            color: #4b5563;
        }

        .footer-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }

        .footer-left {
            text-align: left;
            width: 33%;
        }

        .footer-center {
            text-align: center;
            width: 34%;
        }

        .footer-right {
            text-align: right;
            width: 33%;
        }

        .small-muted {
            color: #6b7280;
            font-size: 9px;
        }

        .report-title {
            margin-top: 5px;
            margin-bottom: 12px;
        }

        .report-title h1 {
            font-size: 18px;
            margin: 0 0 4px 0;
            color: #111827;
        }

        .report-title p {
            margin: 0;
            color: {{ $primaryColor }};
            font-size: 10px;
        }

        .meta-grid {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 14px;
        }

        .meta-grid td {
            vertical-align: top;
            padding: 0;
        }

        .meta-card {
            border: 1px solid #dbe4d3;
            border-radius: 10px;
            background: #fbfdf9;
            padding: 11px 12px;
            min-height: 88px;
        }

        .meta-card-dark {
            background: {{ $primaryColor }};
            color: #ffffff;
            border-color: {{ $primaryColor }};
        }

        .meta-title {
            font-size: 10px;
            font-weight: bold;
            color: {{ $secondaryColor }};
            text-transform: uppercase;
            letter-spacing: .45px;
            margin-bottom: 8px;
        }

        .meta-card-dark .meta-title {
            color: #d1fae5;
        }

        .meta-main {
            font-size: 15px;
            font-weight: bold;
            color: #111827;
            margin-bottom: 4px;
        }

        .meta-card-dark .meta-main {
            color: #ffffff;
        }

        .meta-line {
            font-size: 10px;
            color: #4b5563;
            line-height: 1.55;
        }

        .meta-card-dark .meta-line {
            color: #e5e7eb;
        }

        .kpi-table {
            width: 100%;
            border-collapse: collapse;
            margin: 12px 0 16px 0;
        }

        .kpi-table td {
            padding: 0;
            vertical-align: top;
        }

        .kpi {
            border-radius: 10px;
            border: 1px solid #dbe4d3;
            background: #ffffff;
            padding: 10px 12px;
            min-height: 58px;
        }

        .kpi-label {
            font-size: 9px;
            color: #6b7280;
            text-transform: uppercase;
            letter-spacing: .45px;
            font-weight: bold;
        }

        .kpi-value {
            margin-top: 5px;
            font-size: 15px;
            font-weight: bold;
            color: #111827;
        }

        .kpi-value-success {
            color: {{ $successColor }};
        }

        .kpi-value-danger {
            color: {{ $dangerColor }};
        }

        .kpi-foot {
            margin-top: 4px;
            font-size: 9px;
            color: #6b7280;
        }

        .section-heading {
            margin-top: 18px;
            margin-bottom: 8px;
            padding: 8px 10px;
            background: #f3f7ef;
            border-left: 4px solid {{ $primaryColor }};
            color: #111827;
            font-size: 12px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: .35px;
        }

        table.report {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }

        table.report thead th {
            background: {{ $primaryColor }};
            border: 1px solid {{ $primaryColor }};
            color: #ffffff;
            padding: 9px 7px;
            font-size: 9px;
            text-align: left;
            text-transform: uppercase;
            letter-spacing: .25px;
        }

        table.report tbody td {
            border: 1px solid #e5e7eb;
            padding: 7px;
            vertical-align: top;
            font-size: 10px;
        }

        table.report tbody tr:nth-child(even) {
            background: #fafafa;
        }

        .right {
            text-align: right;
        }

        .center {
            text-align: center;
        }

        .status-badge {
            display: inline-block;
            padding: 3px 7px;
            border-radius: 999px;
            font-size: 9px;
            font-weight: bold;
            color: #ffffff;
            text-transform: uppercase;
        }

        .status-success {
            background: {{ $successColor }};
        }

        .status-warning {
            background: {{ $accentColor }};
        }

        .status-danger {
            background: {{ $dangerColor }};
        }

        .status-muted {
            background: #6b7280;
        }

        .ageing-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
            margin-bottom: 14px;
        }

        .ageing-table th {
            background: #f3f4f6;
            color: #111827;
            padding: 8px;
            font-size: 9px;
            text-transform: uppercase;
            border: 1px solid #e5e7eb;
        }

        .ageing-table td {
            padding: 8px;
            border: 1px solid #e5e7eb;
            font-size: 10px;
            text-align: right;
        }

        .ageing-current {
            color: {{ $successColor }};
            font-weight: bold;
        }

        .ageing-warning {
            color: {{ $accentColor }};
            font-weight: bold;
        }

        .ageing-danger {
            color: {{ $dangerColor }};
            font-weight: bold;
        }

        .summary-wrap {
            margin-top: 18px;
            width: 100%;
            border-collapse: collapse;
        }

        .summary-box {
            border: 1px solid #dbe4d3;
            border-radius: 10px;
            background: #fbfdf9;
            padding: 12px;
        }

        .summary-table {
            width: 100%;
            border-collapse: collapse;
        }

        .summary-table td {
            padding: 6px 4px;
            border-bottom: 1px solid #e5e7eb;
            font-size: 10px;
        }

        .summary-table tr:last-child td {
            border-bottom: none;
        }

        .summary-label {
            color: #374151;
            font-weight: bold;
        }

        .summary-value {
            text-align: right;
            font-weight: bold;
        }

        .balance-due {
            font-size: 14px;
            color: {{ $dangerColor }};
        }

        .balance-clear {
            font-size: 14px;
            color: {{ $successColor }};
        }

        .section-block {
            margin-top: 28px;
        }

        .signature-table {
            width: 100%;
            border-collapse: collapse;
        }

        .signature-table td {
            vertical-align: top;
        }

        .signature-card {
            border: 1px solid #dbe4d3;
            border-radius: 10px;
            padding: 12px 14px;
            background: #fbfdf9;
            min-height: 118px;
        }

        .signature-card-authorized {
            border: 1px solid #cfe3bf;
            background: #f8fff2;
        }

        .signature-card-title {
            font-size: 11px;
            font-weight: bold;
            color: {{ $secondaryColor }};
            margin-bottom: 10px;
            text-transform: uppercase;
            letter-spacing: 0.4px;
        }

        .signature-name {
            font-size: 13px;
            font-weight: bold;
            color: #111827;
            margin-bottom: 4px;
        }

        .signature-meta {
            font-size: 9px;
            color: #6b7280;
            margin-bottom: 12px;
        }

        .signature-line {
            border-top: 1px solid #4b5563;
            margin-top: 18px;
            padding-top: 6px;
        }

        .signature-footer {
            font-size: 9px;
            color: #6b7280;
            margin-top: 4px;
        }

        .signature-handwritten {
            font-family: "ChopinScript" !important;
            font-size: 16px;
            color: {{ $successColor }};
            letter-spacing: 1px;
        }

        .stamp-wrap {
            padding-top: 4px;
            text-align: center;
        }

        .stamp-circle {
            width: 110px;
            height: 110px;
            margin: 0 auto 8px auto;
            border: 1px dashed {{ $primaryColor }};
            border-radius: 50%;
            display: table;
        }

        .stamp-text {
            display: table-cell;
            vertical-align: middle;
            text-align: center;
            font-size: 12px;
            font-weight: bold;
            color: {{ $primaryColor }};
            line-height: 1.4;
        }

        .stamp-caption {
            font-size: 9px;
            color: #6b7280;
            text-align: center;
        }

        .qr-box {
            text-align: center;
        }

        .qr-image-wrap {
            width: 104px;
            height: 104px;
            margin: 4px auto 8px auto;
            padding: 4px;
            border: 2px solid {{ $primaryColor }};
            background: #ffffff;
            border-radius: 8px;
        }

        .qr-image {
            width: 90px;
            height: 90px;
            display: block;
            margin: 0 auto;
        }

        .qr-caption {
            font-size: 8px;
            color: #6b7280;
            margin-top: 6px;
            line-height: 1.4;
        }

        .qr-fallback {
            width: 104px;
            height: 104px;
            margin: 4px auto 8px auto;
            border: 1px solid #999;
            border-radius: 8px;
            font-size: 9px;
            display: table;
            background: #ffffff;
        }

        .qr-fallback span {
            display: table-cell;
            vertical-align: middle;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="watermark">
        @if ($logoBase64)
            <img src="{{ $logoBase64 }}" alt="Watermark">
        @endif
    </div>

    <header>
        <table class="header-table">
            <tr>
                <td class="header-left">
                    @if ($logoBase64)
                        <img src="{{ $logoBase64 }}" class="logo" alt="Logo">
                    @endif
                </td>

                <td class="header-center">
                    <div class="company-title">{{ $farmName }}</div>
                    <div class="tagline">{{ $farmTagline }}</div>
                </td>

                <td class="header-right">
                    <strong>Phone:</strong> {{ $farmPhone }}<br>
                    <strong>Email:</strong> {{ $farmEmail }}<br>
                    <strong>County:</strong> {{ $farmCounty }}
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table class="footer-table">
            <tr>
                <td class="footer-left">
                    Printed on {{ $eatNow->format('d M Y, H:i') }} EAT
                </td>
                <td class="footer-center">
                    Supplier Statement
                </td>
                <td class="footer-right">
                    Created by {{ $generatedByName }} ({{ $generatedByRole }})
                </td>
            </tr>
            <tr>
                <td colspan="3" class="footer-center small-muted">
                    {{ $farmName }} - {{ $farmCounty }} - {{ $farmPhone }} - {{ $farmEmail }}
                </td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="report-title">
            <h1>Supplier Statement</h1>
            <p>Period: {{ pdfDate($from) }} to {{ pdfDate($to) }} | Supplier: {{ $supplier->company_name ?? '-' }}
            </p>
        </div>

        <table class="meta-grid">
            <tr>
                <td style="width: 50%; padding-right: 8px;">
                    <div class="meta-card">
                        <div class="meta-title">Supplier Profile</div>
                        <div class="meta-main">{{ $supplier->company_name ?? '-' }}</div>
                        <div class="meta-line">
                            Contact: {{ $supplier->contact_person ?? '-' }}<br>
                            Phone: {{ $supplier->phone_primary ?? ($supplier->phone ?? '-') }}<br>
                            Email: {{ $supplier->email ?? '-' }}<br>
                            KRA PIN: {{ $supplier->kra_pin ?? '-' }}
                        </div>
                    </div>
                </td>

                <td style="width: 50%; padding-left: 8px;">
                    <div class="meta-card meta-card-dark">
                        <div class="meta-title">Statement Summary</div>
                        <div class="meta-main">{{ pdfMoney($balance) }}</div>
                        <div class="meta-line">
                            Outstanding supplier balance<br>
                            {{ $invoiceCount }} invoice(s) | {{ $paymentCount }} payment(s)<br>
                            Generated: {{ $eatNow->format('d M Y, H:i') }} EAT
                        </div>
                    </div>
                </td>
            </tr>
        </table>

        <table class="kpi-table">
            <tr>
                <td style="width: 25%; padding-right: 6px;">
                    <div class="kpi">
                        <div class="kpi-label">Invoice Value</div>
                        <div class="kpi-value">{{ pdfMoney($invoiceTotal) }}</div>
                        <div class="kpi-foot">Total supplier invoices</div>
                    </div>
                </td>

                <td style="width: 25%; padding: 0 6px;">
                    <div class="kpi">
                        <div class="kpi-label">Payments</div>
                        <div class="kpi-value kpi-value-success">{{ pdfMoney($paymentTotal) }}</div>
                        <div class="kpi-foot">Successful payments</div>
                    </div>
                </td>

                <td style="width: 25%; padding: 0 6px;">
                    <div class="kpi">
                        <div class="kpi-label">Balance</div>
                        <div class="kpi-value {{ $balance > 0 ? 'kpi-value-danger' : 'kpi-value-success' }}">
                            {{ pdfMoney($balance) }}
                        </div>
                        <div class="kpi-foot">Amount owed to supplier</div>
                    </div>
                </td>

                <td style="width: 25%; padding-left: 6px;">
                    <div class="kpi">
                        <div class="kpi-label">Status</div>
                        <div class="kpi-value">
                            <span class="status-badge {{ $balanceClass }}">
                                {{ $balance > 0 ? 'Payable' : 'Cleared' }}
                            </span>
                        </div>
                        <div class="kpi-foot">Accounts payable position</div>
                    </div>
                </td>
            </tr>
        </table>

        <div class="section-heading">Accounts Payable Ageing</div>

        <table class="ageing-table">
            <thead>
                <tr>
                    <th>Current / Not Due</th>
                    <th>0 - 7 Days</th>
                    <th>8 - 30 Days</th>
                    <th>31 - 60 Days</th>
                    <th>60+ Days</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="ageing-current">{{ pdfMoney($currentBucket) }}</td>
                    <td class="ageing-warning">{{ pdfMoney($bucket0to7) }}</td>
                    <td class="ageing-warning">{{ pdfMoney($bucket8to30) }}</td>
                    <td class="ageing-danger">{{ pdfMoney($bucket31to60) }}</td>
                    <td class="ageing-danger">{{ pdfMoney($bucket60Plus) }}</td>
                </tr>
            </tbody>
        </table>

        <div class="section-heading">Invoices & Purchase Orders</div>

        <table class="report">
            <thead>
                <tr>
                    <th width="10%">Date</th>
                    <th width="16%">Invoice</th>
                    <th width="16%">PO</th>
                    <th width="12%">Due</th>
                    <th width="10%">Payment</th>
                    <th width="14%" class="right">Grand Total</th>
                    <th width="11%" class="right">Paid</th>
                    <th width="11%" class="right">Balance</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($purchaseOrders as $order)
                    @php
                        $paymentStatus = $order->payment_status ?? 'unpaid';

                        $statusClass = match ($paymentStatus) {
                            'paid' => 'status-success',
                            'partial' => 'status-warning',
                            default => 'status-danger',
                        };
                    @endphp

                    <tr>
                        <td>{{ pdfDate($order->order_date) }}</td>
                        <td>{{ $order->invoice_number ?? '-' }}</td>
                        <td>{{ $order->purchase_order_number ?? '-' }}</td>
                        <td>{{ pdfDate($order->due_date) }}</td>
                        <td>
                            <span class="status-badge {{ $statusClass }}">
                                {{ str($paymentStatus)->title() }}
                            </span>
                        </td>
                        <td class="right">{{ pdfMoney($order->grand_total) }}</td>
                        <td class="right">{{ pdfMoney($order->amount_paid) }}</td>
                        <td class="right">{{ pdfMoney($order->balance_due) }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="8" class="center">No invoices found in this period.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        <div class="section-heading">Supplier Payments</div>

        <table class="report">
            <thead>
                <tr>
                    <th width="10%">Date</th>
                    <th width="18%">Payment No.</th>
                    <th width="16%">Invoice</th>
                    <th width="15%">Method</th>
                    <th width="18%">Reference</th>
                    <th width="10%">Status</th>
                    <th width="13%" class="right">Amount</th>
                </tr>
            </thead>

            <tbody>
                @forelse ($payments as $payment)
                    @php
                        $reference =
                            $payment->mpesa_reference ?: ($payment->bank_reference ?: ($payment->cheque_number ?: '-'));

                        $paymentStatusClass =
                            ($payment->status ?? null) === 'successful' ? 'status-success' : 'status-warning';
                    @endphp

                    <tr>
                        <td>{{ pdfDate($payment->payment_date) }}</td>
                        <td>{{ $payment->payment_number ?? '-' }}</td>
                        <td>{{ $payment->purchaseOrder?->invoice_number ?? '-' }}</td>
                        <td>{{ str($payment->payment_method ?? '-')->replace('_', ' ')->title() }}</td>
                        <td>{{ $reference }}</td>
                        <td>
                            <span class="status-badge {{ $paymentStatusClass }}">
                                {{ str($payment->status ?? '-')->title() }}
                            </span>
                        </td>
                        <td class="right">{{ pdfMoney($payment->amount) }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7" class="center">No payments found in this period.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        <table class="summary-wrap">
            <tr>
                <td style="width: 55%; padding-right: 12px; vertical-align: top;">
                    <div class="summary-box">
                        <strong>Statement Note</strong><br>
                        <span class="small-muted">
                            This statement summarizes supplier invoices, purchase orders, payments, and the outstanding
                            balance payable to the supplier for the selected period.
                        </span>
                    </div>
                </td>

                <td style="width: 45%; vertical-align: top;">
                    <div class="summary-box">
                        <table class="summary-table">
                            <tr>
                                <td class="summary-label">Total Invoices</td>
                                <td class="summary-value">{{ pdfMoney($invoiceTotal) }}</td>
                            </tr>
                            <tr>
                                <td class="summary-label">Total Payments</td>
                                <td class="summary-value">{{ pdfMoney($paymentTotal) }}</td>
                            </tr>
                            <tr>
                                <td class="summary-label">Balance Due</td>
                                <td class="summary-value {{ $balance > 0 ? 'balance-due' : 'balance-clear' }}">
                                    {{ pdfMoney($balance) }}
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>

        <div class="section-block">
            <table class="signature-table">
                <tr>
                    <td style="width: 26%; padding-top: 16px; padding-right: 8px;">
                        <div class="signature-card">
                            <div class="signature-card-title">Prepared By</div>
                            <div class="signature-name">{{ $generatedByName }}</div>
                            <div class="signature-meta">{{ $generatedByRole }}</div>
                            <div class="signature-line"></div>
                            <div class="signature-footer">
                                Generated on {{ $eatNow->format('d M Y, H:i') }} EAT
                            </div>
                        </div>
                    </td>

                    <td style="width: 28%; padding-top: 16px; padding-right: 8px;">
                        <div class="signature-card signature-card-authorized">
                            <div class="signature-card-title">Finance Approval</div>

                            <div class="signature-handwritten">
                                Verified!
                            </div>

                            <div class="signature-meta">
                                Verification Date: {{ $eatNow->format('d M Y, H:i') }} EAT
                            </div>

                            <div class="signature-line"></div>

                            <div class="signature-footer">
                                {{ $farmName }} Procurement / Finance
                            </div>
                        </div>
                    </td>

                    <td style="width: 22%; padding-top: 16px; padding-right: 8px;">
                        <div class="stamp-wrap">
                            <div class="stamp-circle">
                                <div class="stamp-text">OFFICIAL<br>STAMP</div>
                            </div>

                            <div class="stamp-caption">{{ $farmName }} Stamp</div>
                        </div>
                    </td>

                    <td style="width: 24%; padding-top: 16px;">
                        <div class="qr-box">
                            @if (!empty($qrPng))
                                <div class="qr-image-wrap">
                                    <img src="data:image/png;base64,{{ $qrPng }}" alt="QR Code"
                                        class="qr-image">
                                </div>
                            @else
                                <div class="qr-fallback">
                                    <span>QR not available</span>
                                </div>
                            @endif

                            <div class="qr-caption">
                                Scan to verify statement metadata
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </main>

    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
                $font = $fontMetrics->getFont('Helvetica', 'normal');
                $size = 9;

                $text = "Page {$pageNumber} of {$pageCount}";
                $width = $fontMetrics->getTextWidth($text, $font, $size);

                $x = 297.5 - ($width / 2);
                $y = 805;

                $canvas->text($x, $y, $text, $font, $size, [0.42, 0.45, 0.50]);
            });
        }
    </script>
</body>

</html>
