@php
    if (! function_exists('accountingPdfSetting')) {
        function accountingPdfSetting(string $key, mixed $default = null): mixed
        {
            return function_exists('setting') ? setting($key, $default) : $default;
        }
    }

    if (! function_exists('accountingPdfImageBase64')) {
        function accountingPdfImageBase64(?string $path): ?string
        {
            if (! $path) {
                return null;
            }

            $cleanPath = trim($path);
            $cleanPath = ltrim($cleanPath, '/');
            $cleanPath = preg_replace('#^storage/#', '', $cleanPath);

            $possiblePaths = [
                storage_path('app/public/' . $cleanPath),
                public_path('storage/' . $cleanPath),
                public_path($cleanPath),
            ];

            foreach ($possiblePaths as $fullPath) {
                if (is_file($fullPath)) {
                    $extension = strtolower(pathinfo($fullPath, PATHINFO_EXTENSION));
                    $mime = match ($extension) {
                        'jpg', 'jpeg' => 'image/jpeg',
                        'png' => 'image/png',
                        'gif' => 'image/gif',
                        'webp' => 'image/webp',
                        'svg' => 'image/svg+xml',
                        'ico' => 'image/x-icon',
                        default => 'image/png',
                    };

                    return 'data:' . $mime . ';base64,' . base64_encode(file_get_contents($fullPath));
                }
            }

            return null;
        }
    }

    $eatNow = now('Africa/Nairobi');
    $farmName = accountingPdfSetting('farm.name', 'Lelekwe Farms');
    $farmTagline = accountingPdfSetting('farm.tagline', 'Nurturing Nature, Feeding The Future');
    $farmPhone = accountingPdfSetting('farm.phone', '+254 743 487 186');
    $farmEmail = accountingPdfSetting('farm.email', 'jambo@lelekwefarms.co.ke');
    $farmCounty = accountingPdfSetting('farm.county', 'Nakuru County');

    $primaryColor = trim(accountingPdfSetting('theme.primary', '#014a12'));
    $secondaryColor = trim(accountingPdfSetting('theme.secondary', '#14532d'));
    $accentColor = trim(accountingPdfSetting('theme.accent', '#b7791f'));
    $successColor = trim(accountingPdfSetting('theme.success', '#16a34a'));

    $logoBase64 = accountingPdfImageBase64(accountingPdfSetting('branding.logo_light'));
    $generatedByName = $generatedBy->name ?? 'System';
    $generatedByRole = $generatedByRole ?? 'User';
    $recordCount = $recordCount ?? collect($rows ?? [])->count();
    $isPdf = $isPdf ?? false;

    $verificationText = $farmName
        . ' Accounting Report | Report: ' . $reportTitle
        . ' | Period: ' . $periodLabel
        . ' | Generated by: ' . $generatedByName . ' (' . $generatedByRole . ')'
        . ' | Date: ' . $eatNow->format('Y-m-d H:i:s') . ' EAT'
        . ' | Total Records: ' . $recordCount;

    $qrPng = null;
    if (class_exists(\SimpleSoftwareIO\QrCode\Facades\QrCode::class)) {
        try {
            $qrPng = base64_encode(
                \SimpleSoftwareIO\QrCode\Facades\QrCode::format('png')
                    ->size(110)
                    ->margin(1)
                    ->generate($verificationText)
            );
        } catch (\Throwable $e) {
            $qrPng = null;
        }
    }
@endphp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $reportTitle }}</title>
    <style>
        @font-face {
            font-family: "ChopinScript";
            src: url("{{ public_path('fonts/ChopinScript.ttf') }}") format("truetype");
            font-weight: normal;
            font-style: normal;
        }

        @page { margin: 120px 35px 96px 35px; }

        body {
            font-family: Courier, monospace;
            font-size: 10.5px;
            color: #1f2937;
            position: relative;
        }

        .watermark {
            position: fixed;
            top: 29%;
            left: 13%;
            width: 74%;
            opacity: 0.052;
            z-index: -1;
            text-align: center;
        }

        .watermark img { width: 420px; }

        header {
            position: fixed;
            top: -96px;
            left: 0;
            right: 0;
            height: 90px;
            border-bottom: 2px solid {{ $primaryColor }};
        }

        .header-table, .footer-table, .signature-table { width: 100%; border-collapse: collapse; }
        .header-table td { vertical-align: middle; }
        .header-left { text-align: left; }
        .header-center { text-align: center; }
        .header-right { text-align: right; font-size: 9.5px; line-height: 1.45; color: #374151; }
        .logo { width: 170px; max-height: 75px; object-fit: contain; }
        .company-title { font-size: 21px; font-weight: 800; color: {{ $primaryColor }}; margin-bottom: 2px; text-align: center; }
        .tagline { font-size: 10px; color: #4b5563; font-style: italic; text-align: center; }

        footer {
            position: fixed;
            bottom: -72px;
            left: 0;
            right: 0;
            height: 62px;
            border-top: 1px solid #d1d5db;
            font-size: 9.5px;
            color: #4b5563;
        }

        .footer-table { margin-top: 8px; }
        .footer-left { text-align: left; width: 33%; }
        .footer-center { text-align: center; width: 34%; }
        .footer-right { text-align: right; width: 33%; }
        .small-muted { color: #6b7280; font-size: 8.5px; }

        .screen-actions { text-align: right; margin-bottom: 12px; }
        .screen-actions button { border: 0; background: {{ $primaryColor }}; color: #fff; border-radius: 7px; padding: 8px 12px; font-weight: 700; cursor: pointer; }
        @media print { .screen-actions { display: none; } }

        .report-band {
            margin: 0 0 12px 0;
            padding: 15px 16px;
            color: #fff;
            border-radius: 8px;
            background: linear-gradient(135deg, {{ $primaryColor }} 0%, {{ $secondaryColor }} 62%, #052e16 100%);
        }

        .report-band-table { width: 100%; border-collapse: collapse; }
        .report-band h1 { font-size: 20px; margin: 0 0 5px 0; color: #fff; }
        .report-band p { margin: 0; color: rgba(255,255,255,.83); font-size: 10px; line-height: 1.5; }
        .report-band .period-box { border: 1px solid rgba(255,255,255,.22); padding: 8px 10px; text-align: right; width: 230px; }
        .period-label { color: rgba(255,255,255,.70); font-size: 8px; text-transform: uppercase; letter-spacing: .4px; }
        .period-value { margin-top: 3px; font-size: 12px; font-weight: bold; }

        .executive-brief { width: 100%; border-collapse: collapse; margin: 10px 0 12px 0; }
        .executive-brief td { border: 1px solid #dbe4d3; padding: 9px 10px; background: #fbfdf9; vertical-align: top; }
        .brief-label { font-size: 8.5px; text-transform: uppercase; letter-spacing: .35px; color: {{ $primaryColor }}; font-weight: bold; margin-bottom: 4px; }
        .brief-text { font-size: 9.5px; line-height: 1.45; color: #374151; }

        .summary-table { width: 100%; border-collapse: collapse; margin: 10px 0 12px 0; }
        .summary-table td { border: 1px solid #dbe4d3; background: #fbfdf9; padding: 8px; }
        .summary-label { color: #6b7280; font-size: 8.8px; text-transform: uppercase; letter-spacing: .3px; }
        .summary-value { margin-top: 3px; font-size: 13px; font-weight: 800; color: #111827; }

        table.report { width: 100%; border-collapse: collapse; margin-top: 10px; }
        table.report thead th { background: {{ $primaryColor }}; border: 1px solid {{ $primaryColor }}; color: #fff; padding: 8px 7px; font-size: 9.2px; text-align: left; }
        table.report tbody td { border: 1px solid #e5e7eb; padding: 6.5px 7px; vertical-align: top; }
        table.report tbody tr:nth-child(even) { background: #fafafa; }
        table.report tfoot td { border: 1px solid #d1d5db; padding: 8px 7px; font-weight: 800; background: #f3f4f6; }
        .num { text-align: right; white-space: nowrap; }

        .section-block { margin-top: 26px; }
        .signature-table td { vertical-align: top; }
        .signature-card { border: 1px solid #dbe4d3; border-radius: 10px; padding: 12px 14px; background: #fbfdf9; min-height: 112px; }
        .signature-card-authorized { border: 1px solid #cfe3bf; background: #f8fff2; }
        .signature-card-title { font-size: 10.5px; font-weight: bold; color: {{ $secondaryColor }}; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.4px; }
        .signature-name { font-size: 12.5px; font-weight: bold; color: #111827; margin-bottom: 4px; }
        .signature-meta { font-size: 8.8px; color: #6b7280; margin-bottom: 12px; }
        .signature-line { border-top: 1px solid #4b5563; margin-top: 18px; padding-top: 6px; }
        .signature-footer { font-size: 8.8px; color: #6b7280; margin-top: 4px; }
        .signature-handwritten { font-family: "ChopinScript" !important; font-size: 24px; color: {{ $successColor }}; letter-spacing: 1px; }
        .stamp-wrap { padding-top: 4px; text-align: center; }
        .stamp-circle { width: 104px; height: 104px; margin: 0 auto 8px auto; border: 1px dashed {{ $primaryColor }}; border-radius: 50%; display: table; }
        .stamp-text { display: table-cell; vertical-align: middle; text-align: center; font-size: 11px; font-weight: bold; color: {{ $primaryColor }}; line-height: 1.35; }
        .stamp-caption, .qr-caption { font-size: 8.2px; color: #6b7280; text-align: center; }
        .qr-box { text-align: center; }
        .qr-image-wrap { width: 100px; height: 100px; margin: 4px auto 8px auto; padding: 4px; border: 2px solid {{ $primaryColor }}; background: #fff; border-radius: 8px; }
        .qr-image { width: 88px; height: 88px; display: block; margin: 0 auto; }
        .qr-fallback { width: 100px; height: 100px; margin: 4px auto 8px auto; border: 1px solid #999; border-radius: 8px; font-size: 9px; display: table; background: #fff; }
        .qr-fallback span { display: table-cell; vertical-align: middle; text-align: center; }
    </style>

</head>
<body>
    @if (! $isPdf)
        <div class="screen-actions"><button onclick="window.print()">Print Report</button></div>
    @endif

    <div class="watermark">
        @if ($logoBase64)
            <img src="{{ $logoBase64 }}" alt="Watermark">
        @endif
    </div>

    <header>
        <table class="header-table">
            <tr>
                <td class="header-left" width="120">@if ($logoBase64)<img src="{{ $logoBase64 }}" class="logo" alt="Logo">@endif</td>
                <td class="header-center"><div class="company-title">{{ $farmName }}</div><div class="tagline">{{ $farmTagline }}</div></td>
                <td class="header-right" width="245"><strong>Phone:</strong> {{ $farmPhone }}<br><strong>Email:</strong> {{ $farmEmail }}<br><strong>County:</strong> {{ $farmCounty }}</td>
            </tr>
        </table>
    </header>

    <footer>
        <table class="footer-table">
            <tr><td class="footer-left">Printed on {{ $eatNow->format('d M Y, H:i') }} EAT</td><td class="footer-center">{{ $reportTitle }}</td><td class="footer-right">Created by {{ $generatedByName }} ({{ $generatedByRole }})</td></tr>
            <tr><td colspan="3" class="footer-center small-muted">{{ $farmName }} • {{ $farmCounty }} • {{ $farmPhone }} • {{ $farmEmail }}</td></tr>
        </table>
    </footer>

    <main>
        <div class="report-band">
            <table class="report-band-table">
                <tr>
                    <td>
                        <h1>{{ $reportTitle }}</h1>
                        <p>{{ $reportSubtitle }}<br>Total Records: {{ $recordCount }}</p>
                    </td>
                    <td class="period-box">
                        <div class="period-label">Reporting Period</div>
                        <div class="period-value">{{ $periodLabel }}</div>
                    </td>
                </tr>
            </table>
        </div>

        <table class="executive-brief">
            <tr>
                <td width="50%"><div class="brief-label">Executive interpretation</div><div class="brief-text">{{ $decisionNote ?? 'Review this report as part of the farm’s management reporting and director decision-making process.' }}</div></td>
                <td width="50%"><div class="brief-label">Recommended control action</div><div class="brief-text">{{ $controlNote ?? 'Validate figures against source documents, approvals and posted accounting entries before final circulation.' }}</div></td>
            </tr>
        </table>

        <table class="summary-table"><tr>
            @foreach ($summary as $label => $value)
                <td><div class="summary-label">{{ $label }}</div><div class="summary-value">{{ is_numeric($value) && ! in_array($label, ['Accounts', 'Movements', 'Records'], true) ? 'KES ' . number_format((float) $value, 2) : (is_numeric($value) ? number_format((float) $value) : $value) }}</div></td>
            @endforeach
        </tr></table>

        <table class="report">
            <thead><tr>@foreach ($columns as $column)<th>{{ $column }}</th>@endforeach</tr></thead>
            <tbody>
                @forelse ($rows as $row)
                    <tr>@foreach ($row as $cell)<td class="{{ $loop->remaining <= 2 ? 'num' : '' }}">{{ $cell }}</td>@endforeach</tr>
                @empty
                    <tr><td colspan="{{ count($columns) }}" style="text-align:center; color:#6b7280; padding:20px;">No records found.</td></tr>
                @endforelse
            </tbody>
            @if (! empty($totals))
                <tfoot><tr>@foreach ($totals as $cell)<td class="{{ $loop->remaining <= 2 ? 'num' : '' }}">{{ $cell }}</td>@endforeach</tr></tfoot>
            @endif
        </table>

        <div class="section-block">
            <table class="signature-table">
                <tr>
                    <td style="width: 26%; padding-top: 16px; padding-right: 8px;"><div class="signature-card"><div class="signature-card-title">Prepared By</div><div class="signature-name">{{ $generatedByName }}</div><div class="signature-meta">{{ $generatedByRole }}</div><div class="signature-line"></div><div class="signature-footer">Generated on {{ $eatNow->format('d M Y, H:i') }} EAT</div></div></td>
                    <td style="width: 28%; padding-top: 16px; padding-right: 8px;"><div class="signature-card signature-card-authorized"><div class="signature-card-title">Authorized Signature</div><div class="signature-handwritten">Digitally Approved!</div><div class="signature-meta">Signature Date: {{ $eatNow->format('d M Y, H:i') }} EAT</div><div class="signature-line"></div><div class="signature-footer">{{ $farmName }} Management Approval</div></div></td>
                    <td style="width: 22%; padding-top: 16px; padding-right: 8px;"><div class="stamp-wrap"><div class="stamp-circle"><div class="stamp-text">OFFICIAL<br>STAMP</div></div><div class="stamp-caption">{{ $farmName }} Stamp</div></div></td>
                    <td style="width: 24%; padding-top: 16px;"><div class="qr-box">@if (! empty($qrPng))<div class="qr-image-wrap"><img src="data:image/png;base64,{{ $qrPng }}" alt="QR Code" class="qr-image"></div>@else<div class="qr-fallback"><span>QR not available</span></div>@endif<div class="qr-caption">Scan to verify report metadata</div></div></td>
                </tr>
            </table>
        </div>
    </main>

    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
                $font = $fontMetrics->getFont('Helvetica', 'normal');
                $size = 9;
                $text = "Page {$pageNumber} of {$pageCount}";
                $width = $fontMetrics->getTextWidth($text, $font, $size);
                $canvas->text(420 - ($width / 2), 565, $text, $font, $size, [0.42, 0.45, 0.50]);
            });
        }
    </script>


<style>
    /*
    |--------------------------------------------------------------------------
    | LELEKWE_ACCOUNTING_PDF_VISIBILITY_FINAL_FIX
    |--------------------------------------------------------------------------
    | Generated accounting reports only.
    | Forces report text to black and Courier.
    | Keeps signature handwritten text in the farm primary color.
    */

    html,
    body,
    main,
    section,
    article {
        font-family: Courier, "Courier New", monospace !important;
        color: #000000 !important;
        background: #ffffff !important;
    }

    body * {
        font-family: Courier, "Courier New", monospace !important;
        color: #000000 !important;
    }

    /*
     * Fix the white/invisible report intro/header text.
     */
    .report-title,
    .report-title *,
    .pdf-report-title,
    .pdf-report-title *,
    .accounting-report-title,
    .accounting-report-title *,
    .accounting-pdf-title,
    .accounting-pdf-title *,
    .report-hero,
    .report-hero *,
    .pdf-hero,
    .pdf-hero *,
    .accounting-report-hero,
    .accounting-report-hero *,
    .accounting-pdf-hero,
    .accounting-pdf-hero *,
    .report-summary,
    .report-summary *,
    .pdf-summary,
    .pdf-summary *,
    .report-meta,
    .report-meta *,
    .pdf-meta,
    .pdf-meta *,
    .report-period,
    .report-period *,
    .pdf-period,
    .pdf-period *,
    .summary-card,
    .summary-card *,
    .period-card,
    .period-card *,
    .meta-card,
    .meta-card *,
    .control-card,
    .control-card *,
    .director-note,
    .director-note *,
    .executive-note,
    .executive-note *,
    .report-description,
    .pdf-description,
    .report-subtitle,
    .pdf-subtitle,
    .report-caption,
    .pdf-caption,
    .report-kicker,
    .pdf-kicker,
    .meta-label,
    .summary-label,
    .period-label,
    .meta-value,
    .summary-value,
    .period-value {
        color: #000000 !important;
        font-family: Courier, "Courier New", monospace !important;
    }

    .report-title,
    .pdf-report-title,
    .accounting-report-title,
    .accounting-pdf-title,
    .report-hero,
    .pdf-hero,
    .accounting-report-hero,
    .accounting-pdf-hero,
    .report-summary,
    .pdf-summary,
    .report-meta,
    .pdf-meta,
    .report-period,
    .pdf-period,
    .summary-card,
    .period-card,
    .meta-card,
    .control-card,
    .director-note,
    .executive-note {
        background: #ffffff !important;
        border-color: #000000 !important;
    }

    /*
     * Catch Tailwind/utility classes that may be making PDF text white.
     */
    .text-white,
    .text-gray-50,
    .text-slate-50,
    .text-zinc-50,
    .text-neutral-50,
    .text-stone-50,
    .text-gray-100,
    .text-slate-100,
    .text-emerald-50,
    .text-green-50,
    .text-lime-50 {
        color: #000000 !important;
    }

    /*
     * Headings and labels.
     */
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    p,
    span,
    small,
    strong,
    b,
    div {
        color: #000000 !important;
    }

    .report-title h1,
    .pdf-report-title h1,
    .accounting-report-title h1,
    .accounting-pdf-title h1,
    .report-hero h1,
    .pdf-hero h1 {
        color: #000000 !important;
        font-weight: 800 !important;
    }

    .meta-label,
    .summary-label,
    .period-label,
    .report-period-label,
    .pdf-period-label,
    .report-kpi-label,
    .pdf-kpi-label {
        color: #000000 !important;
        font-weight: 800 !important;
        text-transform: uppercase !important;
        letter-spacing: .04em !important;
    }

    .meta-value,
    .summary-value,
    .period-value,
    .report-period-value,
    .pdf-period-value,
    .report-kpi-value,
    .pdf-kpi-value {
        color: #000000 !important;
        font-weight: 800 !important;
    }

    /*
     * Table content like 000 — Assets, Total, etc.
     */
    table,
    thead,
    tbody,
    tfoot,
    tr,
    th,
    td,
    table *,
    .report-table,
    .report-table *,
    .accounting-table,
    .accounting-table *,
    table.report,
    table.report * {
        color: #000000 !important;
        font-family: Courier, "Courier New", monospace !important;
    }

    table thead th,
    table.report thead th,
    .report-table thead th,
    .accounting-table thead th {
        color: #000000 !important;
        background: #e5e7eb !important;
        border-color: #000000 !important;
        font-weight: 800 !important;
    }

    .group-row,
    .account-group-row,
    .section-row,
    .total-row,
    .subtotal-row,
    .grand-total-row,
    tr.group-row td,
    tr.account-group-row td,
    tr.section-row td,
    tr.total-row td,
    tr.subtotal-row td,
    tr.grand-total-row td {
        color: #000000 !important;
        background: #f3f4f6 !important;
        border-color: #000000 !important;
        font-weight: 800 !important;
    }

    /*
     * Signature should NOT be black. Use the dynamic farm primary color.
     */
    .signature-handwritten,
    .signature-handwritten *,
    .handwritten,
    .handwritten *,
    .signature-script,
    .signature-script * {
        font-family: "ChopinScript", "ChopinScriptDashboard", cursive !important;
        color: {{ $primaryColor ?? setting('theme.primary', '#14532d') }} !important;
    }
</style>

</body>
</html>
