<?php
    use App\Models\Settings\PaymentSetting;

    if (! function_exists('pdfImageBase64')) {
        function pdfImageBase64(?string $path): ?string
        {
            if (! $path) {
                return null;
            }

            $cleanPath = trim((string) $path);
            $cleanPath = ltrim($cleanPath, '/');
            $cleanPath = preg_replace('#^storage/#', '', $cleanPath);
            $cleanPath = preg_replace('#^public/#', '', $cleanPath);

            $possiblePaths = [
                storage_path('app/public/' . $cleanPath),
                public_path('storage/' . $cleanPath),
                public_path($cleanPath),
            ];

            foreach ($possiblePaths as $fullPath) {
                if (is_file($fullPath)) {
                    $extension = strtolower(pathinfo($fullPath, PATHINFO_EXTENSION));

                    $mime = match ($extension) {
                        'jpg', 'jpeg' => 'image/jpeg',
                        'png' => 'image/png',
                        'gif' => 'image/gif',
                        'webp' => 'image/webp',
                        'svg' => 'image/svg+xml',
                        'ico' => 'image/x-icon',
                        default => 'image/png',
                    };

                    return 'data:' . $mime . ';base64,' . base64_encode(file_get_contents($fullPath));
                }
            }

            return null;
        }
    }

    $paymentSettings = PaymentSetting::current();

    $eatNow = now('Africa/Nairobi');

    $farmName = setting('farm.name', 'Lelekwe Farm Limited');
    $farmTagline = setting('farm.tagline', 'Nurturing Nature, Feeding The Future');
    $farmPhone = setting('farm.phone', '+254 743 487 186');
    $farmEmail = setting('farm.email', 'jambo@lelekwefarm.com');
    $farmCounty = setting('farm.county', 'Nakuru County');
    $farmAddress = setting('farm.address', $farmCounty);

    $primaryColor = trim(setting('theme.primary', '#014a12'));
    $secondaryColor = trim(setting('theme.secondary', '#14532d'));
    $accentColor = trim(setting('theme.accent', '#f59e0b'));
    $successColor = trim(setting('theme.success', '#16a34a'));

    $logoBase64 = pdfImageBase64(setting('branding.logo_light'));

    $signatureBase64 = pdfImageBase64(
        data_get($paymentSettings, 'authorized_signature_image')
        ?: data_get($paymentSettings, 'signature_path')
        ?: data_get($paymentSettings, 'authorized_signature_path')
        ?: setting('branding.signature')
    );

    $stampBase64 = pdfImageBase64(
        data_get($paymentSettings, 'payment_stamp_image')
        ?: data_get($paymentSettings, 'stamp_path')
        ?: data_get($paymentSettings, 'official_stamp_path')
        ?: setting('branding.stamp')
    );

    $generatedByName = $generatedBy?->name ?? 'System';
    $generatedByRole = $generatedByRole ?? 'User';

    $reportTitle = $reportTitle ?? 'Locations Report';
    $reportSubtitle = $reportSubtitle ?? 'Farm location register';

    $totalLocations = $locations->count();
    $activeLocations = $locations->where('is_active', true)->count();
    $defaultLocations = $locations->where('is_default', true)->count();
    $totalAnimals = $locations->sum(fn ($location) => (int) ($location->animals_count ?? 0));

    $verificationText =
        $farmName .
        ' Locations Report | Total Locations: ' .
        $totalLocations .
        ' | Active Locations: ' .
        $activeLocations .
        ' | Total Animals: ' .
        $totalAnimals .
        ' | Generated by: ' .
        $generatedByName .
        ' (' .
        $generatedByRole .
        ')' .
        ' | Date: ' .
        $eatNow->format('Y-m-d H:i:s') .
        ' EAT';

    $qrPng = null;

    if (class_exists(\SimpleSoftwareIO\QrCode\Facades\QrCode::class)) {
        try {
            $qrPng = base64_encode(
                \SimpleSoftwareIO\QrCode\Facades\QrCode::format('png')
                    ->size(115)
                    ->margin(1)
                    ->generate($verificationText)
            );
        } catch (\Throwable) {
            $qrPng = null;
        }
    }
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo e($reportTitle); ?></title>

    <style>
        @page {
            margin: 118px 34px 92px 34px;
        }

        body {
            margin: 0;
            font-family: Courier, "Courier New", monospace;
            font-size: 10px;
            color: #111827;
            background: #ffffff;
            position: relative;
        }

        .watermark {
            position: fixed;
            top: 26%;
            left: 12%;
            width: 76%;
            opacity: 0.035;
            z-index: -10;
            text-align: center;
        }

        .watermark img {
            width: 440px;
        }

        header {
            position: fixed;
            top: -96px;
            left: 0;
            right: 0;
            height: 88px;
            border-bottom: 3px solid <?php echo e($primaryColor); ?>;
        }

        footer {
            position: fixed;
            bottom: -70px;
            left: 0;
            right: 0;
            height: 58px;
            border-top: 1px solid #d1d5db;
            color: #4b5563;
            font-size: 9px;
        }

        .header-table,
        .footer-table,
        .report-title-table,
        .kpi-table,
        .items,
        .signature-table {
            width: 100%;
            border-collapse: collapse;
        }

        .header-table td {
            vertical-align: middle;
        }

        .logo {
            width: 145px;
            max-height: 72px;
            object-fit: contain;
        }

        .company-title {
            text-align: center;
            font-size: 15px;
            font-weight: bold;
            color: <?php echo e($primaryColor); ?>;
            text-transform: uppercase;
            letter-spacing: .4px;
        }

        .tagline {
            text-align: center;
            margin-top: 3px;
            font-size: 9.5px;
            color: #4b5563;
            font-style: italic;
        }

        .header-right {
            width: 230px;
            text-align: right;
            font-size: 9px;
            line-height: 1.55;
        }

        .footer-table {
            margin-top: 7px;
        }

        .footer-left {
            width: 33%;
            text-align: left;
        }

        .footer-center {
            width: 34%;
            text-align: center;
        }

        .footer-right {
            width: 33%;
            text-align: right;
        }

        .small-muted {
            color: #6b7280;
            font-size: 8.5px;
            line-height: 1.35;
        }

        .report-top {
            margin-bottom: 12px;
            border: 1px solid #dbe4d3;
            border-left: 7px solid <?php echo e($primaryColor); ?>;
            background: #fbfdf9;
            padding: 12px 14px;
        }

        .report-title {
            margin: 0;
            color: #111827;
            font-size: 23px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: .7px;
        }

        .report-subtitle {
            margin-top: 4px;
            color: <?php echo e($primaryColor); ?>;
            font-size: 10px;
            font-weight: bold;
            line-height: 1.45;
        }

        .report-total-box {
            text-align: right;
        }

        .report-total-label {
            color: #6b7280;
            font-size: 8.5px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .report-total-value {
            margin-top: 3px;
            color: <?php echo e($primaryColor); ?>;
            font-size: 20px;
            font-weight: bold;
        }

        .kpi-table {
            border-spacing: 8px 0;
            border-collapse: separate;
            margin: 12px 0 14px;
        }

        .kpi-card {
            width: 25%;
            border: 1px solid #dbe4d3;
            border-top: 4px solid <?php echo e($primaryColor); ?>;
            background: #fbfdf9;
            padding: 9px 10px;
            text-align: center;
        }

        .kpi-label {
            color: #6b7280;
            font-size: 8px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .kpi-value {
            margin-top: 4px;
            color: <?php echo e($primaryColor); ?>;
            font-size: 14px;
            font-weight: bold;
        }

        .items {
            margin-top: 10px;
            border-collapse: collapse;
        }

        .items th {
            border: 1px solid <?php echo e($primaryColor); ?>;
            background: <?php echo e($primaryColor); ?>;
            color: #ffffff;
            padding: 7px;
            font-size: 9.3px;
            text-align: left;
            text-transform: uppercase;
        }

        .items td {
            border: 1px solid #e5e7eb;
            padding: 7px;
            vertical-align: top;
            color: #111827;
        }

        .items tr:nth-child(even) {
            background: #fafafa;
        }

        .badge {
            display: inline-block;
            padding: 3px 7px;
            border-radius: 999px;
            font-size: 8.5px;
            font-weight: bold;
            color: #ffffff;
            background: <?php echo e($secondaryColor); ?>;
        }

        .badge-success {
            background: <?php echo e($successColor); ?>;
        }

        .signature-block {
            margin-top: 20px;
            page-break-inside: avoid;
        }

        .signature-table {
            border-spacing: 8px 0;
            border-collapse: separate;
        }

        .signature-card {
            min-height: 116px;
            border: 1px solid #dbe4d3;
            background: #fbfdf9;
            padding: 10px;
            vertical-align: top;
        }

        .signature-title {
            margin-bottom: 7px;
            color: <?php echo e($secondaryColor); ?>;
            font-size: 9.5px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .signature-name {
            color: #111827;
            font-size: 12px;
            font-weight: bold;
        }

        .signature-line {
            margin-top: 14px;
            border-top: 1px solid #4b5563;
            padding-top: 5px;
        }

        .signature-img {
            max-width: 155px;
            max-height: 60px;
            display: block;
            margin: 4px auto 6px auto;
            object-fit: contain;
        }

        .signature-placeholder {
            height: 58px;
            border: 1px dashed #9ca3af;
            background: #ffffff;
            text-align: center;
            color: #6b7280;
            font-size: 9px;
            line-height: 58px;
            margin-bottom: 6px;
        }

        .stamp-wrap {
            text-align: center;
        }

        .stamp-img {
            max-width: 118px;
            max-height: 96px;
            display: block;
            margin: 0 auto 5px auto;
            object-fit: contain;
        }

        .stamp-placeholder {
            width: 96px;
            height: 96px;
            margin: 0 auto 6px auto;
            border: 2px dashed <?php echo e($primaryColor); ?>;
            border-radius: 50%;
            display: table;
            background: #ffffff;
        }

        .stamp-placeholder span {
            display: table-cell;
            vertical-align: middle;
            text-align: center;
            color: <?php echo e($primaryColor); ?>;
            font-size: 10px;
            font-weight: bold;
            line-height: 1.35;
        }

        .qr-box {
            text-align: center;
        }

        .qr-image-wrap,
        .qr-fallback {
            width: 96px;
            height: 96px;
            margin: 0 auto 6px auto;
            border: 2px solid <?php echo e($primaryColor); ?>;
            background: #ffffff;
            padding: 4px;
        }

        .qr-image {
            width: 86px;
            height: 86px;
        }
    </style>
</head>

<body>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($logoBase64): ?>
        <div class="watermark">
            <img src="<?php echo e($logoBase64); ?>" alt="Watermark">
        </div>
    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>

    <header>
        <table class="header-table">
            <tr>
                <td width="150">
                    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($logoBase64): ?>
                        <img src="<?php echo e($logoBase64); ?>" class="logo" alt="Logo">
                    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                </td>

                <td>
                    <div class="company-title"><?php echo e($farmName); ?></div>
                    <div class="tagline"><?php echo e($farmTagline); ?></div>
                </td>

                <td class="header-right">
                    <strong>Phone:</strong> <?php echo e($farmPhone); ?><br>
                    <strong>Email:</strong> <?php echo e($farmEmail); ?><br>
                    <strong>Location:</strong> <?php echo e($farmAddress); ?>

                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table class="footer-table">
            <tr>
                <td class="footer-left">
                    Printed <?php echo e($eatNow->format('d M Y, H:i')); ?> EAT
                </td>
                <td class="footer-center">
                    <?php echo e($reportTitle); ?>

                </td>
                <td class="footer-right">
                    Created by <?php echo e($generatedByName); ?> (<?php echo e($generatedByRole); ?>)
                </td>
            </tr>
            <tr>
                <td colspan="3" class="footer-center small-muted">
                    <?php echo e($farmName); ?> • <?php echo e($farmCounty); ?> • <?php echo e($farmPhone); ?> • <?php echo e($farmEmail); ?>

                </td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="report-top">
            <table class="report-title-table">
                <tr>
                    <td>
                        <h1 class="report-title"><?php echo e($reportTitle); ?></h1>
                        <div class="report-subtitle"><?php echo e($reportSubtitle); ?></div>
                    </td>

                    <td class="report-total-box" width="210">
                        <div class="report-total-label">Total Locations</div>
                        <div class="report-total-value">
                            <?php echo e(number_format($totalLocations)); ?>

                        </div>
                    </td>
                </tr>
            </table>
        </div>

        <table class="kpi-table">
            <tr>
                <td class="kpi-card">
                    <div class="kpi-label">Locations</div>
                    <div class="kpi-value"><?php echo e(number_format($totalLocations)); ?></div>
                </td>

                <td class="kpi-card">
                    <div class="kpi-label">Active</div>
                    <div class="kpi-value"><?php echo e(number_format($activeLocations)); ?></div>
                </td>

                <td class="kpi-card">
                    <div class="kpi-label">Default</div>
                    <div class="kpi-value"><?php echo e(number_format($defaultLocations)); ?></div>
                </td>

                <td class="kpi-card">
                    <div class="kpi-label">Animals Assigned</div>
                    <div class="kpi-value"><?php echo e(number_format($totalAnimals)); ?></div>
                </td>
            </tr>
        </table>

        <table class="items">
            <thead>
                <tr>
                    <th width="4%">#</th>
                    <th width="16%">Location</th>
                    <th width="9%">Code</th>
                    <th width="12%">Type</th>
                    <th width="13%">County</th>
                    <th width="13%">Area</th>
                    <th width="9%">Animals</th>
                    <th width="8%">Default</th>
                    <th width="8%">Active</th>
                    <th width="8%">GPS</th>
                </tr>
            </thead>

            <tbody>
                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $locations; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $index => $location): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                    <tr>
                        <td><?php echo e($index + 1); ?></td>
                        <td><strong><?php echo e($location->name); ?></strong><br><span class="small-muted"><?php echo e($location->address ?: 'No address recorded'); ?></span></td>
                        <td><?php echo e($location->code ?: '-'); ?></td>
                        <td><?php echo e(filled($location->type) ? str($location->type)->replace('_', ' ')->headline() : 'Other'); ?></td>
                        <td><?php echo e($location->county ?: '-'); ?></td>
                        <td><?php echo e($location->sub_county ?: '-'); ?></td>
                        <td><?php echo e(number_format((int) ($location->animals_count ?? 0))); ?></td>
                        <td>
                            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($location->is_default): ?>
                                <span class="badge">Default</span>
                            <?php else: ?>
                                -
                            <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                        </td>
                        <td>
                            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($location->is_active): ?>
                                <span class="badge badge-success">Active</span>
                            <?php else: ?>
                                -
                            <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                        </td>
                        <td>
                            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(filled($location->latitude) && filled($location->longitude)): ?>
                                <?php echo e($location->latitude); ?>, <?php echo e($location->longitude); ?>

                            <?php else: ?>
                                -
                            <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                    <tr>
                        <td colspan="10" style="text-align:center;">No locations found.</td>
                    </tr>
                <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
            </tbody>
        </table>

        <div class="signature-block">
            <table class="signature-table">
                <tr>
                    <td class="signature-card" style="width: 26%;">
                        <div class="signature-title">Prepared By</div>
                        <div class="signature-name"><?php echo e($generatedByName); ?></div>
                        <div class="small-muted"><?php echo e($generatedByRole); ?></div>
                        <div class="signature-line"></div>
                        <div class="small-muted">
                            Generated <?php echo e($eatNow->format('d M Y, H:i')); ?> EAT
                        </div>
                    </td>

                    <td class="signature-card" style="width: 28%; text-align: center;">
                        <div class="signature-title">Authorized Signature</div>

                        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($signatureBase64): ?>
                            <img src="<?php echo e($signatureBase64); ?>" class="signature-img" alt="Authorized Signature">
                        <?php else: ?>
                            <div class="signature-placeholder">Signature not uploaded</div>
                        <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>

                        <div class="small-muted">
                            <?php echo e($farmName); ?> Management Approval
                        </div>
                    </td>

                    <td class="signature-card stamp-wrap" style="width: 22%;">
                        <div class="signature-title">Official Stamp</div>

                        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($stampBase64): ?>
                            <img src="<?php echo e($stampBase64); ?>" class="stamp-img" alt="Official Stamp">
                        <?php else: ?>
                            <div class="stamp-placeholder">
                                <span>STAMP<br>NOT<br>UPLOADED</span>
                            </div>
                        <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>

                        <div class="small-muted"><?php echo e($farmName); ?></div>
                    </td>

                    <td class="signature-card" style="width: 24%;">
                        <div class="qr-box">
                            <div class="signature-title">Verification</div>

                            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(! empty($qrPng)): ?>
                                <div class="qr-image-wrap">
                                    <img src="data:image/png;base64,<?php echo e($qrPng); ?>" class="qr-image" alt="QR Code">
                                </div>
                            <?php else: ?>
                                <div class="qr-fallback">
                                    <span class="small-muted">QR not available</span>
                                </div>
                            <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>

                            <div class="small-muted">
                                Scan to verify location report metadata
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </main>

    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
                $font = $fontMetrics->getFont('Helvetica', 'normal');
                $size = 8.5;

                $text = "Page {$pageNumber} of {$pageCount}";
                $width = $fontMetrics->getTextWidth($text, $font, $size);

                $x = ($canvas->get_width() - $width) / 2;
                $y = $canvas->get_height() - 30;

                $canvas->text($x, $y, $text, $font, $size, [0.42, 0.45, 0.50]);
            });
        }
    </script>
</body>
</html>
<?php /**PATH /home/maurice/LocalDev/Penzi/resources/views/pdf/locations-report.blade.php ENDPATH**/ ?>