@php
    if (! function_exists('pdfImageBase64')) {
        function pdfImageBase64(?string $path): ?string
        {
            if (! $path) {
                return null;
            }

            $cleanPath = trim($path);
            $cleanPath = ltrim($cleanPath, '/');
            $cleanPath = preg_replace('#^storage/#', '', $cleanPath);

            $possiblePaths = [
                storage_path('app/public/' . $cleanPath),
                public_path('storage/' . $cleanPath),
                public_path($cleanPath),
            ];

            foreach ($possiblePaths as $fullPath) {
                if (is_file($fullPath)) {
                    $extension = strtolower(pathinfo($fullPath, PATHINFO_EXTENSION));
                    $mime = match ($extension) {
                        'jpg', 'jpeg' => 'image/jpeg',
                        'png' => 'image/png',
                        'gif' => 'image/gif',
                        'webp' => 'image/webp',
                        'svg' => 'image/svg+xml',
                        'ico' => 'image/x-icon',
                        default => 'image/png',
                    };

                    return 'data:' . $mime . ';base64,' . base64_encode(file_get_contents($fullPath));
                }
            }

            return null;
        }
    }

    $eatNow = $snapshot['generated_at'] ?? now('Africa/Nairobi');
    $farmName = setting('farm.name', 'Lelekwe Farms');
    $farmTagline = setting('farm.tagline', 'Nurturing Nature, Feeding The Future');
    $farmPhone = setting('farm.phone', '+254 743 487 186');
    $farmEmail = setting('farm.email', 'jambo@lelekwefarms.co.ke');
    $farmCounty = setting('farm.county', 'Ravine, Kambi Moto');

    $primaryColor = setting('theme.primary', '#014a12');
    $secondaryColor = setting('theme.secondary', '#14532d');
    $accentColor = setting('theme.accent', '#f59e0b');
    $dangerColor = setting('theme.danger', '#dc2626');
    $successColor = setting('theme.success', '#16a34a');

    $logoBase64 = pdfImageBase64(setting('branding.logo_light'));
    $generatedByName = $generatedBy->name ?? 'System';
    $reportTitle = 'Livestock Activity Snapshot Report';

    $verificationText = $farmName . ' Livestock Snapshot | Generated by: ' . $generatedByName . ' (' . $generatedByRole . ')' . ' | Date: ' . $eatNow->format('Y-m-d H:i:s') . ' EAT | Period: ' . ($snapshot['period_label'] ?? '-') . ' | Total Animals: ' . number_format($snapshot['total'] ?? 0);

    $qrPng = null;
    if (class_exists(\SimpleSoftwareIO\QrCode\Facades\QrCode::class)) {
        try {
            $qrPng = base64_encode(\SimpleSoftwareIO\QrCode\Facades\QrCode::format('png')->size(110)->margin(1)->generate($verificationText));
        } catch (\Throwable $e) {
            $qrPng = null;
        }
    }

    $total = max((int) ($snapshot['total'] ?? 0), 1);
@endphp

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $reportTitle }}</title>
    <style>
        @font-face {
            font-family: "ChopinScript";
            src: url("{{ public_path('fonts/ChopinScript.ttf') }}") format("truetype");
            font-weight: normal;
            font-style: normal;
        }
        @page { size: A4 landscape; margin: 105px 28px 85px 28px; }
        body { font-family: Courier, "Courier New", monospace; font-size: 11px; color: #111827; position: relative; background: #fff; }
        .watermark { position: fixed; top: 30%; left: 12%; width: 75%; opacity: 0.055; z-index: -1; text-align: center; }
        .watermark img { width: 420px; }
        header { position: fixed; top: -95px; left: 0; right: 0; height: 90px; border-bottom: 2px solid {{ $primaryColor }}; }
        .header-table, .footer-table, .signature-table, table.report { width: 100%; border-collapse: collapse; }
        .header-table td { vertical-align: middle; }
        .header-left { text-align: left; } .header-center { text-align: center; } .header-right { text-align: right; font-size: 10px; line-height: 1.5; color: #374151; }
        .logo { width: 180px; max-height: 75px; object-fit: contain; }
        .company-title { font-size: 22px; font-weight: 700; color: {{ $primaryColor }}; margin-bottom: 2px; text-align: center; }
        .tagline { font-size: 11px; color: #4b5563; font-style: italic; text-align: center; }
        footer { position: fixed; bottom: -72px; left: 0; right: 0; height: 62px; border-top: 1px solid #d1d5db; font-size: 10px; color: #4b5563; }
        .footer-table { margin-top: 8px; } .footer-left { text-align: left; width: 33%; } .footer-center { text-align: center; width: 34%; } .footer-right { text-align: right; width: 33%; } .small-muted { color: #6b7280; font-size: 9px; }
        .report-title { margin: 0 0 14px 0; padding: 13px 14px; border-left: 5px solid {{ $primaryColor }}; background: #f8fafc; }
        .report-title h1 { font-size: 18px; margin: 0 0 4px 0; color: #111827; }
        .report-title p { margin: 0; color: {{ $primaryColor }}; font-size: 10px; font-weight: bold; }
        .meta-table { width: 100%; border-collapse: separate; border-spacing: 8px; margin: 8px -8px 14px -8px; }
        .meta-card { border: 1px solid #dbe4d3; background: #fbfdf9; border-radius: 8px; padding: 10px; }
        .meta-label { color: #6b7280; font-size: 8px; font-weight: bold; text-transform: uppercase; letter-spacing: .4px; }
        .meta-value { color: #111827; font-size: 14px; font-weight: bold; margin-top: 3px; }
        .section-title { margin: 18px 0 8px; color: {{ $secondaryColor }}; font-size: 13px; font-weight: bold; text-transform: uppercase; letter-spacing: .45px; border-bottom: 1px solid #d1d5db; padding-bottom: 5px; }
        .explanation { background: #fffdf4; border: 1px solid #fde68a; border-radius: 8px; padding: 10px 12px; color: #374151; line-height: 1.55; margin-bottom: 10px; }
        .insight-list { margin: 0; padding-left: 18px; } .insight-list li { margin-bottom: 7px; line-height: 1.5; }
        table.report { margin-top: 8px; }
        table.report thead th { background: {{ $primaryColor }}; border: 1px solid {{ $primaryColor }}; color: #fff; padding: 9px 8px; font-size: 10px; text-align: left; }
        table.report tbody td { border: 1px solid #e5e7eb; padding: 7px 8px; vertical-align: top; }
        table.report tbody tr:nth-child(even) { background: #fafafa; }
        .number { text-align: right; font-weight: bold; }
        .badge { display:inline-block; padding:3px 7px; border-radius:999px; color:#fff; background: {{ $secondaryColor }}; font-size:9px; font-weight:bold; }
        .bar-wrap { width: 120px; height: 8px; border-radius: 999px; background: #e5e7eb; overflow: hidden; }
        .bar-fill { height: 8px; border-radius: 999px; background: {{ $primaryColor }}; }
        .section-block { margin-top: 28px; page-break-inside: avoid; }
        .signature-table td { vertical-align: top; }
        .signature-card { border: 1px solid #dbe4d3; border-radius: 10px; padding: 12px 14px; background: #fbfdf9; min-height: 120px; }
        .signature-card-authorized { border: 1px solid #cfe3bf; background: #f8fff2; }
        .signature-card-title { font-size: 11px; font-weight: bold; color: {{ $secondaryColor }}; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.4px; }
        .signature-name { font-size: 13px; font-weight: bold; color: #111827; margin-bottom: 4px; }
        .signature-meta { font-size: 9px; color: #6b7280; margin-bottom: 12px; }
        .signature-line { border-top: 1px solid #4b5563; margin-top: 18px; padding-top: 6px; }
        .signature-footer { font-size: 9px; color: #6b7280; margin-top: 4px; }
        .signature-handwritten { font-family: "ChopinScript" !important; font-size: 25px; color: {{ $primaryColor }}; letter-spacing: 1px; }
        .stamp-wrap { padding-top: 4px; text-align: center; }
        .stamp-circle { width: 110px; height: 110px; margin: 0 auto 8px auto; border: 1px dashed {{ $primaryColor }}; border-radius: 50%; display: table; }
        .stamp-text { display: table-cell; vertical-align: middle; text-align: center; font-size: 12px; font-weight: bold; color: {{ $primaryColor }}; line-height: 1.4; }
        .stamp-caption { font-size: 9px; color: #6b7280; text-align: center; }
        .qr-box { text-align: center; } .qr-image-wrap { width: 104px; height: 104px; margin: 4px auto 8px auto; padding: 4px; border: 2px solid {{ $primaryColor }}; background: #fff; border-radius: 8px; } .qr-image { width: 90px; height: 90px; display: block; margin: 0 auto; } .qr-caption { font-size: 8px; color: #6b7280; margin-top: 6px; line-height: 1.4; } .qr-fallback { width: 104px; height: 104px; margin: 4px auto 8px auto; border: 1px solid #999; border-radius: 8px; font-size: 9px; display: table; background: #fff; } .qr-fallback span { display: table-cell; vertical-align: middle; text-align: center; }
    
        /* Landscape PDF fit */
        table.report {
            width: 100%;
            table-layout: fixed;
        }

        table.report th,
        table.report td {
            word-wrap: break-word;
            overflow-wrap: break-word;
        }

        .landscape-grid-2 {
            width: 100%;
            border-collapse: separate;
            border-spacing: 10px;
        }

        .landscape-grid-2 td {
            width: 50%;
            vertical-align: top;
        }

    </style>
</head>
<body>
    <div class="watermark">@if ($logoBase64)<img src="{{ $logoBase64 }}" alt="Watermark">@endif</div>
    <header>
        <table class="header-table"><tr>
            <td class="header-left" width="110">@if ($logoBase64)<img src="{{ $logoBase64 }}" class="logo" alt="Logo">@endif</td>
            <td class="header-center"><div class="company-title">{{ $farmName }}</div><div class="tagline">{{ $farmTagline }}</div></td>
            <td class="header-right" width="230"><strong>Phone:</strong> {{ $farmPhone }}<br><strong>Email:</strong> {{ $farmEmail }}<br><strong>County:</strong> {{ $farmCounty }}</td>
        </tr></table>
    </header>
    <footer>
        <table class="footer-table"><tr>
            <td class="footer-left">Generated on {{ $eatNow->format('d M Y, H:i') }} EAT</td>
            <td class="footer-center">{{ $reportTitle }}</td>
            <td class="footer-right">Created by {{ $generatedByName }} ({{ $generatedByRole }})</td>
        </tr><tr><td colspan="3" class="footer-center small-muted">{{ $farmName }} • {{ $farmCounty }} • {{ $farmPhone }} • {{ $farmEmail }}</td></tr></table>
    </footer>

    <main>
        <div class="report-title">
            <h1>{{ $reportTitle }}</h1>
            <p>Period: {{ $snapshot['period_label'] ?? '-' }} • As At: {{ $snapshot['as_at_label'] ?? '-' }} • Total Animals: {{ number_format($snapshot['total'] ?? 0) }}</p>
        </div>

        <table class="meta-table"><tr>
            <td class="meta-card"><div class="meta-label">Total Animals</div><div class="meta-value">{{ number_format($snapshot['total'] ?? 0) }}</div></td>
            <td class="meta-card"><div class="meta-label">Active Rate</div><div class="meta-value">{{ number_format($snapshot['active_rate'] ?? 0, 1) }}%</div></td>
            <td class="meta-card"><div class="meta-label">Exit Rate</div><div class="meta-value">{{ number_format($snapshot['exit_rate'] ?? 0, 1) }}%</div></td>
            <td class="meta-card"><div class="meta-label">New Additions</div><div class="meta-value">{{ number_format($snapshot['additions'] ?? 0) }}</div></td>
        </tr></table>

        <div class="section-title">Executive Explanation</div>
        <div class="explanation">
            This report provides a management snapshot of livestock records as at the selected report date. It summarises current animal numbers, status movement, breed concentration, period additions and operational events so the farm can quickly identify herd strength, losses, commercial exits and data-cleaning gaps.
        </div>
        <ul class="insight-list">
            @foreach (($snapshot['insights'] ?? []) as $insight)
                <li>{{ $insight }}</li>
            @endforeach
        </ul>

        <div class="section-title">Status Distribution</div>
        <table class="report">
            <thead><tr><th>Status</th><th width="16%">Animals</th><th width="16%">Share</th><th width="22%">Visual</th><th>Management Meaning</th></tr></thead>
            <tbody>
                @forelse (($snapshot['status_rows'] ?? []) as $row)
                    @php $pct = (($row['total'] ?? 0) / $total) * 100; @endphp
                    <tr>
                        <td><span class="badge">{{ $row['label'] }}</span></td>
                        <td class="number">{{ number_format($row['total']) }}</td>
                        <td class="number">{{ number_format($pct, 1) }}%</td>
                        <td><div class="bar-wrap"><div class="bar-fill" style="width: {{ max(2, $pct) }}%"></div></div></td>
                        <td>Shows how much of the herd is currently sitting in this operational state.</td>
                    </tr>
                @empty
                    <tr><td colspan="5">No status data available.</td></tr>
                @endforelse
            </tbody>
        </table>

        <div class="section-title">Breed Composition</div>
        <table class="report">
            <thead><tr><th>#</th><th>Breed</th><th>Category</th><th width="16%">Total</th><th width="16%">Share</th></tr></thead>
            <tbody>
                @forelse (($snapshot['breed_rows'] ?? []) as $index => $row)
                    @php $pct = (($row['total'] ?? 0) / $total) * 100; @endphp
                    <tr><td>{{ $index + 1 }}</td><td>{{ $row['breed_name'] }}</td><td>{{ $row['parent_category'] }}</td><td class="number">{{ number_format($row['total']) }}</td><td class="number">{{ number_format($pct, 1) }}%</td></tr>
                @empty
                    <tr><td colspan="5">Breed data is not linked or not available.</td></tr>
                @endforelse
            </tbody>
        </table>

        <div class="section-title">Supporting Operational Snapshots</div>
        <table class="report">
            <thead><tr><th>Area</th><th>Label</th><th width="16%">Total</th><th>Explanation</th></tr></thead>
            <tbody>
                @foreach (['gender_rows' => 'Sex / Gender', 'stage_rows' => 'Stage', 'location_rows' => 'Location / Unit'] as $key => $title)
                    @forelse (($snapshot[$key]['rows'] ?? []) as $row)
                        <tr><td>{{ $title }}</td><td>{{ $row['label'] }}</td><td class="number">{{ number_format($row['total']) }}</td><td>Helps management understand distribution for planning, breeding, feeding, housing and operations.</td></tr>
                    @empty
                        <tr><td>{{ $title }}</td><td colspan="3">No data available.</td></tr>
                    @endforelse
                @endforeach
            </tbody>
        </table>

        <div class="section-title">Period Activity Events</div>
        <table class="report">
            <thead><tr><th>Event Type</th><th width="18%">Total</th><th>Explanation</th></tr></thead>
            <tbody>
                @forelse (($snapshot['events']['rows'] ?? []) as $row)
                    <tr><td>{{ $row['label'] }}</td><td class="number">{{ number_format($row['total']) }}</td><td>Operational event recorded within the selected period.</td></tr>
                @empty
                    <tr><td colspan="3">No animal events were found for this period.</td></tr>
                @endforelse
            </tbody>
        </table>

        <div class="section-block">
            <table class="signature-table"><tr>
                <td style="width: 26%; padding-top: 16px; padding-right: 8px;"><div class="signature-card"><div class="signature-card-title">Prepared By</div><div class="signature-name">{{ $generatedByName }}</div><div class="signature-meta">{{ $generatedByRole }}</div><div class="signature-line"></div><div class="signature-footer">Generated on {{ $eatNow->format('d M Y, H:i') }} EAT</div></div></td>
                <td style="width: 28%; padding-top: 16px; padding-right: 8px;"><div class="signature-card signature-card-authorized"><div class="signature-card-title">Authorized Signature</div><div class="signature-handwritten">Digitally Approved!</div><div class="signature-meta">Signature Date: {{ $eatNow->format('d M Y, H:i') }} EAT</div><div class="signature-line"></div><div class="signature-footer">{{ $farmName }} Management Approval</div></div></td>
                <td style="width: 22%; padding-top: 16px; padding-right: 8px;"><div class="stamp-wrap"><div class="stamp-circle"><div class="stamp-text">OFFICIAL<br>STAMP</div></div><div class="stamp-caption">{{ $farmName }} Stamp</div></div></td>
                <td style="width: 24%; padding-top: 16px;"><div class="qr-box">@if (! empty($qrPng))<div class="qr-image-wrap"><img src="data:image/png;base64,{{ $qrPng }}" alt="QR Code" class="qr-image"></div>@else<div class="qr-fallback"><span>QR not available</span></div>@endif<div class="qr-caption">Scan to verify report metadata</div></div></td>
            </tr></table>
        </div>
    </main>

    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
                $font = $fontMetrics->getFont('Helvetica', 'normal');
                $size = 9;
                $text = "Page {$pageNumber} of {$pageCount}";
                $width = $fontMetrics->getTextWidth($text, $font, $size);
                $x = 420 - ($width / 2);
                $y = 565;
                $canvas->text($x, $y, $text, $font, $size, [0.42, 0.45, 0.50]);
            });
        }
    </script>
</body>
</html>
