@php
    if (! function_exists('pdfImageBase64')) {
        function pdfImageBase64(?string $path): ?string
        {
            if (! $path) {
                return null;
            }

            $cleanPath = ltrim(trim($path), '/');
            $cleanPath = preg_replace('#^storage/#', '', $cleanPath);

            $possiblePaths = [
                storage_path('app/public/' . $cleanPath),
                public_path('storage/' . $cleanPath),
                public_path($cleanPath),
            ];

            foreach ($possiblePaths as $fullPath) {
                if (is_file($fullPath)) {
                    $extension = strtolower(pathinfo($fullPath, PATHINFO_EXTENSION));
                    $mime = match ($extension) {
                        'jpg', 'jpeg' => 'image/jpeg',
                        'png' => 'image/png',
                        'gif' => 'image/gif',
                        'webp' => 'image/webp',
                        'svg' => 'image/svg+xml',
                        default => 'image/png',
                    };

                    return 'data:' . $mime . ';base64,' . base64_encode(file_get_contents($fullPath));
                }
            }

            return null;
        }
    }

    $farmName = setting('farm.name', 'Lelekwe Farms Limited');
    $farmTagline = setting('farm.tagline', 'Nurturing Nature, Feeding The Future');
    $farmPhone = setting('farm.phone', '+254 743 487 186');
    $farmEmail = setting('farm.email', 'jambo@lelekwefarms.co.ke');
    $farmCounty = setting('farm.county', 'Ravine, Kambi Moto');
    $primaryColor = setting('theme.primary', '#14532d');
    $secondaryColor = setting('theme.secondary', '#166534');
    $accentColor = setting('theme.accent', '#f59e0b');
    $logoBase64 = pdfImageBase64(setting('branding.logo_light'));

    $generatedByName = $generatedBy?->name ?? 'System';
    $generatedByRole = method_exists($generatedBy, 'getRoleNames') ? ($generatedBy?->getRoleNames()?->first() ?? 'User') : 'User';
    $verificationText = $farmName . ' Farm Activity Snapshot | Period: ' . $data['periodLabel'] . ' | As at: ' . $data['asAtLabel'] . ' | Generated by: ' . $generatedByName . ' | Records: ' . $data['totalAsAt'];

    $qrPng = null;
    if (class_exists(\SimpleSoftwareIO\QrCode\Facades\QrCode::class)) {
        try {
            $qrPng = base64_encode(\SimpleSoftwareIO\QrCode\Facades\QrCode::format('png')->size(105)->margin(1)->generate($verificationText));
        } catch (\Throwable $e) {
            $qrPng = null;
        }
    }
@endphp

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Farm Activity Snapshot</title>

    <style>
        @font-face {
            font-family: "ChopinScript";
            src: url("{{ public_path('fonts/ChopinScript.ttf') }}") format("truetype");
            font-weight: normal;
            font-style: normal;
        }

        @page {
            margin: 120px 35px 95px 35px;
        }

        * {
            box-sizing: border-box;
        }

        html,
        body {
            margin: 0;
            padding: 0;
            font-family: Courier, "Courier New", monospace;
            font-size: 11px;
            color: #000;
            background: #fff;
        }

        .print-toolbar {
            position: fixed;
            top: 14px;
            right: 14px;
            z-index: 99;
        }

        .print-toolbar button {
            border: 0;
            border-radius: 8px;
            background: {{ $primaryColor }};
            color: #fff;
            padding: 9px 13px;
            font-family: Courier, "Courier New", monospace;
            font-weight: bold;
            cursor: pointer;
        }

        @media print {
            .print-toolbar {
                display: none !important;
            }
        }

        .watermark {
            position: fixed;
            top: 31%;
            left: 15%;
            width: 70%;
            opacity: 0.045;
            z-index: -1;
            text-align: center;
        }

        .watermark img {
            width: 420px;
        }

        header {
            position: fixed;
            top: -96px;
            left: 0;
            right: 0;
            height: 90px;
            border-bottom: 2px solid {{ $primaryColor }};
        }

        .header-table,
        .footer-table,
        .signature-table {
            width: 100%;
            border-collapse: collapse;
        }

        .header-table td {
            vertical-align: middle;
        }

        .logo {
            width: 160px;
            max-height: 75px;
            object-fit: contain;
        }

        .company-title {
            font-size: 21px;
            font-weight: 900;
            color: {{ $primaryColor }};
            text-align: center;
        }

        .tagline {
            margin-top: 2px;
            font-size: 10px;
            color: #374151;
            font-style: italic;
            text-align: center;
        }

        .header-right {
            text-align: right;
            font-size: 10px;
            line-height: 1.45;
            color: #111827;
        }

        footer {
            position: fixed;
            bottom: -72px;
            left: 0;
            right: 0;
            height: 62px;
            border-top: 1px solid #d1d5db;
            font-size: 9.5px;
            color: #111827;
        }

        .footer-table {
            margin-top: 8px;
        }

        .footer-left { text-align: left; width: 33%; }
        .footer-center { text-align: center; width: 34%; }
        .footer-right { text-align: right; width: 33%; }

        .report-hero {
            border: 1px solid #111827;
            border-left: 6px solid {{ $primaryColor }};
            padding: 14px 16px;
            background: #fff;
            color: #000;
            margin-bottom: 14px;
        }

        .report-kicker {
            font-size: 9px;
            font-weight: 900;
            letter-spacing: .08em;
            text-transform: uppercase;
            color: #000;
        }

        h1 {
            margin: 5px 0 4px 0;
            font-size: 20px;
            line-height: 1.15;
            color: #000;
        }

        .report-description {
            margin: 0;
            color: #000;
            font-size: 10.5px;
            line-height: 1.45;
        }

        .summary-grid {
            width: 100%;
            border-collapse: collapse;
            margin: 10px 0 16px;
        }

        .summary-grid td {
            width: 25%;
            border: 1px solid #d1d5db;
            padding: 10px;
            vertical-align: top;
            background: #fff;
        }

        .summary-label {
            font-size: 8.5px;
            font-weight: 900;
            letter-spacing: .06em;
            text-transform: uppercase;
            color: #000;
        }

        .summary-value {
            margin-top: 4px;
            font-size: 16px;
            font-weight: 900;
            color: #000;
            line-height: 1.1;
        }

        .summary-sub {
            margin-top: 4px;
            font-size: 8.8px;
            color: #111827;
            line-height: 1.35;
        }

        .section-title {
            margin: 18px 0 8px;
            padding: 8px 10px;
            border-left: 5px solid {{ $primaryColor }};
            background: #f3f4f6;
            color: #000;
            font-size: 12px;
            font-weight: 900;
            text-transform: uppercase;
            letter-spacing: .04em;
        }

        table.report {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }

        table.report th {
            background: #e5e7eb;
            border: 1px solid #111827;
            padding: 8px;
            color: #000;
            font-size: 9.5px;
            font-weight: 900;
            text-align: left;
        }

        table.report td {
            border: 1px solid #d1d5db;
            padding: 8px;
            color: #000;
            vertical-align: top;
        }

        table.report tbody tr:nth-child(even) td {
            background: #fafafa;
        }

        .status-dot {
            display: inline-block;
            width: 8px;
            height: 8px;
            border-radius: 999px;
            margin-right: 6px;
            background: {{ $primaryColor }};
        }

        .bar-wrap {
            height: 8px;
            background: #e5e7eb;
            border-radius: 99px;
            overflow: hidden;
            border: 1px solid #d1d5db;
        }

        .bar-fill {
            height: 100%;
            background: {{ $primaryColor }};
        }

        .signature-block {
            margin-top: 28px;
            page-break-inside: avoid;
        }

        .signature-table td {
            vertical-align: top;
            padding-right: 8px;
        }

        .signature-card {
            border: 1px solid #d1d5db;
            padding: 12px;
            min-height: 105px;
            background: #fff;
        }

        .signature-card-title {
            font-size: 9px;
            font-weight: 900;
            color: {{ $primaryColor }};
            text-transform: uppercase;
            letter-spacing: .04em;
            margin-bottom: 8px;
        }

        .signature-name {
            font-size: 12px;
            font-weight: 900;
            color: #000;
        }

        .signature-meta,
        .signature-footer {
            font-size: 8.8px;
            color: #374151;
            margin-top: 4px;
        }

        .signature-line {
            border-top: 1px solid #111827;
            margin-top: 18px;
            padding-top: 5px;
        }

        .signature-handwritten {
            font-family: "ChopinScript", cursive !important;
            font-size: 25px;
            color: {{ $primaryColor }} !important;
            letter-spacing: 1px;
        }

        .stamp-circle {
            width: 105px;
            height: 105px;
            border: 1px dashed {{ $primaryColor }};
            border-radius: 50%;
            display: table;
            margin: 0 auto 7px;
        }

        .stamp-text {
            display: table-cell;
            vertical-align: middle;
            text-align: center;
            color: {{ $primaryColor }};
            font-weight: 900;
            font-size: 11px;
            line-height: 1.35;
        }

        .qr-image-wrap {
            width: 96px;
            height: 96px;
            margin: 0 auto 6px;
            padding: 4px;
            border: 2px solid {{ $primaryColor }};
            background: #fff;
        }

        .qr-image {
            width: 84px;
            height: 84px;
        }

        .center { text-align: center; }
        .right { text-align: right; }
        .bold { font-weight: 900; }
        .small { font-size: 9px; }
    </style>
</head>
<body>
    <div class="print-toolbar">
        <button onclick="window.print()">Print Snapshot</button>
    </div>

    <div class="watermark">
        @if ($logoBase64)
            <img src="{{ $logoBase64 }}" alt="Watermark">
        @endif
    </div>

    <header>
        <table class="header-table">
            <tr>
                <td width="170">
                    @if ($logoBase64)
                        <img src="{{ $logoBase64 }}" class="logo" alt="Logo">
                    @endif
                </td>
                <td>
                    <div class="company-title">{{ $farmName }}</div>
                    <div class="tagline">{{ $farmTagline }}</div>
                </td>
                <td width="230" class="header-right">
                    <strong>Phone:</strong> {{ $farmPhone }}<br>
                    <strong>Email:</strong> {{ $farmEmail }}<br>
                    <strong>County:</strong> {{ $farmCounty }}
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table class="footer-table">
            <tr>
                <td class="footer-left">Printed {{ $data['generatedAt']->format('d M Y, H:i') }} EAT</td>
                <td class="footer-center">Farm Activity Snapshot</td>
                <td class="footer-right">Generated by {{ $generatedByName }} ({{ $generatedByRole }})</td>
            </tr>
            <tr>
                <td colspan="3" class="footer-center">{{ $farmName }} • {{ $farmCounty }} • {{ $farmPhone }} • {{ $farmEmail }}</td>
            </tr>
        </table>
    </footer>

    <main>
        <section class="report-hero">
            <div class="report-kicker">Livestock activity command report</div>
            <h1>Farm Activity Snapshot</h1>
            <p class="report-description">
                Animal numbers as at {{ $data['asAtLabel'] }}, grouped by operational status for director-level review. The report focuses on totals, status pressure, productive herd visibility and printable decision support.
            </p>
        </section>

        <table class="summary-grid">
            <tr>
                <td>
                    <div class="summary-label">Reporting period</div>
                    <div class="summary-value" style="font-size: 12px;">{{ $data['periodLabel'] }}</div>
                    <div class="summary-sub">Animals are counted as at {{ $data['asAtLabel'] }}.</div>
                </td>
                <td>
                    <div class="summary-label">Total as at date</div>
                    <div class="summary-value">{{ number_format($data['totalAsAt']) }}</div>
                    <div class="summary-sub">Total animal records captured up to period end.</div>
                </td>
                <td>
                    <div class="summary-label">Active / Current</div>
                    <div class="summary-value">{{ number_format($data['active']) }}</div>
                    <div class="summary-sub">{{ number_format($data['activeRate'], 2) }}% active herd indicator.</div>
                </td>
                <td>
                    <div class="summary-label">New in period</div>
                    <div class="summary-value">{{ number_format($data['newInPeriod']) }}</div>
                    <div class="summary-sub">New records created in selected period.</div>
                </td>
            </tr>
        </table>

        <div class="section-title">Animal status distribution</div>
        <table class="report">
            <thead>
                <tr>
                    <th width="25%">Status</th>
                    <th width="12%" class="right">Animals</th>
                    <th width="12%" class="right">Share</th>
                    <th width="22%">Visual Control</th>
                    <th width="29%">Director Decision Use</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data['statusDistribution'] as $row)
                    <tr>
                        <td><span class="status-dot" style="background: {{ $row['color'] }};"></span><span class="bold">{{ $row['label'] }}</span></td>
                        <td class="right bold">{{ number_format($row['value']) }}</td>
                        <td class="right">{{ number_format($row['percentage'], 2) }}%</td>
                        <td>
                            <div class="bar-wrap">
                                <div class="bar-fill" style="width: {{ min(100, $row['percentage']) }}%; background: {{ $row['color'] }};"></div>
                            </div>
                        </td>
                        <td>{{ $row['decision'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="section-title">Breed composition as at {{ $data['asAtLabel'] }}</div>
        <table class="report">
            <thead>
                <tr>
                    <th>Breed / Group</th>
                    <th width="20%" class="right">Animals</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($data['breedDistribution'] as $breed)
                    <tr>
                        <td>{{ $breed['label'] }}</td>
                        <td class="right bold">{{ number_format($breed['value']) }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="2" class="center">No breed distribution column detected.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        <div class="section-title">Management interpretation</div>
        <table class="report">
            <tbody>
                <tr>
                    <td width="28%" class="bold">Productive Herd</td>
                    <td>{{ number_format($data['productivePool']) }} animals remain available after excluding archived records. This is the key operational number for feeding, health and sales planning.</td>
                </tr>
                <tr>
                    <td class="bold">Mortality Control</td>
                    <td>{{ number_format($data['dead']) }} mortality records, representing {{ number_format($data['mortalityRate'], 2) }}% of the as-at animal base. Review vet notes where this is unusually high.</td>
                </tr>
                <tr>
                    <td class="bold">Sales / Disposal</td>
                    <td>{{ number_format($data['sold']) }} animals marked as sold. Link this to animal sale invoices, receivables and gross margin reporting.</td>
                </tr>
                <tr>
                    <td class="bold">Data Quality</td>
                    <td>{{ number_format($data['unknown']) }} records are unclassified or not mapped to the main status groups. Clean these before presenting final board reports.</td>
                </tr>
            </tbody>
        </table>

        <div class="signature-block">
            <table class="signature-table">
                <tr>
                    <td width="28%">
                        <div class="signature-card">
                            <div class="signature-card-title">Prepared By</div>
                            <div class="signature-name">{{ $generatedByName }}</div>
                            <div class="signature-meta">{{ $generatedByRole }}</div>
                            <div class="signature-line"></div>
                            <div class="signature-footer">Generated {{ $data['generatedAt']->format('d M Y, H:i') }} EAT</div>
                        </div>
                    </td>
                    <td width="30%">
                        <div class="signature-card">
                            <div class="signature-card-title">Authorized Signature</div>
                            <div class="signature-handwritten">Digitally Approved!</div>
                            <div class="signature-line"></div>
                            <div class="signature-footer">{{ $farmName }} Management Approval</div>
                        </div>
                    </td>
                    <td width="20%" class="center">
                        <div class="stamp-circle"><div class="stamp-text">OFFICIAL<br>STAMP</div></div>
                        <div class="small">{{ $farmName }} Stamp</div>
                    </td>
                    <td width="22%" class="center">
                        @if ($qrPng)
                            <div class="qr-image-wrap">
                                <img src="data:image/png;base64,{{ $qrPng }}" class="qr-image" alt="QR Code">
                            </div>
                        @else
                            <div class="qr-image-wrap small">QR unavailable</div>
                        @endif
                        <div class="small">Scan to verify report metadata</div>
                    </td>
                </tr>
            </table>
        </div>
    </main>

    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
                $font = $fontMetrics->getFont('Courier', 'normal');
                $size = 9;
                $text = "Page {$pageNumber} of {$pageCount}";
                $width = $fontMetrics->getTextWidth($text, $font, $size);
                $canvas->text(420 - ($width / 2), 565, $text, $font, $size, [0, 0, 0]);
            });
        }
    </script>
</body>
</html>
