@php
    if (! function_exists('farmActivityReportSetting')) {
        function farmActivityReportSetting(string $key, mixed $default = null): mixed
        {
            return function_exists('setting') ? setting($key, $default) : $default;
        }
    }

    if (! function_exists('farmActivityPdfImageBase64')) {
        function farmActivityPdfImageBase64(?string $path): ?string
        {
            if (! $path) {
                return null;
            }

            $cleanPath = ltrim(trim($path), '/');
            $cleanPath = preg_replace('#^storage/#', '', $cleanPath);

            $possiblePaths = [
                storage_path('app/public/' . $cleanPath),
                public_path('storage/' . $cleanPath),
                public_path($cleanPath),
            ];

            foreach ($possiblePaths as $fullPath) {
                if (is_file($fullPath)) {
                    $extension = strtolower(pathinfo($fullPath, PATHINFO_EXTENSION));
                    $mime = match ($extension) {
                        'jpg', 'jpeg' => 'image/jpeg',
                        'png' => 'image/png',
                        'gif' => 'image/gif',
                        'webp' => 'image/webp',
                        'svg' => 'image/svg+xml',
                        default => 'image/png',
                    };

                    return 'data:' . $mime . ';base64,' . base64_encode(file_get_contents($fullPath));
                }
            }

            return null;
        }
    }

    $farmName = farmActivityReportSetting('farm.name', 'Lelekwe Farms Limited');
    $farmTagline = farmActivityReportSetting('farm.tagline', 'Nurturing Nature, Feeding The Future');
    $farmPhone = farmActivityReportSetting('farm.phone', '+254 743 487 186');
    $farmEmail = farmActivityReportSetting('farm.email', 'jambo@lelekwefarms.co.ke');
    $farmCounty = farmActivityReportSetting('farm.county', 'Ravine, Kambi Moto');

    $primaryColor = farmActivityReportSetting('theme.primary', '#14532d');
    $secondaryColor = farmActivityReportSetting('theme.secondary', '#166534');
    $accentColor = farmActivityReportSetting('theme.accent', '#f59e0b');
    $dangerColor = farmActivityReportSetting('theme.danger', '#dc2626');
    $successColor = farmActivityReportSetting('theme.success', '#16a34a');

    $logoBase64 = farmActivityPdfImageBase64(farmActivityReportSetting('branding.logo_light'));

    $generatedBy = $reportMeta['generated_by'] ?? null;
    $generatedByName = $generatedBy?->name ?? 'System';
    $generatedByRole = method_exists($generatedBy, 'getRoleNames') ? ($generatedBy?->getRoleNames()?->first() ?? 'User') : 'User';
    $generatedAt = $reportMeta['generated_at'];
    $periodLabel = $reportMeta['period_label'];

    $verificationText = $farmName
        . ' Farm Animal Snapshot | Period: ' . $periodLabel
        . ' | Generated by: ' . $generatedByName
        . ' | Generated at: ' . $generatedAt->format('Y-m-d H:i:s') . ' EAT'
        . ' | Total animals: ' . number_format($metrics['total_animals'] ?? 0);

    $qrPng = null;

    if (class_exists(\SimpleSoftwareIO\QrCode\Facades\QrCode::class)) {
        try {
            $qrPng = base64_encode(
                \SimpleSoftwareIO\QrCode\Facades\QrCode::format('png')
                    ->size(115)
                    ->margin(1)
                    ->generate($verificationText)
            );
        } catch (\Throwable $e) {
            $qrPng = null;
        }
    }

    $statusColors = [
        'active' => $successColor,
        'dead' => $dangerColor,
        'culled' => '#64748b',
        'sold' => $accentColor,
        'archived' => '#2563eb',
        'breeders' => $secondaryColor,
        'unknown' => '#111827',
    ];
@endphp

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Farm Animal Snapshot Report</title>

    <style>
        @font-face {
            font-family: "ChopinScript";
            src: url("{{ public_path('fonts/ChopinScript.ttf') }}") format("truetype");
            font-weight: normal;
            font-style: normal;
        }

        @page {
            margin: 118px 34px 92px 34px;
        }

        * {
            box-sizing: border-box;
        }

        html,
        body {
            margin: 0;
            padding: 0;
            font-family: Courier, "Courier New", monospace;
            font-size: 10.5px;
            color: #111827;
            background: #ffffff;
        }

        .watermark {
            position: fixed;
            top: 21%;
            left: 20%;
            width: 60%;
            text-align: center;
            opacity: .055;
            z-index: -1;
        }

        .watermark img {
            width: 370px;
            max-height: 370px;
            object-fit: contain;
        }

        header {
            position: fixed;
            top: -92px;
            left: 0;
            right: 0;
            height: 88px;
            border-bottom: 2px solid {{ $primaryColor }};
        }

        footer {
            position: fixed;
            bottom: -70px;
            left: 0;
            right: 0;
            height: 60px;
            border-top: 1px solid #d1d5db;
            color: #4b5563;
            font-size: 9px;
        }

        .header-table,
        .footer-table,
        .report-table,
        .summary-table,
        .kpi-table,
        .signature-table,
        .two-col-table {
            width: 100%;
            border-collapse: collapse;
        }

        .header-table td {
            vertical-align: middle;
        }

        .header-left {
            width: 130px;
            text-align: left;
        }

        .header-center {
            text-align: center;
        }

        .header-right {
            width: 245px;
            text-align: right;
            line-height: 1.45;
            color: #374151;
            font-size: 9.5px;
        }

        .logo {
            width: 115px;
            max-height: 70px;
            object-fit: contain;
        }

        .company-title {
            font-size: 20px;
            line-height: 1.05;
            font-weight: 800;
            color: {{ $primaryColor }};
        }

        .tagline {
            margin-top: 3px;
            font-size: 10px;
            font-style: italic;
            color: #4b5563;
        }

        .footer-table {
            margin-top: 7px;
        }

        .footer-left { text-align: left; width: 33%; }
        .footer-center { text-align: center; width: 34%; }
        .footer-right { text-align: right; width: 33%; }

        .small-muted {
            color: #6b7280;
            font-size: 8.5px;
        }

        .hero {
            border: 1px solid #d1d5db;
            border-left: 7px solid {{ $primaryColor }};
            padding: 13px 14px;
            margin-bottom: 12px;
            background: #f8fafc;
            color: #111827;
        }

        .hero h1 {
            margin: 0 0 4px 0;
            font-size: 20px;
            line-height: 1.08;
            color: #111827;
            font-weight: 800;
        }

        .hero p {
            margin: 0;
            color: #111827;
            font-size: 10.2px;
            line-height: 1.45;
        }

        .hero-meta {
            margin-top: 9px;
        }

        .meta-card {
            border: 1px solid #d1d5db;
            background: #ffffff;
            padding: 8px;
            color: #111827;
        }

        .meta-label {
            text-transform: uppercase;
            letter-spacing: .04em;
            font-size: 8px;
            font-weight: 800;
            color: {{ $primaryColor }};
        }

        .meta-value {
            margin-top: 2px;
            font-size: 11px;
            font-weight: 800;
            color: #111827;
        }

        .section-title {
            margin: 14px 0 8px 0;
            padding: 7px 9px;
            border-left: 5px solid {{ $primaryColor }};
            background: #f3f4f6;
            color: #111827;
            font-size: 12px;
            font-weight: 800;
            text-transform: uppercase;
            letter-spacing: .03em;
        }

        .section-note {
            margin: -3px 0 8px 0;
            color: #374151;
            font-size: 9.4px;
            line-height: 1.45;
        }

        .kpi-table td {
            width: 20%;
            padding: 4px;
            vertical-align: top;
        }

        .kpi-card {
            min-height: 72px;
            border: 1px solid #d1d5db;
            background: #ffffff;
            padding: 8px;
            border-top: 4px solid {{ $primaryColor }};
        }

        .kpi-label {
            color: #4b5563;
            font-size: 8px;
            font-weight: 800;
            text-transform: uppercase;
            letter-spacing: .04em;
        }

        .kpi-value {
            margin-top: 5px;
            color: #111827;
            font-size: 20px;
            line-height: 1;
            font-weight: 800;
        }

        .kpi-sub {
            margin-top: 4px;
            color: #6b7280;
            font-size: 8.5px;
            line-height: 1.35;
        }

        .report-table th {
            background: #e5e7eb;
            color: #111827;
            border: 1px solid #9ca3af;
            padding: 7px 6px;
            text-align: left;
            font-size: 9px;
            font-weight: 800;
            text-transform: uppercase;
        }

        .report-table td {
            border: 1px solid #e5e7eb;
            padding: 6px;
            color: #111827;
            vertical-align: top;
            line-height: 1.35;
        }

        .report-table tbody tr:nth-child(even) td {
            background: #fafafa;
        }

        .right { text-align: right; }
        .center { text-align: center; }
        .bold { font-weight: 800; }

        .status-pill {
            display: inline-block;
            padding: 3px 7px;
            color: #ffffff;
            font-weight: 800;
            font-size: 8px;
            border-radius: 999px;
        }

        .bar-shell {
            width: 100%;
            height: 8px;
            border: 1px solid #d1d5db;
            background: #f3f4f6;
        }

        .bar-fill {
            height: 6px;
            background: {{ $primaryColor }};
        }

        .insight-box {
            border: 1px solid #d1d5db;
            border-left: 5px solid {{ $accentColor }};
            background: #fffbeb;
            padding: 8px 9px;
            margin-bottom: 6px;
            color: #111827;
        }

        .insight-title {
            font-weight: 800;
            color: #111827;
            margin-bottom: 2px;
        }

        .insight-body {
            color: #111827;
            line-height: 1.45;
        }

        .two-col-table td {
            width: 50%;
            vertical-align: top;
            padding-right: 8px;
        }

        .signature-table td {
            vertical-align: top;
        }

        .signature-card {
            border: 1px solid #d1d5db;
            background: #fbfdf9;
            min-height: 116px;
            padding: 10px 12px;
            color: #111827;
        }

        .signature-card-title {
            color: {{ $secondaryColor }};
            font-size: 9px;
            font-weight: 800;
            text-transform: uppercase;
            letter-spacing: .04em;
            margin-bottom: 8px;
        }

        .signature-name {
            color: #111827;
            font-size: 12px;
            font-weight: 800;
            margin-bottom: 3px;
        }

        .signature-meta {
            color: #6b7280;
            font-size: 8.5px;
            margin-bottom: 12px;
        }

        .signature-line {
            border-top: 1px solid #4b5563;
            margin-top: 17px;
            padding-top: 5px;
            color: #6b7280;
            font-size: 8.5px;
        }

        .signature-handwritten {
            font-family: "ChopinScript", cursive !important;
            font-size: 24px;
            letter-spacing: .8px;
            color: {{ $primaryColor }} !important;
            line-height: 1.2;
        }

        .stamp-wrap {
            text-align: center;
        }

        .stamp-circle {
            width: 106px;
            height: 106px;
            margin: 0 auto 7px auto;
            border: 1px dashed {{ $primaryColor }};
            border-radius: 50%;
            display: table;
        }

        .stamp-text {
            display: table-cell;
            vertical-align: middle;
            text-align: center;
            color: {{ $primaryColor }};
            font-size: 11px;
            font-weight: 800;
            line-height: 1.35;
        }

        .qr-box { text-align: center; }

        .qr-image-wrap {
            width: 104px;
            height: 104px;
            margin: 0 auto 6px auto;
            padding: 5px;
            border: 2px solid {{ $primaryColor }};
            background: #ffffff;
        }

        .qr-image {
            width: 90px;
            height: 90px;
        }

        .page-break {
            page-break-before: always;
        }
    </style>
</head>
<body>
    <div class="watermark">
        @if ($logoBase64)
            <img src="{{ $logoBase64 }}" alt="Watermark">
        @endif
    </div>

    <header>
        <table class="header-table">
            <tr>
                <td class="header-left">
                    @if ($logoBase64)
                        <img src="{{ $logoBase64 }}" class="logo" alt="Logo">
                    @endif
                </td>
                <td class="header-center">
                    <div class="company-title">{{ $farmName }}</div>
                    <div class="tagline">{{ $farmTagline }}</div>
                </td>
                <td class="header-right">
                    <strong>Phone:</strong> {{ $farmPhone }}<br>
                    <strong>Email:</strong> {{ $farmEmail }}<br>
                    <strong>County:</strong> {{ $farmCounty }}
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table class="footer-table">
            <tr>
                <td class="footer-left">Generated {{ $generatedAt->format('d M Y, H:i') }} EAT</td>
                <td class="footer-center">Farm Animal Snapshot Report</td>
                <td class="footer-right">Created by {{ $generatedByName }} ({{ $generatedByRole }})</td>
            </tr>
            <tr>
                <td colspan="3" class="footer-center small-muted">
                    {{ $farmName }} • {{ $farmCounty }} • {{ $farmPhone }} • {{ $farmEmail }}
                </td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="hero">
            <h1>{{ $reportMeta['title'] }}</h1>
            <p>{{ $reportMeta['subtitle'] }}</p>

            <table class="summary-table hero-meta">
                <tr>
                    <td style="width: 25%; padding-right: 6px;">
                        <div class="meta-card">
                            <div class="meta-label">Reporting Period</div>
                            <div class="meta-value">{{ $periodLabel }}</div>
                        </div>
                    </td>
                    <td style="width: 25%; padding-right: 6px;">
                        <div class="meta-card">
                            <div class="meta-label">Total Animals</div>
                            <div class="meta-value">{{ number_format($metrics['total_animals']) }}</div>
                        </div>
                    </td>
                    <td style="width: 25%; padding-right: 6px;">
                        <div class="meta-card">
                            <div class="meta-label">Active Rate</div>
                            <div class="meta-value">{{ number_format($ratios['active_rate'], 1) }}%</div>
                        </div>
                    </td>
                    <td style="width: 25%;">
                        <div class="meta-card">
                            <div class="meta-label">New In Period</div>
                            <div class="meta-value">{{ number_format($metrics['new_animals']) }}</div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>

        <div class="section-title">Executive Animal Position</div>
        <table class="kpi-table">
            <tr>
                <td>
                    <div class="kpi-card" style="border-top-color: {{ $successColor }};">
                        <div class="kpi-label">Active / Current</div>
                        <div class="kpi-value">{{ number_format($metrics['active']) }}</div>
                        <div class="kpi-sub">{{ number_format($ratios['active_rate'], 1) }}% of total records</div>
                    </div>
                </td>
                <td>
                    <div class="kpi-card" style="border-top-color: {{ $dangerColor }};">
                        <div class="kpi-label">Dead / Mortality</div>
                        <div class="kpi-value">{{ number_format($metrics['dead']) }}</div>
                        <div class="kpi-sub">{{ number_format($ratios['mortality_rate'], 1) }}% mortality indicator</div>
                    </div>
                </td>
                <td>
                    <div class="kpi-card" style="border-top-color: #64748b;">
                        <div class="kpi-label">Culled</div>
                        <div class="kpi-value">{{ number_format($metrics['culled']) }}</div>
                        <div class="kpi-sub">{{ number_format($ratios['culling_rate'], 1) }}% culling indicator</div>
                    </div>
                </td>
                <td>
                    <div class="kpi-card" style="border-top-color: {{ $accentColor }};">
                        <div class="kpi-label">Sold</div>
                        <div class="kpi-value">{{ number_format($metrics['sold']) }}</div>
                        <div class="kpi-sub">{{ number_format($ratios['sold_rate'], 1) }}% commercial exits</div>
                    </div>
                </td>
                <td>
                    <div class="kpi-card" style="border-top-color: {{ $secondaryColor }};">
                        <div class="kpi-label">Breeding Pool</div>
                        <div class="kpi-value">{{ number_format($metrics['breeders']) }}</div>
                        <div class="kpi-sub">{{ number_format($ratios['breeder_rate'], 1) }}% breeder concentration</div>
                    </div>
                </td>
            </tr>
        </table>

        <div class="section-title">Status Control Summary</div>
        <div class="section-note">
            This table gives directors a compact status view of the animal base as currently recorded up to the selected reporting date. Status history is dependent on the accuracy of recorded animal lifecycle updates.
        </div>

        <table class="report-table">
            <thead>
                <tr>
                    <th style="width: 18%;">Status</th>
                    <th style="width: 10%;" class="right">Animals</th>
                    <th style="width: 12%;" class="right">Share</th>
                    <th style="width: 26%;">Visualization</th>
                    <th>Director Interpretation</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($statusSummary as $key => $status)
                    @php
                        $color = $statusColors[$key] ?? $primaryColor;
                        $percent = min(100, max(0, (float) ($status['percentage'] ?? 0)));
                    @endphp
                    <tr>
                        <td>
                            <span class="status-pill" style="background: {{ $color }};">{{ $status['label'] }}</span>
                        </td>
                        <td class="right bold">{{ number_format($status['count']) }}</td>
                        <td class="right bold">{{ number_format($percent, 1) }}%</td>
                        <td>
                            <div class="bar-shell">
                                <div class="bar-fill" style="width: {{ $percent }}%; background: {{ $color }};"></div>
                            </div>
                        </td>
                        <td>{{ $status['description'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="section-title">Director-Level Insights</div>
        @foreach ($insights as $insight)
            <div class="insight-box">
                <div class="insight-title">{{ $insight['title'] }}</div>
                <div class="insight-body">{{ $insight['body'] }}</div>
            </div>
        @endforeach

        <div class="section-title">Breed and Classification Snapshot</div>
        <table class="two-col-table">
            <tr>
                <td>
                    <table class="report-table">
                        <thead>
                            <tr>
                                <th>Breed</th>
                                <th>Category</th>
                                <th class="right">Animals</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($breedSnapshot as $row)
                                <tr>
                                    <td>{{ $row['breed_name'] }}</td>
                                    <td>{{ $row['parent_category'] }}</td>
                                    <td class="right bold">{{ number_format($row['total']) }}</td>
                                </tr>
                            @empty
                                <tr><td colspan="3">Breed snapshot is not available because breed linkage is missing or not configured.</td></tr>
                            @endforelse
                        </tbody>
                    </table>
                </td>
                <td>
                    <table class="report-table">
                        <thead>
                            <tr>
                                <th>{{ $genderSnapshot['title'] }}</th>
                                <th class="right">Animals</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($genderSnapshot['rows'] as $row)
                                <tr>
                                    <td>{{ $row['label'] }}</td>
                                    <td class="right bold">{{ number_format($row['total']) }}</td>
                                </tr>
                            @empty
                                <tr><td colspan="2">Gender/sex breakdown is not available from the current animals table.</td></tr>
                            @endforelse
                        </tbody>
                    </table>

                    <br>

                    <table class="report-table">
                        <thead>
                            <tr>
                                <th>{{ $stageSnapshot['title'] }}</th>
                                <th class="right">Animals</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($stageSnapshot['rows'] as $row)
                                <tr>
                                    <td>{{ $row['label'] }}</td>
                                    <td class="right bold">{{ number_format($row['total']) }}</td>
                                </tr>
                            @empty
                                <tr><td colspan="2">Animal stage breakdown is not available from the current animals table.</td></tr>
                            @endforelse
                        </tbody>
                    </table>
                </td>
            </tr>
        </table>

        <div class="section-title">Period Movement and Event Trace</div>
        <table class="two-col-table">
            <tr>
                <td>
                    <table class="report-table">
                        <thead>
                            <tr>
                                <th>Day</th>
                                <th class="right">New Animals Added</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($dailyAdditions as $row)
                                <tr>
                                    <td>{{ $row['day'] }}</td>
                                    <td class="right bold">{{ number_format($row['total']) }}</td>
                                </tr>
                            @empty
                                <tr><td colspan="2">No daily animal additions were detected for the selected reporting period.</td></tr>
                            @endforelse
                        </tbody>
                    </table>
                </td>
                <td>
                    <table class="report-table">
                        <thead>
                            <tr>
                                <th>Animal Event Type</th>
                                <th class="right">Events</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($animalEvents['rows'] as $row)
                                <tr>
                                    <td>{{ $row['label'] }}</td>
                                    <td class="right bold">{{ number_format($row['total']) }}</td>
                                </tr>
                            @empty
                                <tr><td colspan="2">No animal event summary was detected for the selected period.</td></tr>
                            @endforelse
                            <tr>
                                <td class="bold">Total Events</td>
                                <td class="right bold">{{ number_format($animalEvents['total_events']) }}</td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </table>

        <div class="section-title">Approval and Verification</div>
        <table class="signature-table">
            <tr>
                <td style="width: 26%; padding-right: 8px;">
                    <div class="signature-card">
                        <div class="signature-card-title">Prepared By</div>
                        <div class="signature-name">{{ $generatedByName }}</div>
                        <div class="signature-meta">{{ $generatedByRole }}</div>
                        <div class="signature-line">Generated on {{ $generatedAt->format('d M Y, H:i') }} EAT</div>
                    </div>
                </td>
                <td style="width: 28%; padding-right: 8px;">
                    <div class="signature-card">
                        <div class="signature-card-title">Authorized Signature</div>
                        <div class="signature-handwritten">Digitally Approved!</div>
                        <div class="signature-meta">Signature Date: {{ $generatedAt->format('d M Y, H:i') }} EAT</div>
                        <div class="signature-line">{{ $farmName }} Management Approval</div>
                    </div>
                </td>
                <td style="width: 22%; padding-right: 8px;">
                    <div class="stamp-wrap">
                        <div class="stamp-circle">
                            <div class="stamp-text">OFFICIAL<br>STAMP</div>
                        </div>
                        <div class="small-muted">{{ $farmName }} Stamp</div>
                    </div>
                </td>
                <td style="width: 24%;">
                    <div class="qr-box">
                        @if ($qrPng)
                            <div class="qr-image-wrap">
                                <img src="data:image/png;base64,{{ $qrPng }}" alt="QR Code" class="qr-image">
                            </div>
                        @else
                            <div class="meta-card center">QR not available</div>
                        @endif
                        <div class="small-muted">Scan to verify report metadata</div>
                    </div>
                </td>
            </tr>
        </table>
    </main>

    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
                $font = $fontMetrics->getFont('Courier', 'normal');
                $size = 8.5;
                $text = "Page {$pageNumber} of {$pageCount}";
                $width = $fontMetrics->getTextWidth($text, $font, $size);
                $canvas->text(420 - ($width / 2), 560, $text, $font, $size, [0.25, 0.28, 0.32]);
            });
        }
    </script>
</body>
</html>
