@php
    if (!function_exists('pdfImageBase64')) {
        function pdfImageBase64(?string $path): ?string
        {
            if (!$path) {
                return null;
            }

            $cleanPath = trim($path);
            $cleanPath = ltrim($cleanPath, '/');

            // Handles values saved as: storage/logos/logo.png
            $cleanPath = preg_replace('#^storage/#', '', $cleanPath);

            $possiblePaths = [
                storage_path('app/public/' . $cleanPath),
                public_path('storage/' . $cleanPath),
                public_path($cleanPath),
            ];

            foreach ($possiblePaths as $fullPath) {
                if (is_file($fullPath)) {
                    $extension = strtolower(pathinfo($fullPath, PATHINFO_EXTENSION));

                    $mime = match ($extension) {
                        'jpg', 'jpeg' => 'image/jpeg',
                        'png' => 'image/png',
                        'gif' => 'image/gif',
                        'webp' => 'image/webp',
                        'svg' => 'image/svg+xml',
                        'ico' => 'image/x-icon',
                        default => 'image/png',
                    };

                    return 'data:' . $mime . ';base64,' . base64_encode(file_get_contents($fullPath));
                }
            }

            return null;
        }
    }

    $eatNow = now('Africa/Nairobi');

    $farmName = setting('farm.name', 'Lelekwe Farms');
    $farmTagline = setting('farm.tagline', 'Nurturing Nature, Feeding The Future');
    $farmPhone = setting('farm.phone', '+254 743 487 186');
    $farmEmail = setting('farm.email', 'jambo@lelekwefarms.co.ke');
    $farmCounty = setting('farm.county', 'Ravine, Kambi Moto');

    $primaryColor = setting('theme.primary', '#014a12');
    $secondaryColor = setting('theme.secondary', '#14532d');
    $accentColor = setting('theme.accent', '#f59e0b');
    $dangerColor = setting('theme.danger', '#dc2626');
    $successColor = setting('theme.success', '#16a34a');

    $logoBase64 = pdfImageBase64(setting('branding.logo_light'));

    $generatedByName = $generatedBy->name ?? 'System';
    $generatedByRole = $generatedByRole ?? 'User';

    $closedAt = $session->logout_at ?: $session->last_seen_at;

    $totalLogs = $logs->count();

    $createdCount = $logs->where('event', 'created')->count();
    $updatedCount = $logs->where('event', 'updated')->count();
    $deletedCount = $logs->whereIn('event', ['deleted', 'force_deleted'])->count();
    $printedCount = $logs->where('event', 'printed')->count();
    $exportedCount = $logs->where('event', 'exported')->count();

    $riskEvents = $logs->filter(
        fn($log) => in_array(
            $log->event,
            [
                'deleted',
                'force_deleted',
                'failed_login',
                'rejected',
                'stock_adjustment',
                'permission_changed',
                'payment_deleted',
                'payment_updated',
                'backdated_transaction',
            ],
            true,
        ),
    );

    $verificationText =
        $farmName .
        ' Audit Session Report | Session: ' .
        ($session->uuid ?: $session->id) .
        ' | User: ' .
        ($session->user_email ?: $session->actor_label) .
        ' | Generated by: ' .
        $generatedByName .
        ' (' .
        $generatedByRole .
        ')' .
        ' | Date: ' .
        $eatNow->format('Y-m-d H:i:s') .
        ' EAT | Total Events: ' .
        $totalLogs;

    $qrPng = null;

    if (class_exists(\SimpleSoftwareIO\QrCode\Facades\QrCode::class)) {
        try {
            $qrPng = base64_encode(
                \SimpleSoftwareIO\QrCode\Facades\QrCode::format('png')
                    ->size(110)
                    ->margin(1)
                    ->generate($verificationText),
            );
        } catch (\Throwable $e) {
            $qrPng = null;
        }
    }

    $eventBadgeClass = function (?string $event): string {
        return match ($event) {
            'created', 'login', 'restored', 'session_started' => 'role-manager',
            'updated', 'printed', 'exported', 'page_view', 'request' => 'role-vet',
            'deleted', 'failed_login', 'rejected', 'session_expired' => 'role-finance',
            'force_deleted' => 'role-admin',
            default => 'role-other',
        };
    };

    $severityBadgeClass = function (?string $severity): string {
        return match ($severity) {
            'danger' => 'role-admin',
            'warning' => 'role-finance',
            'success' => 'role-manager',
            'info' => 'role-vet',
            default => 'role-other',
        };
    };

    $formatDateTime = function ($date): string {
        return $date ? $date->format('d M Y, H:i:s') : 'N/A';
    };
@endphp

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Audit Session Report</title>

    <style>
        @font-face {
            font-family: "ChopinScript";
            src: url("{{ public_path('fonts/ChopinScript.ttf') }}") format("truetype");
            font-weight: normal;
            font-style: normal;
        }

        @page {
            margin: 120px 35px 95px 35px;
        }

        body {
            font-family: Courier, sans-serif;
            font-size: 10px;
            color: #222;
            position: relative;
        }

        .watermark {
            position: fixed;
            top: 26%;
            left: 12%;
            width: 75%;
            opacity: 0.055;
            z-index: -1;
            text-align: center;
        }

        .watermark img {
            width: 420px;
        }

        header {
            position: fixed;
            top: -95px;
            left: 0;
            right: 0;
            height: 90px;
            border-bottom: 2px solid {{ $primaryColor }};
        }

        .header-table {
            width: 100%;
            border-collapse: collapse;
        }

        .header-table td {
            vertical-align: middle;
        }

        .header-left {
            text-align: left;
        }

        .header-center {
            text-align: center;
        }

        .header-right {
            text-align: right;
            font-size: 10px;
            line-height: 1.5;
            color: #374151;
        }

        .logo {
            width: 180px;
            max-height: 75px;
            object-fit: contain;
        }

        .company-title {
            font-size: 22px;
            font-weight: 700;
            color: {{ $primaryColor }};
            margin-bottom: 2px;
            text-align: center;
        }

        .tagline {
            font-size: 11px;
            color: #4b5563;
            font-style: italic;
            text-align: center;
        }

        .report-title {
            margin-top: 5px;
            margin-bottom: 12px;
        }

        .report-title-table {
            width: 100%;
            border-collapse: collapse;
        }

        .report-title h1 {
            font-size: 18px;
            margin: 0 0 4px 0;
            color: #111827;
        }

        .report-title p {
            margin: 0;
            color: {{ $primaryColor }};
            font-size: 10px;
            line-height: 1.4;
        }

        .status-pill {
            display: inline-block;
            padding: 7px 12px;
            border-radius: 999px;
            background: {{ $primaryColor }};
            color: #fff;
            font-size: 10px;
            font-weight: bold;
        }

        .summary-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            margin-bottom: 8px;
        }

        .summary-table td {
            border: 1px solid #dbe4d3;
            background: #fbfdf9;
            padding: 9px 8px;
            vertical-align: top;
        }

        .summary-label {
            font-size: 8px;
            color: #6b7280;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 0.4px;
            margin-bottom: 4px;
        }

        .summary-value {
            font-size: 12px;
            font-weight: bold;
            color: #111827;
            line-height: 1.4;
        }

        .summary-note {
            margin-top: 3px;
            color: #6b7280;
            font-size: 8px;
            line-height: 1.4;
        }

        .section-heading {
            margin-top: 18px;
            margin-bottom: 8px;
            font-size: 12px;
            font-weight: bold;
            color: {{ $secondaryColor }};
            text-transform: uppercase;
            letter-spacing: .5px;
            border-left: 4px solid {{ $primaryColor }};
            padding-left: 8px;
        }

        table.report {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }

        table.report thead th {
            background: {{ $primaryColor }};
            border: 1px solid {{ $primaryColor }};
            color: #fff;
            padding: 8px 6px;
            font-size: 9px;
            text-align: left;
        }

        table.report tbody td {
            border: 1px solid #e5e7eb;
            padding: 7px 6px;
            vertical-align: top;
            font-size: 9px;
            line-height: 1.35;
        }

        table.report tbody tr:nth-child(even) {
            background: #fafafa;
        }

        .details-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }

        .details-table th {
            width: 16%;
            background: #f8fff2;
            border: 1px solid #dbe4d3;
            color: {{ $secondaryColor }};
            padding: 8px;
            text-align: left;
            font-size: 9px;
            text-transform: uppercase;
        }

        .details-table td {
            border: 1px solid #e5e7eb;
            padding: 8px;
            font-size: 9px;
            line-height: 1.4;
        }

        .role-badge {
            display: inline-block;
            padding: 3px 7px;
            border-radius: 999px;
            font-size: 9px;
            font-weight: bold;
            color: #fff;
            white-space: nowrap;
        }

        .role-admin {
            background: {{ $dangerColor }};
        }

        .role-manager {
            background: {{ $successColor }};
        }

        .role-finance {
            background: {{ $accentColor }};
        }

        .role-vet {
            background: {{ $secondaryColor }};
        }

        .role-other {
            background: #6b7280;
        }

        .section-block {
            margin-top: 28px;
        }

        .signature-table {
            width: 100%;
            border-collapse: collapse;
        }

        .signature-table td {
            vertical-align: top;
        }

        .signature-card {
            border: 1px solid #dbe4d3;
            border-radius: 10px;
            padding: 12px 14px;
            background: #fbfdf9;
            min-height: 120px;
        }

        .signature-card-authorized {
            border: 1px solid #cfe3bf;
            background: #f8fff2;
        }

        .signature-card-title {
            font-size: 11px;
            font-weight: bold;
            color: {{ $secondaryColor }};
            margin-bottom: 10px;
            text-transform: uppercase;
            letter-spacing: 0.4px;
        }

        .signature-name {
            font-size: 13px;
            font-weight: bold;
            color: #111827;
            margin-bottom: 4px;
        }

        .signature-meta {
            font-size: 9px;
            color: #6b7280;
            margin-bottom: 12px;
        }

        .signature-line {
            border-top: 1px solid #4b5563;
            margin-top: 18px;
            padding-top: 6px;
        }

        .signature-footer {
            font-size: 9px;
            color: #6b7280;
            margin-top: 4px;
        }

        .signature-handwritten {
            font-family: "ChopinScript" !important;
            font-size: 25px;
            color: {{ $successColor }};
            letter-spacing: 1px;
        }

        .stamp-wrap {
            padding-top: 4px;
            text-align: center;
        }

        .stamp-circle {
            width: 110px;
            height: 110px;
            margin: 0 auto 8px auto;
            border: 1px dashed {{ $primaryColor }};
            border-radius: 50%;
            display: table;
        }

        .stamp-text {
            display: table-cell;
            vertical-align: middle;
            text-align: center;
            font-size: 12px;
            font-weight: bold;
            color: {{ $primaryColor }};
            line-height: 1.4;
        }

        .stamp-caption {
            font-size: 9px;
            color: #6b7280;
            text-align: center;
        }

        .qr-box {
            text-align: center;
        }

        .qr-image-wrap {
            width: 104px;
            height: 104px;
            margin: 4px auto 8px auto;
            padding: 4px;
            border: 2px solid {{ $primaryColor }};
            background: #fff;
            border-radius: 8px;
        }

        .qr-image {
            width: 90px;
            height: 90px;
            display: block;
            margin: 0 auto;
        }

        .qr-caption {
            font-size: 8px;
            color: #6b7280;
            margin-top: 6px;
            line-height: 1.4;
        }

        .qr-fallback {
            width: 104px;
            height: 104px;
            margin: 4px auto 8px auto;
            border: 1px solid #999;
            border-radius: 8px;
            font-size: 9px;
            display: table;
            background: #fff;
        }

        .qr-fallback span {
            display: table-cell;
            vertical-align: middle;
            text-align: center;
        }

        footer {
            position: fixed;
            bottom: -72px;
            left: 0;
            right: 0;
            height: 62px;
            border-top: 1px solid #d1d5db;
            font-size: 10px;
            color: #4b5563;
        }

        .footer-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }

        .footer-left {
            text-align: left;
            width: 33%;
        }

        .footer-center {
            text-align: center;
            width: 34%;
        }

        .footer-right {
            text-align: right;
            width: 33%;
        }

        .small-muted {
            color: #6b7280;
            font-size: 9px;
        }

        .page-break {
            page-break-before: always;
        }
    </style>
</head>

<body>
    <div class="watermark">
        @if ($logoBase64)
            <img src="{{ $logoBase64 }}" alt="Watermark">
        @endif
    </div>

    <header>
        <table class="header-table">
            <tr>
                <td class="header-left" width="110">
                    @if ($logoBase64)
                        <img src="{{ $logoBase64 }}" class="logo" alt="Logo">
                    @endif
                </td>

                <td class="header-center">
                    <div class="company-title">{{ $farmName }}</div>
                    <div class="tagline">{{ $farmTagline }}</div>
                </td>

                <td class="header-right" width="230">
                    <strong>Phone:</strong> {{ $farmPhone }}<br>
                    <strong>Email:</strong> {{ $farmEmail }}<br>
                    <strong>County:</strong> {{ $farmCounty }}
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table class="footer-table">
            <tr>
                <td class="footer-left">
                    Printed on {{ $eatNow->format('d M Y, H:i') }} EAT
                </td>

                <td class="footer-center">
                    Audit Session Report
                </td>

                <td class="footer-right">
                    Created by {{ $generatedByName }} ({{ $generatedByRole }})
                </td>
            </tr>

            <tr>
                <td colspan="3" class="footer-center small-muted">
                    {{ $farmName }} • {{ $farmCounty }} • {{ $farmPhone }} • {{ $farmEmail }}
                </td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="report-title">
            <table class="report-title-table">
                <tr>
                    <td>
                        <h1>Audit Session Report</h1>
                        <p>
                            Complete session trail from login to logout/session expiry.
                            Total audit events: {{ number_format($totalLogs) }}.
                        </p>
                    </td>

                    <td style="text-align: right; width: 260px;">
                        <span class="status-pill">
                            {{ $session->status_label }} / {{ $session->logout_reason_label }}
                        </span>
                    </td>
                </tr>
            </table>
        </div>

        <table class="summary-table">
            <tr>
                <td width="17%">
                    <div class="summary-label">User</div>
                    <div class="summary-value">{{ $session->actor_label }}</div>
                    <div class="summary-note">{{ $session->user_email ?: 'N/A' }}</div>
                </td>

                <td width="17%">
                    <div class="summary-label">Login Time</div>
                    <div class="summary-value">{{ $formatDateTime($session->login_at) }}</div>
                </td>

                <td width="17%">
                    <div class="summary-label">Closed / Last Seen</div>
                    <div class="summary-value">{{ $formatDateTime($closedAt) }}</div>
                </td>

                <td width="13%">
                    <div class="summary-label">Duration</div>
                    <div class="summary-value">{{ $session->duration_label }}</div>
                </td>

                <td width="12%">
                    <div class="summary-label">Requests</div>
                    <div class="summary-value">{{ number_format((int) $session->request_count) }}</div>
                </td>

                <td width="12%">
                    <div class="summary-label">Events</div>
                    <div class="summary-value">{{ number_format($totalLogs) }}</div>
                </td>

                <td width="12%">
                    <div class="summary-label">Risk Events</div>
                    <div class="summary-value">{{ number_format($riskEvents->count()) }}</div>
                </td>
            </tr>
        </table>

        <div class="section-heading">Activity Breakdown</div>

        <table class="summary-table">
            <tr>
                <td width="16.66%">
                    <div class="summary-label">Created</div>
                    <div class="summary-value">{{ number_format($createdCount) }}</div>
                </td>

                <td width="16.66%">
                    <div class="summary-label">Updated</div>
                    <div class="summary-value">{{ number_format($updatedCount) }}</div>
                </td>

                <td width="16.66%">
                    <div class="summary-label">Deleted</div>
                    <div class="summary-value">{{ number_format($deletedCount) }}</div>
                </td>

                <td width="16.66%">
                    <div class="summary-label">Printed</div>
                    <div class="summary-value">{{ number_format($printedCount) }}</div>
                </td>

                <td width="16.66%">
                    <div class="summary-label">Exported</div>
                    <div class="summary-value">{{ number_format($exportedCount) }}</div>
                </td>

                <td width="16.66%">
                    <div class="summary-label">Email Status</div>
                    <div class="summary-value">{{ $session->emailed_at ? 'Sent' : 'Not Sent' }}</div>
                    <div class="summary-note">{{ $session->email_to ?: 'No recipient' }}</div>
                </td>
            </tr>
        </table>

        <div class="section-heading">Technical Details</div>

        <table class="details-table">
            <tr>
                <th>Session UUID</th>
                <td colspan="3">{{ $session->uuid ?: 'N/A' }}</td>
            </tr>

            <tr>
                <th>IP Address</th>
                <td>{{ $session->ip_address ?: 'N/A' }}</td>

                <th>Guard</th>
                <td>{{ $session->guard ?: 'N/A' }}</td>
            </tr>

            <tr>
                <th>First URL</th>
                <td colspan="3">{{ $session->first_url ?: 'N/A' }}</td>
            </tr>

            <tr>
                <th>Last URL</th>
                <td colspan="3">{{ $session->last_url ?: 'N/A' }}</td>
            </tr>

            <tr>
                <th>Device / Browser</th>
                <td colspan="3">{{ $session->user_agent ?: 'N/A' }}</td>
            </tr>
        </table>

        <div class="section-heading">Activity Timeline</div>

        <table class="report">
            <thead>
                <tr>
                    <th width="4%">#</th>
                    <th width="9%">Time</th>
                    <th width="10%">Action</th>
                    <th width="11%">Module</th>
                    <th width="13%">Record</th>
                    <th width="26%">Description</th>
                    <th width="9%">IP</th>
                    <th width="9%">Severity</th>
                    <th width="9%">HTTP</th>
                </tr>
            </thead>

            <tbody>
                @forelse ($logs as $index => $log)
                    <tr>
                        <td>{{ $index + 1 }}</td>

                        <td>{{ $log->created_at?->format('H:i:s') ?: '-' }}</td>

                        <td>
                            <span class="role-badge {{ $eventBadgeClass($log->event) }}">
                                {{ $log->event_label }}
                            </span>
                        </td>

                        <td>{{ $log->module ?: 'System' }}</td>

                        <td>{{ $log->record_label }}</td>

                        <td>{{ $log->description ?: '-' }}</td>

                        <td>{{ $log->ip_address ?: '-' }}</td>

                        <td>
                            <span class="role-badge {{ $severityBadgeClass($log->severity) }}">
                                {{ $log->severity_label }}
                            </span>
                        </td>

                        <td>
                            {{ $log->http_method ?: '-' }}
                            @if ($log->response_status)
                                / {{ $log->response_status }}
                            @endif
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="9" style="text-align: center;">
                            No audit events found for this session.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        <div class="section-block">
            <table class="signature-table">
                <tr>
                    <td style="width: 26%; padding-top: 16px; padding-right: 8px;">
                        <div class="signature-card">
                            <div class="signature-card-title">Prepared By</div>

                            <div class="signature-name">{{ $generatedByName }}</div>

                            <div class="signature-meta">{{ $generatedByRole }}</div>

                            <div class="signature-line"></div>

                            <div class="signature-footer">
                                Generated on {{ $eatNow->format('d M Y, H:i') }} EAT
                            </div>
                        </div>
                    </td>

                    <td style="width: 28%; padding-top: 16px; padding-right: 8px;">
                        <div class="signature-card signature-card-authorized">
                            <div class="signature-card-title">Authorized Signature</div>

                            <div class="signature-handwritten">
                                Digitally Verified!
                            </div>

                            <div class="signature-meta">
                                Verification Date: {{ $eatNow->format('d M Y, H:i') }} EAT
                            </div>

                            <div class="signature-line"></div>

                            <div class="signature-footer">
                                {{ $farmName }} Management Review
                            </div>
                        </div>
                    </td>

                    <td style="width: 22%; padding-top: 16px; padding-right: 8px;">
                        <div class="stamp-wrap">
                            <div class="stamp-circle">
                                <div class="stamp-text">OFFICIAL<br>AUDIT<br>STAMP</div>
                            </div>

                            <div class="stamp-caption">{{ $farmName }} Stamp</div>
                        </div>
                    </td>

                    <td style="width: 24%; padding-top: 16px;">
                        <div class="qr-box">
                            @if (!empty($qrPng))
                                <div class="qr-image-wrap">
                                    <img src="data:image/png;base64,{{ $qrPng }}" alt="QR Code"
                                        class="qr-image">
                                </div>
                            @else
                                <div class="qr-fallback">
                                    <span>QR not available</span>
                                </div>
                            @endif

                            <div class="qr-caption">
                                Scan to verify report metadata
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </main>

    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
                $font = $fontMetrics->getFont('Helvetica', 'normal');
                $size = 9;

                $text = "Page {$pageNumber} of {$pageCount}";
                $width = $fontMetrics->getTextWidth($text, $font, $size);

                $x = 420 - ($width / 2);
                $y = 565;

                $canvas->text($x, $y, $text, $font, $size, [0.42, 0.45, 0.50]);
            });
        }
    </script>
</body>

</html>
