<?php

namespace App\Http\Controllers;

use App\Models\AnimalLabRequest;
use Barryvdh\DomPDF\Facade\Pdf;
use Carbon\Carbon;
use Carbon\CarbonInterface;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

class AnimalLabRequestPdfController extends Controller
{
    public function __invoke(AnimalLabRequest $labRequest)
    {
        $user = auth()->user();

        $hasRole = $user &&
            method_exists($user, 'hasAnyRole') &&
            $user->hasAnyRole([
                'Administrator',
                'Admin',
                'Manager',
                'Veterinary Officer',
                'Vet',
            ]);

        abort_unless(
            $user &&
                (
                    $user->can('view lab requests') ||
                    $user->can('view animals') ||
                    $hasRole
                ),
            403
        );

        $relations = [
            'animal.breed',
            'animal.location',
            'animal.latestWeight',
            'clinicalCase',
            'createdBy',
        ];

        if (method_exists($labRequest, 'veterinaryClinic')) {
            $relations[] = 'veterinaryClinic';
        }

        $labRequest->loadMissing($relations);

        $animal = $labRequest->animal;

        /*
         * Live records from:
         * health_administrations
         * health_administration_animals
         * health_products
         */
        $healthAdministrations = collect();

        if ($animal) {
            $healthAdministrations = DB::table(
                'health_administration_animals as haa'
            )
                ->join(
                    'health_administrations as ha',
                    'ha.id',
                    '=',
                    'haa.health_administration_id'
                )
                ->leftJoin(
                    'health_products as hp',
                    'hp.id',
                    '=',
                    'ha.health_product_id'
                )
                ->where('haa.animal_id', $animal->id)
                ->whereNull('ha.deleted_at')
                ->orderByDesc('ha.administered_at')
                ->select([
                    'ha.id',
                    'ha.administered_at',
                    'ha.next_due_date',
                    'ha.dosage_per_animal',
                    'ha.total_quantity_used',
                    'ha.administered_by',
                    'ha.notes',
                    'hp.name as product_name',
                    'hp.type as product_type',
                    'hp.dosage_unit as dosage_unit',
                ])
                ->limit(50)
                ->get()
                ->map(function ($record) {
                    $record->administered_at = $record->administered_at
                        ? Carbon::parse($record->administered_at)
                        : null;

                    $record->next_due_date = $record->next_due_date
                        ? Carbon::parse($record->next_due_date)
                        : null;

                    return $record;
                });
        }

        $clinic = method_exists($labRequest, 'veterinaryClinic')
            ? $labRequest->veterinaryClinic
            : null;

        $clinicName = $clinic?->display_name
            ?? $labRequest->clinic_name
            ?? 'Not recorded';

        $age = $animal?->date_of_birth
            ? $animal->date_of_birth->diffForHumans(now(), [
                'parts' => 3,
                'syntax' => CarbonInterface::DIFF_ABSOLUTE,
            ])
            : 'Not recorded';

        $generatedByRole = method_exists($user, 'getRoleNames')
            ? ($user->getRoleNames()->first() ?? 'User')
            : 'User';

        $verificationText = implode(' | ', [
            setting('farm.name', 'Penzi Farm Limited'),
            'Laboratory Request',
            $labRequest->request_number,
            $animal?->tag_number ?? 'Unknown Animal',
            'Generated by ' . $user->name,
            now('Africa/Nairobi')->format('Y-m-d H:i:s') . ' EAT',
        ]);

        $qrPng = null;

        try {
            $qrPng = base64_encode(
                QrCode::format('png')
                    ->size(120)
                    ->margin(1)
                    ->generate($verificationText)
            );
        } catch (\Throwable) {
            $qrPng = null;
        }

        $pdf = Pdf::loadView('pdf.animal-lab-request', [
            'labRequest' => $labRequest,
            'animal' => $animal,
            'clinic' => $clinic,
            'clinicName' => $clinicName,
            'healthAdministrations' => $healthAdministrations,
            'age' => $age,
            'generatedBy' => $user,
            'generatedByRole' => $generatedByRole,
            'generatedAt' => now('Africa/Nairobi'),
            'verificationText' => $verificationText,
            'qrPng' => $qrPng,
        ])
            ->setPaper('a4', 'portrait')
            ->setOptions([
                'dpi' => 96,
                'defaultFont' => 'Courier',

                /*
                 * |--------------------------------------------------------------------------
                 * | Force DomPDF to create and read custom-font metrics from storage/fonts,
                 * | never from vendor/dompdf/dompdf/lib/fonts.
                 * |--------------------------------------------------------------------------
                 */
                'fontDir' => storage_path('fonts'),
                'fontCache' => storage_path('fonts'),
                'chroot' => base_path(),
                'isRemoteEnabled' => false,
                'isPhpEnabled' => true,
            ]);

        return $pdf->stream(
            Str::upper($labRequest->request_number) . '-lab-request.pdf'
        );
    }
}
